# Chapter 2: Vectors, matrices and multidimensional arrays

Robert Johansson

Source code listings for [Numerical Python - Scientific Computing and Data Science Applications with Numpy, SciPy and Matplotlib](https://www.apress.com/us/book/9781484242452) (ISBN 978-1-484242-45-2).

In [1]:
import numpy as np

## The NumPy array object

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
print(data)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
data.ndim

2

In [7]:
data.shape

(4, 2)

In [8]:
data.size

8

In [9]:
data.dtype

dtype('int64')

In [10]:
data.nbytes

64

## Data types

In [11]:
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [12]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [13]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
data = np.array(object = [1, 2, 3], dtype=np.float)

In [15]:
data

array([1., 2., 3.])

In [16]:
data.dtype

dtype('float64')

In [17]:
data = np.array([1, 2, 3], dtype=np.int)

In [18]:
data.dtype

dtype('int64')

In [19]:
type(data)

numpy.ndarray

In [20]:
data

array([1, 2, 3])

In [21]:
data = np.array([1, 2, 3], dtype=np.float)

In [22]:
data

array([1., 2., 3.])

In [23]:
data2 = data.astype(np.int)
data2

array([1, 2, 3])

In [24]:
data

array([1., 2., 3.])

In [25]:
d1 = np.array([1, 2, 3], dtype=float)

In [26]:
d2 = np.array([1, 2, 3], dtype=complex)

In [27]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [28]:
(d1 + d2).dtype

dtype('complex128')

In [29]:
d2.dtype

dtype('complex128')

In [30]:
arrayWithDummies = np.sqrt(np.array([-1, 0, 1]))
arrayWithDummies

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [31]:
np.sqrt(arrayWithDummies)

array([nan,  0.,  1.])

In [32]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])


<font color='red'> redo color </font>

$ \color{red}{\text{another way to set color}} $

$\color{red}{\text{ciao}}$


### Real and imaginary parts


In [33]:
data = np.array([1, 2, 3], dtype=complex)

In [34]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [35]:
1 + 1j

(1+1j)

In [36]:
data.real

array([1., 2., 3.])

In [37]:
(1 + 1j).real

1.0

In [38]:
data.imag

array([0., 0., 0.])

## Creating arrays

### Arrays created from lists and other array-like objects

In [39]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [40]:
data.ndim

1

In [41]:
data.shape

(3,)

In [42]:
type(data.shape)

tuple

In [43]:
len(data.shape)

1

In [44]:
data = np.array([[1, 2], [3, 4]])

In [45]:
data.ndim

2

### Arrays filled with constant values

In [46]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.ones(4)

array([1., 1., 1., 1.])

In [48]:
data = np.ones(4)

In [49]:
data.dtype

dtype('float64')

In [50]:
data = np.ones(4, dtype=np.int64)

In [51]:
data.dtype

dtype('int64')

In [52]:
x1 = 5.4 * np.ones(10)
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [53]:
x2 = np.full(10, 5.4)
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [54]:
x1 = np.empty(5)
x1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [55]:
x1.fill(3.0)

In [56]:
x1

array([3., 3., 3., 3., 3.])

In [57]:
x2 = np.full(5, 3.0)

In [58]:
x2

array([3., 3., 3., 3., 3.])

### Arrays filled with incremental sequences

In [59]:
np.arange(0.0, stop=10, step=1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [60]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Arrays filled with logarithmic sequences

In [61]:
np.logspace(start=0, stop=2, num=5)  # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Mesh-grid arrays

In [62]:
x = np.array([-1, 0, 1])

In [63]:
y = np.array([-2, 0, 2])

In [64]:
X, Y = np.meshgrid(x, y)

In [65]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [66]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [67]:
Z = (X + Y) ** 2

In [68]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [69]:
W = (X, Y)
W

(array([[-1,  0,  1],
        [-1,  0,  1],
        [-1,  0,  1]]), array([[-2, -2, -2],
        [ 0,  0,  0],
        [ 2,  2,  2]]))

In [70]:
# How to put them in pairs?
# Perhaps, through concatenate?

### Creating uninitialized arrays

In [71]:
np.empty(3, dtype=np.float)

array([1., 2., 3.])

### Creating arrays with properties of other arrays

In [72]:
def f(x):
    y = np.ones_like(x)
    # compute with x and y
    return y

f(np.array([1, 2j]))    

array([1.+0.j, 1.+0.j])

### Creating matrix arrays

In [73]:
import numpy as np
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [75]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [76]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Index and slicing

In [77]:
# None + 5 # fails
np.nan + 5

nan

### One-dimensional arrays

In [78]:
a = np.arange(0, 11)

In [79]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
a[0]  # the first element

0

In [81]:
a[-1] # the last element

10

In [82]:
a[4]  # the fifth element, at index 4

4

In [83]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [85]:
a[:5]

array([0, 1, 2, 3, 4])

In [86]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [87]:
a[::-2]


array([10,  8,  6,  4,  2,  0])

In [88]:
a[0:10:-2]

array([], dtype=int64)

In [89]:
a[10:0:-2]

array([10,  8,  6,  4,  2])

## Multidimensional arrays

In [90]:
f = lambda m, n: n + 10 * m

In [91]:
f(1, 2)

12

In [92]:
A = np.fromfunction(f, (6, 6), dtype=int)

In [93]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [94]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41, 51])

In [95]:
A[1, :]  # the second row

array([10, 11, 12, 13, 14, 15])

In [96]:
A[:3, :3]  # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [97]:
A[3:, :3]  # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [98]:
A[::2, ::2]  # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [99]:
A[1::2, 1::3]  # every second element starting from 1, 1
# B: and every third element in columns

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views

In [100]:
B = A[1:5, 1:5]

In [101]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [102]:
B[:, :] = 0

In [103]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [104]:
C = B[1:3, 1:3].copy()

In [105]:
C

array([[0, 0],
       [0, 0]])

In [106]:
C[:, :] = 1  # this does not affect B the view B[1:3, 1:3]since C is a copy of 

In [107]:
C

array([[1, 1],
       [1, 1]])

In [108]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Fancy indexing and Boolean-valued indexing

In [109]:
A = np.linspace(0, 1, 11)

In [110]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [111]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

In [112]:
A > 0.5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [113]:
A[[False, False, False, False, False, False,  True,  True,  True, True,  True]]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [114]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [115]:
A = np.arange(10)

In [116]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
indices = [2, 4, 6]

In [118]:
B = A[indices]

In [119]:
B.shape

(3,)

In [120]:
A[[1, 2, 3]]

array([1, 2, 3])

If A is a list, then the transfer is by reference, and all we do with B, will happen to A. 
If A is np.ndarray, then the transfer is by copy, and B will be independent of A.
Indexes may be of any type. 
It matters, if the subject of copying A is numpy or simple numeric type.  


In [121]:
B[0] = -1  # this does not affect A

In [122]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
A[indices] = -1

In [124]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [125]:
A = np.arange(10)

In [126]:
B = A[A > 5]

In [127]:
B[0] = -1  # this does not affect A

In [128]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
A[A > 5] = -1

In [130]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

## Reshaping and resizing

In [131]:
data = np.array([[1, 2], [3, 4]])

In [132]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [133]:
data.reshape(4,)
data.reshape(4)

array([1, 2, 3, 4])

In [134]:
data.reshape([4])

array([1, 2, 3, 4])

In [135]:
# data.reshape([[4]]) 
# unlike tuple, in list we can not use nested square brackets
# Only round brackets. 

In [136]:
data.reshape((4))

array([1, 2, 3, 4])

In [137]:
data.reshape(((4)))

array([1, 2, 3, 4])

In [138]:
data = np.array([[1, 2], [3, 4]])

In [139]:
data

array([[1, 2],
       [3, 4]])

In [140]:
data.flatten()

array([1, 2, 3, 4])

In [141]:
data.flatten().shape

(4,)

In [142]:
data = np.arange(0, 5)

In [143]:
column = data[:, np.newaxis]

In [144]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [145]:
row = data[np.newaxis, :]

In [146]:
row

array([[0, 1, 2, 3, 4]])

In [147]:
data = np.arange(5)

In [148]:
data

array([0, 1, 2, 3, 4])

In [149]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [150]:
data = np.arange(5)

In [151]:
data

array([0, 1, 2, 3, 4])

In [152]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [153]:
data = data[:, np.newaxis]
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [154]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

## Vectorized expressions

### Arithmetic operations

In [155]:
x = np.array([[1, 2], [3, 4]]) 

In [156]:
y = np.array([[5, 6], [7, 8]])

In [157]:
x + y

array([[ 6,  8],
       [10, 12]])

In [158]:
y - x

array([[4, 4],
       [4, 4]])

In [159]:
x * y

array([[ 5, 12],
       [21, 32]])

In [160]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [161]:
x * 2

array([[2, 4],
       [6, 8]])

In [162]:
2 ** x

array([[ 2,  4],
       [ 8, 16]])

In [163]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [164]:
(y / 2).dtype

dtype('float64')

In [165]:
x = np.array([1, 2, 3, 4]).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [166]:
z = np.array([1, 2, 3, 4])

In [167]:
# x / z

In [168]:
z = np.array([[2, 4]])

In [169]:
z

array([[2, 4]])

In [170]:
z.shape

(1, 2)

In [171]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [172]:
zz = np.concatenate([z, z], axis=0)

In [173]:
zz

array([[2, 4],
       [2, 4]])

In [174]:
# compare
np.vstack([z, z])

array([[2, 4],
       [2, 4]])

In [175]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [176]:
z = np.array([[2], [4]])

In [177]:
z.shape

(2, 1)

In [178]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [179]:
zz = np.concatenate([z, z], axis=1)

In [180]:
zz

array([[2, 2],
       [4, 4]])

In [181]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [182]:
x = np.array([[1, 3], [2, 4]])
x = x + y
x

array([[ 6,  9],
       [ 9, 12]])

In [183]:
x = np.array([[1, 3], [2, 4]])
x += y
x

array([[ 6,  9],
       [ 9, 12]])

### Elementwise functions

In [184]:
x = np.linspace(-1, 1, 11)

In [185]:
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [186]:
y = np.sin(np.pi * x)

In [187]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [188]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [189]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [190]:
def heaviside(x):
    return 1 if x > 0 else 0

In [191]:
heaviside(-1)

0

In [192]:
heaviside(1.5)

1

In [193]:
x = np.linspace(-5, 5, 11)

In [194]:
# heaviside(x)

In [195]:
heaviside = np.vectorize(heaviside)

In [196]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [197]:
def heaviside(x):
    return 1.0 * (x > 0)

### Aggregate functions

In [198]:
data = np.random.normal(size=(15,15))

In [199]:
np.mean(data)

-0.07257405416460971

In [200]:
data.mean()

-0.07257405416460971

In [201]:
data = np.random.normal(size=(5, 10, 15))

In [202]:
data.sum(axis=0).shape

(10, 15)

In [203]:
data.sum(axis=(0, 2)).shape

(10,)

In [204]:
data.sum()

-9.121157880105216

In [205]:
data = np.arange(1,10).reshape(3,3)

In [206]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [207]:
data.sum()

45

In [208]:
data.sum(axis=0)

array([12, 15, 18])

In [209]:
data.sum(axis=1)

array([ 6, 15, 24])

### Boolean arrays and conditional expressions

In [210]:
a = np.array([1, 2, 3, 4])

In [211]:
b = np.array([4, 3, 2, 1])

In [212]:
a < b

array([ True,  True, False, False])

In [213]:
np.all(a < b)

False

In [214]:
np.any(a < b)

True

In [215]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elemment in b")
else:
    print("All elements in b are smaller than their corresponding element in a")

Some elements in a are smaller than their corresponding elemment in b


In [216]:
x = np.array([-2, -1, 0, 1, 2])

In [217]:
x > 0

array([False, False, False,  True,  True])

In [218]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [219]:
x * (x > 0)

array([0, 0, 0, 1, 2])

In [220]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [221]:
x = np.linspace(-5, 5, 11)
x = np.repeat(5, 11)
x

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [222]:
pulse(x, position=-4, height=15, width=5)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [223]:
pulse(x, position=1, height=15, width=5)

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [224]:
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width), 66)

In [225]:
x = np.linspace(-4, 4, 9)

In [226]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [227]:
np.select([x < -1, x < 2, x >= 2],
          [x**2  , x**3 , x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [228]:
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [229]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], 
          [x**2,    x**3,    x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [230]:
np.choose([2, 2, 2, 0, 0, 0, 1, 1, 1],
          [x**2,    x**3,    x**4])

array([256.,  81.,  16.,   1.,   0.,   1.,   8.,  27.,  64.])

In [231]:
indexes = [1, 2, 3, 3, 3, 3, 5]
values = [10, 20, 30, 40, 500, 600]
np.choose(indexes, values)

array([ 20,  30,  40,  40,  40,  40, 600])

In [232]:
[1, 2][1]

2

In [233]:
[[10, 20, 30, 40, 500, 600][i] for i in [1, 2, 3, 3, 3, 3, 5]]

[20, 30, 40, 40, 40, 40, 600]

In [234]:
from operator import itemgetter
a = [10, 20, 30, 40, 500, 600]
itemgetter(1, 2, 3, 3, 3, 3, 5)(a)

(20, 30, 40, 40, 40, 40, 600)

In [235]:
type(itemgetter(1, 2, 3, 3, 3, 3, 5))

operator.itemgetter

In [236]:
slice([1, 2])

slice(None, [1, 2], None)

In [237]:
# [10, 20, 30, 40, 500, 600][slice([1, 2])]

In [238]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

In [239]:
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [240]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8]),)

In [241]:
np.nonzero([True, True, True, True, False, True, True, True, True])

(array([0, 1, 2, 3, 5, 6, 7, 8]),)

In [242]:
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

In [243]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

Try to construct when these two are different

In [244]:
x1 = np.array([0, 1, 2, 3, 0, 0, 0, 5, 7])
x1[x1 >= 0]

array([0, 1, 2, 3, 0, 0, 0, 5, 7])

In [245]:
x1[np.nonzero(x1 >= 0)]

array([0, 1, 2, 3, 0, 0, 0, 5, 7])

# Set operations

In [246]:
a = np.unique([1,2,3,3])

In [247]:
b = np.unique([2,3,4,4,5,6,5])

In [248]:
np.in1d(a, b)

array([False,  True,  True])

In [249]:
1 in a

True

In [250]:
1 in b

False

In [251]:
np.all(np.in1d(a, b))

False

In [252]:
np.any(np.in1d(a, b))

True

In [253]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [254]:
np.intersect1d(a, b)

array([2, 3])

In [255]:
np.setdiff1d(a, b)

array([1])

In [256]:
np.setdiff1d(b, a)

array([4, 5, 6])

### Operations on arrays

In [257]:
data = np.arange(9).reshape(3, 3)

In [258]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [259]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [260]:
data = np.random.randn(1, 2, 3, 4, 5)

In [261]:
data.shape

(1, 2, 3, 4, 5)

In [262]:
data.ndim

5

In [263]:
data.T.shape

(5, 4, 3, 2, 1)

## Matrix and vector operations

Simpler

In [264]:
a = np.array([1, 2])
b = np.array([3, 4])
np.dot(a, b)

11

In [265]:
row = np.array([1, 2])
col = np.array([[3], [4]])
np.dot(a, b), np.dot(b, a)

(11, 11)

In [266]:
a.dot(b)

11

In [267]:
A = np.arange(1, 7).reshape(2, 3)

In [268]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [269]:
B = np.arange(1, 7).reshape(3, 2)

In [270]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [271]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [272]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [273]:
A.dot(B)

array([[22, 28],
       [49, 64]])

In [274]:
A = np.arange(9).reshape(3, 3)

In [275]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [276]:
x = np.arange(3)

In [277]:
x

array([0, 1, 2])

In [278]:
np.dot(A, x)

array([ 5, 14, 23])

In [279]:
A.dot(x)

array([ 5, 14, 23])

In [280]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)

In [281]:
Ap = B @ A @ np.linalg.inv(B)
Ap

array([[  2.03881253,  -4.98706888,   1.17069857],
       [  1.0023259 ,  -4.28781392,   1.04124119],
       [  3.18145048, -15.18393239,   3.62208611]])

In [282]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))
Ap

array([[  2.03881253,  -4.98706888,   1.17069857],
       [  1.0023259 ,  -4.28781392,   1.04124119],
       [  3.18145048, -15.18393239,   3.62208611]])

In [283]:
Ap = B.dot(A.dot(np.linalg.inv(B)))
Ap

array([[  2.03881253,  -4.98706888,   1.17069857],
       [  1.0023259 ,  -4.28781392,   1.04124119],
       [  3.18145048, -15.18393239,   3.62208611]])

In [284]:
A = np.matrix(A)

In [285]:
B = np.matrix(B)

stopped here

In [286]:
Ap = B * A * B.I

In [287]:
B

matrix([[0.90077719, 0.43146907, 0.74250483],
        [0.17856933, 0.18634047, 0.33874165],
        [0.23598297, 0.66866744, 0.94826803]])

In [288]:
B.I

matrix([[  1.81593458,  -3.18452412,  -0.28431755],
        [  3.25940961, -24.75557343,   6.29106555],
        [ -2.75026746,  18.2487849 ,  -3.31081138]])

In [289]:
A = np.asmatrix(A)

In [290]:
B = np.asmatrix(B)

In [291]:
Ap = B * A * B.I

In [292]:
Ap = np.asarray(Ap)

In [293]:
Ap

array([[  2.03881253,  -4.98706888,   1.17069857],
       [  1.0023259 ,  -4.28781392,   1.04124119],
       [  3.18145048, -15.18393239,   3.62208611]])

In [294]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
a.shape, a.ndim

((3, 4, 5, 6), 4)

In [295]:
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
b.shape

(5, 4, 6, 3)

In [296]:
np.array([1, 2, 3])[::-1]

array([3, 2, 1])

In [297]:
np.array([1, 2, 3])[0::1]

array([1, 2, 3])

In [298]:
np.dot(a, b)[2,3,2,1,2,2]

499128

In [299]:
np.dot(a, b).shape

(3, 4, 5, 5, 4, 3)

In [300]:
np.array([1, 2]).dot([3, 4])

11

In [301]:
np.array([1, 2]).dot([[3], [4]])

array([11])

In [302]:
# np.array([[1], [2]]).dot([[3], [4]])

In [303]:
sum(a[2,3,2,:] * b[1,2,:,2])

499128

In [304]:
np.inner(x, x)

5

In [305]:
np.dot(x, x)

5

In [306]:
y = x[:, np.newaxis]

In [307]:
y

array([[0],
       [1],
       [2]])

In [308]:
np.dot(y.T, y)

array([[5]])

In [309]:
x = np.array([1, 2, 3])

In [310]:
np.outer(x, x) 

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [311]:
np.kron(x, x) 

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

stopped here

In [312]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [313]:
np.kron(np.ones((2,2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [314]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [315]:
np.kron(np.identity(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [316]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [317]:
x = np.array([1, 2, 3, 4])

In [318]:
y = np.array([5, 6, 7, 8])

In [319]:
np.einsum("n,n", x, y)

70

In [320]:
np.inner(x, y)

70

In [321]:
A = np.arange(9).reshape(3, 3)

In [322]:
B = A.T

In [323]:
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [324]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True

In [325]:
 import numpy as np
 num = np.array([[1,2,3],[4,5,6],[7,8,9]])
 print(num[2][2])

9


In [326]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [327]:
np.random.rand()

0.5298699590949055

In [328]:
f = np.array([1,2])
g = np.array([4,5])
np.dot(f, g)

14

In [329]:
aa= np.array([[1,2],[4,5],[7,8]])
bb=np.transpose(aa,(1,0))
print(bb)

[[1 4 7]
 [2 5 8]]


In [330]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [331]:
arr%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

# Ragged numpy array

In [332]:
ragged = np.array([[1, 2], [3, 4, 5]], dtype=object)

In [333]:
ragged.shape

(2,)

In [334]:
try:
    ragged[0, 1]
except IndexError as e:
    print(f"{e}")

too many indices for array: array is 1-dimensional, but 2 were indexed


In [335]:
ragged[0][1]

2

In [336]:
ragged

array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [337]:
mat1 = np.array([
                 [1, 2], 
                 [3, 4]
])
mat1 * np.array([5, 6])

array([[ 5, 12],
       [15, 24]])