# Chapter 2: Vectors, matrices and multidimensional arrays

Robert Johansson

Source code listings for [Numerical Python - Scientific Computing and Data Science Applications with Numpy, SciPy and Matplotlib](https://www.apress.com/us/book/9781484242452) (ISBN 978-1-484242-45-2).

In [623]:
import numpy as np

## The NumPy array object

In [624]:
data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [625]:
type(data)

numpy.ndarray

In [626]:
data

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [627]:
data.ndim

2

In [628]:
data.shape

(4, 2)

In [629]:
data.size

8

In [630]:
data.dtype

dtype('int64')

In [631]:
data.nbytes

64

## Data types

In [632]:
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [633]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [634]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [635]:
data = np.array(object = [1, 2, 3], dtype=np.float)

In [636]:
data

array([1., 2., 3.])

In [637]:
data.dtype

dtype('float64')

In [638]:
data = np.array([1, 2, 3], dtype=np.int)

In [639]:
data.dtype

dtype('int64')

In [640]:
type(data)

numpy.ndarray

In [641]:
data

array([1, 2, 3])

In [642]:
data = np.array([1, 2, 3], dtype=np.float)

In [643]:
data

array([1., 2., 3.])

In [644]:
data2 = data.astype(np.int)
data2

array([1, 2, 3])

In [645]:
data

array([1., 2., 3.])

In [646]:
d1 = np.array([1, 2, 3], dtype=float)

In [647]:
d2 = np.array([1, 2, 3], dtype=complex)

In [648]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [649]:
(d1 + d2).dtype

dtype('complex128')

In [650]:
d2.dtype

dtype('complex128')

In [651]:
arrayWithDummies = np.sqrt(np.array([-1, 0, 1]))
arrayWithDummies

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [652]:
np.sqrt(arrayWithDummies)

array([nan,  0.,  1.])

In [653]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])


<font color='red'> redo color </font>

$ \color{red}{\text{another way to set color}} $

$\color{red}{\text{ciao}}$


### Real and imaginary parts


In [654]:
data = np.array([1, 2, 3], dtype=complex)

In [655]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [656]:
1 + 1j

(1+1j)

In [657]:
data.real

array([1., 2., 3.])

In [658]:
(1 + 1j).real

1.0

In [659]:
data.imag

array([0., 0., 0.])

## Creating arrays

### Arrays created from lists and other array-like objects

In [660]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [661]:
data.ndim

1

In [662]:
data.shape

(3,)

In [663]:
type(data.shape)

tuple

In [664]:
len(data.shape)

1

In [665]:
data = np.array([[1, 2], [3, 4]])

In [666]:
data.ndim

2

### Arrays filled with constant values

In [667]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [668]:
np.ones(4)

array([1., 1., 1., 1.])

In [669]:
data = np.ones(4)

In [670]:
data.dtype

dtype('float64')

In [671]:
data = np.ones(4, dtype=np.int64)

In [672]:
data.dtype

dtype('int64')

In [673]:
x1 = 5.4 * np.ones(10)
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [674]:
x2 = np.full(10, 5.4)
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [675]:
x1 = np.empty(5)
x1

array([9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323, 3.0e-323])

In [676]:
x1.fill(3.0)

In [677]:
x1

array([3., 3., 3., 3., 3.])

In [678]:
x2 = np.full(5, 3.0)

In [679]:
x2

array([3., 3., 3., 3., 3.])

### Arrays filled with incremental sequences

In [926]:
np.arange(0.0, stop=10, step=1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [681]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Arrays filled with logarithmic sequences

In [682]:
np.logspace(start=0, stop=2, num=5)  # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Mesh-grid arrays

In [683]:
x = np.array([-1, 0, 1])

In [684]:
y = np.array([-2, 0, 2])

In [685]:
X, Y = np.meshgrid(x, y)

In [686]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [687]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [688]:
Z = (X + Y) ** 2

In [689]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [690]:
W = (X, Y)
W

(array([[-1,  0,  1],
        [-1,  0,  1],
        [-1,  0,  1]]), array([[-2, -2, -2],
        [ 0,  0,  0],
        [ 2,  2,  2]]))

In [691]:
# How to put them in pairs?
# Perhaps, through concatenate?

### Creating uninitialized arrays

In [692]:
np.empty(3, dtype=np.float)

array([1., 2., 3.])

### Creating arrays with properties of other arrays

In [693]:
def f(x):
    y = np.ones_like(x)
    # compute with x and y
    return y

f(np.array([1, 2j]))    

array([1.+0.j, 1.+0.j])

### Creating matrix arrays

In [694]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [695]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [696]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [697]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Index and slicing

In [933]:
# None + 5 # fails
np.nan + 5

nan

### One-dimensional arrays

In [698]:
a = np.arange(0, 11)

In [699]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [700]:
a[0]  # the first element

0

In [701]:
a[-1] # the last element

10

In [702]:
a[4]  # the fifth element, at index 4

4

In [703]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [704]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [705]:
a[:5]

array([0, 1, 2, 3, 4])

In [706]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [707]:
a[::-2]


array([10,  8,  6,  4,  2,  0])

In [708]:
a[0:10:-2]

array([], dtype=int64)

In [709]:
a[10:0:-2]

array([10,  8,  6,  4,  2])

## Multidimensional arrays

In [710]:
f = lambda m, n: n + 10 * m

In [711]:
f(1, 2)

12

In [712]:
A = np.fromfunction(f, (6, 6), dtype=int)

In [713]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [714]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41, 51])

In [715]:
A[1, :]  # the second row

array([10, 11, 12, 13, 14, 15])

In [716]:
A[:3, :3]  # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [717]:
A[3:, :3]  # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [718]:
A[::2, ::2]  # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [719]:
A[1::2, 1::3]  # every second element starting from 1, 1
# B: and every third element in columns

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views

In [720]:
B = A[1:5, 1:5]

In [721]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [722]:
B[:, :] = 0

In [723]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [724]:
C = B[1:3, 1:3].copy()

In [725]:
C

array([[0, 0],
       [0, 0]])

In [726]:
C[:, :] = 1  # this does not affect B the view B[1:3, 1:3]since C is a copy of 

In [727]:
C

array([[1, 1],
       [1, 1]])

In [728]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Fancy indexing and Boolean-valued indexing

In [729]:
A = np.linspace(0, 1, 11)

In [730]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [731]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

In [732]:
A > 0.5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [733]:
A[[False, False, False, False, False, False,  True,  True,  True, True,  True]]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [734]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [735]:
A = np.arange(10)

In [736]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [737]:
indices = [2, 4, 6]

In [738]:
B = A[indices]

In [739]:
B.shape

(3,)

In [740]:
A[[1, 2, 3]]

array([1, 2, 3])

If A is a list, then the transfer is by reference, and all we do with B, will happen to A. 
If A is np.ndarray, then the transfer is by copy, and B will be independent of A.
Indexes may be of any type. 
It matters, if the subject of copying A is numpy or simple numeric type.  


In [741]:
B[0] = -1  # this does not affect A

In [742]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [743]:
A[indices] = -1

In [744]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [745]:
A = np.arange(10)

In [746]:
B = A[A > 5]

In [747]:
B[0] = -1  # this does not affect A

In [748]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [749]:
A[A > 5] = -1

In [750]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

## Reshaping and resizing

In [751]:
data = np.array([[1, 2], [3, 4]])

In [752]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [753]:
data.reshape(4,)
data.reshape(4)

array([1, 2, 3, 4])

In [754]:
data.reshape([4])

array([1, 2, 3, 4])

In [755]:
# data.reshape([[4]]) 
# unlike tuple, in list we can not use nested square brackets
# Only round brackets. 

In [756]:
data.reshape((4))

array([1, 2, 3, 4])

In [757]:
data.reshape(((4)))

array([1, 2, 3, 4])

In [758]:
data = np.array([[1, 2], [3, 4]])

In [759]:
data

array([[1, 2],
       [3, 4]])

In [760]:
data.flatten()

array([1, 2, 3, 4])

In [761]:
data.flatten().shape

(4,)

In [762]:
data = np.arange(0, 5)

In [763]:
column = data[:, np.newaxis]

In [764]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [765]:
row = data[np.newaxis, :]

In [766]:
row

array([[0, 1, 2, 3, 4]])

In [767]:
data = np.arange(5)

In [768]:
data

array([0, 1, 2, 3, 4])

$\color{red}{\text{Stopped here}}$

In [769]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [770]:
data = np.arange(5)

In [771]:
data

array([0, 1, 2, 3, 4])

In [772]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [773]:
data = data[:, np.newaxis]
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [774]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

## Vectorized expressions

### Arithmetic operations

In [775]:
x = np.array([[1, 2], [3, 4]]) 

In [776]:
y = np.array([[5, 6], [7, 8]])

In [777]:
x + y

array([[ 6,  8],
       [10, 12]])

In [778]:
y - x

array([[4, 4],
       [4, 4]])

In [779]:
x * y

array([[ 5, 12],
       [21, 32]])

In [780]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [781]:
x * 2

array([[2, 4],
       [6, 8]])

In [782]:
2 ** x

array([[ 2,  4],
       [ 8, 16]])

In [783]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [784]:
(y / 2).dtype

dtype('float64')

In [785]:
x = np.array([1, 2, 3, 4]).reshape(2,2)

In [786]:
z = np.array([1, 2, 3, 4])

In [787]:
# x / z

In [788]:
z = np.array([[2, 4]])

In [789]:
z

array([[2, 4]])

In [790]:
z.shape

(1, 2)

In [791]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [792]:
zz = np.concatenate([z, z], axis=0)

In [793]:
zz

array([[2, 4],
       [2, 4]])

In [794]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [795]:
z = np.array([[2], [4]])

In [796]:
z.shape

(2, 1)

In [797]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [798]:
zz = np.concatenate([z, z], axis=1)

In [799]:
zz

array([[2, 2],
       [4, 4]])

In [800]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [801]:
x = np.array([[1, 3], [2, 4]])
x = x + y
x

array([[ 6,  9],
       [ 9, 12]])

In [802]:
x = np.array([[1, 3], [2, 4]])
x += y
x

array([[ 6,  9],
       [ 9, 12]])

### Elementwise functions

In [803]:
x = np.linspace(-1, 1, 11)

In [804]:
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [805]:
y = np.sin(np.pi * x)

In [806]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [807]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [808]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [809]:
def heaviside(x):
    return 1 if x > 0 else 0

In [810]:
heaviside(-1)

0

In [811]:
heaviside(1.5)

1

In [812]:
x = np.linspace(-5, 5, 11)

In [813]:
# heaviside(x)

In [814]:
heaviside = np.vectorize(heaviside)

In [815]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [816]:
def heaviside(x):
    return 1.0 * (x > 0)

### Aggregate functions

In [817]:
data = np.random.normal(size=(15,15))

In [818]:
np.mean(data)

0.017487375791322392

In [819]:
data.mean()

0.017487375791322392

In [820]:
data = np.random.normal(size=(5, 10, 15))

In [821]:
data.sum(axis=0).shape

(10, 15)

In [822]:
data.sum(axis=(0, 2)).shape

(10,)

In [823]:
data.sum()

-6.441612745525994

In [824]:
data = np.arange(1,10).reshape(3,3)

In [825]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [826]:
data.sum()

45

In [827]:
data.sum(axis=0)

array([12, 15, 18])

In [828]:
data.sum(axis=1)

array([ 6, 15, 24])

### Boolean arrays and conditional expressions

In [829]:
a = np.array([1, 2, 3, 4])

In [830]:
b = np.array([4, 3, 2, 1])

In [831]:
a < b

array([ True,  True, False, False])

In [832]:
np.all(a < b)

False

In [833]:
np.any(a < b)

True

In [834]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elemment in b")
else:
    print("All elements in b are smaller than their corresponding element in a")

Some elements in a are smaller than their corresponding elemment in b


In [835]:
x = np.array([-2, -1, 0, 1, 2])

In [836]:
x > 0

array([False, False, False,  True,  True])

In [837]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [838]:
x * (x > 0)

array([0, 0, 0, 1, 2])

In [839]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [840]:
x = np.linspace(-5, 5, 11)

In [841]:
pulse(x, position=-2, height=1, width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [842]:
pulse(x, position=1, height=1, width=5)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [843]:
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))

In [844]:
x = np.linspace(-4, 4, 9)

In [845]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [846]:
np.select([x < -1, x < 2, x >= 2],
          [x**2  , x**3 , x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [847]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], 
          [x**2,    x**3,    x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [848]:
np.choose([2, 2, 2, 0, 0, 0, 1, 1, 1],
          [x**2,    x**3,    x**4])

array([256.,  81.,  16.,   1.,   0.,   1.,   8.,  27.,  64.])

In [849]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

In [850]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8]),)

In [851]:
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

# Set operations

In [852]:
a = np.unique([1,2,3,3])

In [853]:
b = np.unique([2,3,4,4,5,6,5])

In [854]:
np.in1d(a, b)

array([False,  True,  True])

In [855]:
1 in a

True

In [856]:
1 in b

False

In [857]:
np.all(np.in1d(a, b))

False

In [858]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [859]:
np.intersect1d(a, b)

array([2, 3])

In [860]:
np.setdiff1d(a, b)

array([1])

In [861]:
np.setdiff1d(b, a)

array([4, 5, 6])

### Operations on arrays

In [862]:
data = np.arange(9).reshape(3, 3)

In [863]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [864]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [865]:
data = np.random.randn(1, 2, 3, 4, 5)

In [866]:
data.shape

(1, 2, 3, 4, 5)

In [867]:
data.T.shape

(5, 4, 3, 2, 1)

## Matrix and vector operations

In [868]:
A = np.arange(1, 7).reshape(2, 3)

In [869]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [870]:
B = np.arange(1, 7).reshape(3, 2)

In [871]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [872]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [873]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [874]:
A = np.arange(9).reshape(3, 3)

In [875]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [876]:
x = np.arange(3)

In [877]:
x

array([0, 1, 2])

In [878]:
np.dot(A, x)

array([ 5, 14, 23])

In [879]:
A.dot(x)

array([ 5, 14, 23])

In [880]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)

In [881]:
Ap = B @ A @ np.linalg.inv(B)
Ap

array([[ 0.63949057, -0.43461199,  3.04527512],
       [ 0.29751114,  1.83386468, -1.48395349],
       [ 0.24761149,  1.28901497, -1.01809767]])

In [882]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))
Ap

array([[ 0.63949057, -0.43461199,  3.04527512],
       [ 0.29751114,  1.83386468, -1.48395349],
       [ 0.24761149,  1.28901497, -1.01809767]])

In [883]:
Ap = B.dot(A.dot(np.linalg.inv(B)))
Ap

array([[ 0.63949057, -0.43461199,  3.04527512],
       [ 0.29751114,  1.83386468, -1.48395349],
       [ 0.24761149,  1.28901497, -1.01809767]])

In [884]:
A = np.matrix(A)

In [885]:
B = np.matrix(B)

In [886]:
Ap = B * A * B.I

In [887]:
B

matrix([[0.51517699, 0.66318219, 0.23793191],
        [0.02822448, 0.29324119, 0.24712921],
        [0.00879724, 0.24578672, 0.19993735]])

In [888]:
B.I

matrix([[  0.89781899,  31.51805682, -40.02579934],
        [  1.4752663 , -42.91321436,  51.28654451],
        [ -1.85307646,  51.36722338, -56.2848075 ]])

In [889]:
A = np.asmatrix(A)

In [890]:
B = np.asmatrix(B)

In [891]:
Ap = B * A * B.I

In [892]:
Ap = np.asarray(Ap)

In [893]:
Ap

array([[ 0.63949057, -0.43461199,  3.04527512],
       [ 0.29751114,  1.83386468, -1.48395349],
       [ 0.24761149,  1.28901497, -1.01809767]])

In [894]:
np.inner(x, x)

5

In [895]:
np.dot(x, x)

5

In [896]:
y = x[:, np.newaxis]

In [897]:
y

array([[0],
       [1],
       [2]])

In [898]:
np.dot(y.T, y)

array([[5]])

In [899]:
x = np.array([1, 2, 3])

In [900]:
np.outer(x, x) 

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [901]:
np.kron(x, x) 

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [902]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [903]:
np.kron(np.ones((2,2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [904]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [905]:
np.kron(np.identity(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [906]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [907]:
x = np.array([1, 2, 3, 4])

In [908]:
y = np.array([5, 6, 7, 8])

In [909]:
np.einsum("n,n", x, y)

70

In [910]:
np.inner(x, y)

70

In [911]:
A = np.arange(9).reshape(3, 3)

In [912]:
B = A.T

In [913]:
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [914]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True

In [915]:
 import numpy as np
 num = np.array([[1,2,3],[4,5,6],[7,8,9]])
 print(num[2][2])

9


In [916]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [917]:
np.random.rand()

0.6995318120916251

In [918]:
f = np.array([1,2])
g = np.array([4,5])
np.dot(f, g)

14

In [919]:
aa= np.array([[1,2],[4,5],[7,8]])
bb=np.transpose(aa,(1,0))
print(bb)

[[1 4 7]
 [2 5 8]]


In [920]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [921]:
arr%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])