In [47]:
import numpy as np

In [48]:
# sample = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
# sample = [[1,2,3],[4,5,6],[7,8,9]]
sample = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
np.array(sample)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
"""
Lower triangle of an array.
Return a copy of an array with elements above the k-th diagonal zeroed.

[ numpy.tril(m, k=0) ]
"""
a = np.tril(sample, k=-1)
b = np.tril(sample, 0)

In [50]:
a

array([[ 0,  0,  0,  0],
       [ 5,  0,  0,  0],
       [ 9, 10,  0,  0],
       [13, 14, 15,  0]])

In [51]:
b

array([[ 1,  0,  0,  0],
       [ 5,  6,  0,  0],
       [ 9, 10, 11,  0],
       [13, 14, 15, 16]])

In [52]:
"""
Upper triangle of an array.
Return a copy of an array with the elements below the k-th diagonal zeroed.
"""
c = np.triu(sample, 1)
d = np.triu(sample, 0)

In [53]:
c

array([[ 0,  2,  3,  4],
       [ 0,  0,  7,  8],
       [ 0,  0,  0, 12],
       [ 0,  0,  0,  0]])

In [54]:
d

array([[ 1,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 0,  0, 11, 12],
       [ 0,  0,  0, 16]])

Lets operate with b and d matrix

In [55]:
b

array([[ 1,  0,  0,  0],
       [ 5,  6,  0,  0],
       [ 9, 10, 11,  0],
       [13, 14, 15, 16]])

In [56]:
d

array([[ 1,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 0,  0, 11, 12],
       [ 0,  0,  0, 16]])

In [57]:
# Adition
np.add(b,d)

array([[ 2,  2,  3,  4],
       [ 5, 12,  7,  8],
       [ 9, 10, 22, 12],
       [13, 14, 15, 32]])

In [58]:
b + d

array([[ 2,  2,  3,  4],
       [ 5, 12,  7,  8],
       [ 9, 10, 22, 12],
       [13, 14, 15, 32]])

In [59]:
# substract
np.subtract(b,d)

array([[  0,  -2,  -3,  -4],
       [  5,   0,  -7,  -8],
       [  9,  10,   0, -12],
       [ 13,  14,  15,   0]])

In [60]:
np.subtract(d,b)

array([[  0,   2,   3,   4],
       [ -5,   0,   7,   8],
       [ -9, -10,   0,  12],
       [-13, -14, -15,   0]])

In [61]:
print("Matrix Division : ")
print(np.divide(b,d))
print("-------------------------------------")
print("Multiplication of two matrices: ")
print(np.multiply(b,d))
print("-------------------------------------")
print("The product of two matrices : ")
print(np.dot(b,d))
print("-------------------------------------")
print("square root is : ")
print(np.sqrt(b))
print("-------------------------------------")
print("The summation of elements : ")
print(np.sum(d))
print("-------------------------------------")
print("The original d =")
print(d)
print("Sum of each column (rows change within each sum, axis=0)  : ")
print(np.sum(d,axis=0))
print("-------------------------------------")
print("Sum of each row (columns change within each sum, axis=1)  : ")
print(np.sum(d,axis=1))
print("-------------------------------------")
print("Matrix transposition : ")
print(b.T)

Matrix Division : 
[[ 1.  0.  0.  0.]
 [inf  1.  0.  0.]
 [inf inf  1.  0.]
 [inf inf inf  1.]]
-------------------------------------
Multiplication of two matrices: 
[[  1   0   0   0]
 [  0  36   0   0]
 [  0   0 121   0]
 [  0   0   0 256]]
-------------------------------------
The product of two matrices : 
[[  1   2   3   4]
 [  5  46  57  68]
 [  9  78 218 248]
 [ 13 110 302 600]]
-------------------------------------
square root is : 
[[1.         0.         0.         0.        ]
 [2.23606798 2.44948974 0.         0.        ]
 [3.         3.16227766 3.31662479 0.        ]
 [3.60555128 3.74165739 3.87298335 4.        ]]
-------------------------------------
The summation of elements : 
70
-------------------------------------
The original d =
[[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]]
Sum of each column (rows change within each sum, axis=0)  : 
[ 1  8 21 40]
-------------------------------------
Sum of each row (columns change within each sum, axis=1)  : 
[10 2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


## However triangular operations are supported in scipy.linalg


https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_triangular.html

scipy.linalg.solve_triangular - Solve the equation ax = b for x, assuming a is a triangular matrix.
Parameters
a - triangular matrix
b - Right-hand side matrix in ax = b

lower - Use only data contained in the lower triangle of a. Default is to use upper triangle.

trans{0, 1, 2, 'N', 'T', 'C'}

0 or ‘N’ - ax = b

1 or ‘T’ - a^T x = b

2 or ‘C’ - a^H x = b
	

In [62]:
from scipy.linalg import solve_triangular
a = np.array([[3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
b = np.array([4, 2, 4, 2])

In [63]:
a

array([[3, 0, 0, 0],
       [2, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 1, 1]])

In [64]:
b

array([4, 2, 4, 2])

In [65]:
x = solve_triangular(a, b, lower=True)
x

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [66]:
a.dot(x)  # Check the result

array([4., 2., 4., 2.])

In [67]:
A = np.array([
    [1, 1],
    [0, 1]
])

In [68]:
Ainv = solve_triangular(A, np.identity(A.shape[0]), lower=False)
Ainv

array([[ 1., -1.],
       [ 0.,  1.]])

In [69]:
np.linalg.inv(A)

array([[ 1., -1.],
       [ 0.,  1.]])