In [ ]:
import numpy as np
from sympy.matrices import Matrix, GramSchmidt
from sympy import init_printing
init_printing()

#Sympy
stopped here

In [ ]:
L = [Matrix([2,3,5]), Matrix([3,6,2]), Matrix([8,3,6])]
out1 = GramSchmidt(L)
out2 = GramSchmidt(L, True)
L

⎡⎡2⎤  ⎡3⎤  ⎡8⎤⎤
⎢⎢ ⎥  ⎢ ⎥  ⎢ ⎥⎥
⎢⎢3⎥, ⎢6⎥, ⎢3⎥⎥
⎢⎢ ⎥  ⎢ ⎥  ⎢ ⎥⎥
⎣⎣5⎦  ⎣2⎦  ⎣6⎦⎦

In [ ]:
out1

⎡     ⎡ 23 ⎤  ⎡ 1692 ⎤⎤
⎢     ⎢ ── ⎥  ⎢ ──── ⎥⎥
⎢     ⎢ 19 ⎥  ⎢ 353  ⎥⎥
⎢⎡2⎤  ⎢    ⎥  ⎢      ⎥⎥
⎢⎢ ⎥  ⎢ 63 ⎥  ⎢-1551 ⎥⎥
⎢⎢3⎥, ⎢ ── ⎥, ⎢──────⎥⎥
⎢⎢ ⎥  ⎢ 19 ⎥  ⎢ 706  ⎥⎥
⎢⎣5⎦  ⎢    ⎥  ⎢      ⎥⎥
⎢     ⎢-47 ⎥  ⎢-423  ⎥⎥
⎢     ⎢────⎥  ⎢───── ⎥⎥
⎣     ⎣ 19 ⎦  ⎣ 706  ⎦⎦

In [ ]:
out2

⎡⎡ √38 ⎤  ⎡ 23⋅√6707 ⎤  ⎡ 12⋅√706 ⎤⎤
⎢⎢ ─── ⎥  ⎢ ──────── ⎥  ⎢ ─────── ⎥⎥
⎢⎢  19 ⎥  ⎢   6707   ⎥  ⎢   353   ⎥⎥
⎢⎢     ⎥  ⎢          ⎥  ⎢         ⎥⎥
⎢⎢3⋅√38⎥  ⎢ 63⋅√6707 ⎥  ⎢-11⋅√706 ⎥⎥
⎢⎢─────⎥, ⎢ ──────── ⎥, ⎢─────────⎥⎥
⎢⎢  38 ⎥  ⎢   6707   ⎥  ⎢   706   ⎥⎥
⎢⎢     ⎥  ⎢          ⎥  ⎢         ⎥⎥
⎢⎢5⋅√38⎥  ⎢-47⋅√6707 ⎥  ⎢-3⋅√706  ⎥⎥
⎢⎢─────⎥  ⎢──────────⎥  ⎢──────── ⎥⎥
⎣⎣  38 ⎦  ⎣   6707   ⎦  ⎣  706    ⎦⎦

-------------------------------


#Custom

In [ ]:


def gramschmidt(A):
    """
    Applies the Gram-Schmidt method to A
    and returns Q and R, so Q*R = A.
    """
    R = np.zeros((A.shape[1], A.shape[1]))
    Q = np.zeros(A.shape)
    for k in range(0, A.shape[1]):
        R[k, k] = np.sqrt(np.dot(A[:, k], A[:, k])) # norm of kth column
        Q[:, k] = A[:, k]/R[k, k] # norming kth column
        for j in range(k+1, A.shape[1]):
            R[k, j] = np.dot(Q[:, k], A[:, j])
            A[:, j] = A[:, j] - R[k, j]*Q[:, k]
    return Q, R

def main():
    """
    Prompts for n and generates a random matrix.
    """
    #cols = int(input('give number of columns : '))
    #rows = int(input('give number of rows : '))
    cols = 2
    rows = 3
    A = np.random.rand(rows, cols)
    print('A = ')
    print(A)
    Q, R = gramschmidt(A)
    print('after gramschidt A = ')
    print(A)
    print('Q = ')
    print(Q)
    print('R = ')
    print(R)
    print('Q^T*Q = ')
    print(np.dot(Q.transpose(), Q))
    print('Q*R =')
    print(np.dot(Q, R))
    
    
main()

A = 
[[0.6372123  0.71979662]
 [0.60227241 0.04004634]
 [0.8328624  0.7944354 ]]
after gramschidt A = 
[[ 0.6372123   0.221141  ]
 [ 0.60227241 -0.43126679]
 [ 0.8328624   0.14267221]]
Q = 
[[ 0.52692209  0.43771014]
 [ 0.49802968 -0.85361759]
 [ 0.68870861  0.28239483]]
R = 
[[1.20931028 0.94635551]
 [0.         0.50522247]]
Q^T*Q = 
[[ 1.0000000e+00 -5.5828303e-16]
 [-5.5828303e-16  1.0000000e+00]]
Q*R =
[[0.6372123  0.71979662]
 [0.60227241 0.04004634]
 [0.8328624  0.7944354 ]]
