The paper we borrowed the code from:
https://techgoggler.com/computer-engineering/linear-equations-with-python-the-qr-decomposition/ 

In [213]:
import scipy.linalg as linalg
import numpy as np
# same matrix A and B as in LU decomposition
# There was an equation Ax = b
# A and b are given. 
# Then we have A = QR and substitute into the equation, having
# QR x = b
# Now premultiply both parts by Q.T = Q inv
# and have R x = Q.T b 
# solve it by the linalg.solve
# could also solve it using linalg.solve_triangular
# Nothing is checked. 
A = np.array([
                [2., 1., 1.],
                [1., 3., 2.],
                [1., 0., 0]])
b = np.array([4., 5., 6.])
Q, R = linalg.qr(A) # QR decomposition with qr function
y = np.dot(Q.T, b) # Let y=Q'.B using matrix multiplication
x = linalg.solve(R, y) # Solve Rx=y
x
# Can not extract any moral from this example

array([  6.,  15., -23.])

In [214]:
import scipy.linalg 
P, L, U = scipy.linalg.lu(A)

In [215]:
L@U

array([[ 2.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  3.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00, -2.77555756e-17,  2.77555756e-17]])

In [216]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0.5, -0.2,  1. ]])

In [217]:
U

array([[ 2. ,  1. ,  1. ],
       [ 0. ,  2.5,  1.5],
       [ 0. ,  0. , -0.2]])

In [218]:
x

array([  6.,  15., -23.])

In [219]:
R@Q

array([[ 3.5       ,  0.59160798, -0.48304589],
       [ 1.60579308,  1.64285714, -1.69131435],
       [ 0.06900656, -0.05832118, -0.14285714]])

In [220]:
Q@R

array([[ 2.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  3.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00, -2.42598438e-17, -2.10832838e-16]])

In [221]:
Q

array([[-0.81649658,  0.27602622, -0.50709255],
       [-0.40824829, -0.89708523,  0.16903085],
       [-0.40824829,  0.34503278,  0.84515425]])

In [222]:
R

array([[-2.44948974, -2.04124145, -1.63299316],
       [ 0.        , -2.41522946, -1.51814423],
       [ 0.        ,  0.        , -0.16903085]])

In [223]:
# Program to show working of qr() when q is orthonormal
import numpy as np
# Declaring the first array
arr1 = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
arr1

array([[0, 1],
       [1, 1],
       [1, 1],
       [2, 1]])

In [224]:
b = np.array([1, 0, 2, 1])
# Calculating qr
(q, r) = np.linalg.qr(arr1)
q

array([[ 0.        ,  0.8660254 ],
       [-0.40824829,  0.28867513],
       [-0.40824829,  0.28867513],
       [-0.81649658, -0.28867513]])

In [225]:
r

array([[-2.44948974, -1.63299316],
       [ 0.        ,  1.15470054]])

In [226]:
# Validating
p = np.dot(q.T, b)
p

array([-1.63299316,  1.15470054])

In [227]:
np.dot(np.linalg.inv(r), p)

array([6.66133815e-16, 1.00000000e+00])

In [228]:
import numpy as np
m = np.matrix([[2, -1],
               [-1, 2],
               [0, -1]])

orthonormal, upper_triangle = np.linalg.qr(m, mode="raw")

In [229]:
orthonormal

array([[-2.23606798, -0.23606798,  0.        ],
       [ 1.78885438, -1.67332005, -0.33167927]])

In [230]:
upper_triangle

array([1.89442719, 1.80178373])

In [231]:
from sympy.matrices import Matrix, eye, zeros, ones, diag, GramSchmidt
from sympy.interactive.printing import init_printing

init_printing(use_unicode=False, wrap_line=False)

V = [Matrix([2,3,5]), Matrix([3,6,2]), Matrix([8,3,6])]
out1 = GramSchmidt(V)
out2 = GramSchmidt(V, True)
out1

      [ 23 ]  [ 1692 ] 
      [ -- ]  [ ---- ] 
      [ 19 ]  [ 353  ] 
 [2]  [    ]  [      ] 
 [ ]  [ 63 ]  [-1551 ] 
[[3], [ -- ], [------]]
 [ ]  [ 19 ]  [ 706  ] 
 [5]  [    ]  [      ] 
      [-47 ]  [-423  ] 
      [----]  [----- ] 
      [ 19 ]  [ 706  ] 

In [232]:
out2

 [   ____ ]  [      ______ ]  [      _____ ] 
 [ \/ 38  ]  [ 23*\/ 6707  ]  [ 12*\/ 706  ] 
 [ ------ ]  [ ----------- ]  [ ---------- ] 
 [   19   ]  [     6707    ]  [    353     ] 
 [        ]  [             ]  [            ] 
 [    ____]  [      ______ ]  [      _____ ] 
 [3*\/ 38 ]  [ 63*\/ 6707  ]  [-11*\/ 706  ] 
[[--------], [ ----------- ], [------------]]
 [   38   ]  [     6707    ]  [    706     ] 
 [        ]  [             ]  [            ] 
 [    ____]  [      ______ ]  [     _____  ] 
 [5*\/ 38 ]  [-47*\/ 6707  ]  [-3*\/ 706   ] 
 [--------]  [-------------]  [----------- ] 
 [   38   ]  [     6707    ]  [    706     ] 

In [233]:
from sympy.matrices import Matrix, GramSchmidt
V = [Matrix([2,3]), Matrix([3,6])]

In [234]:
Matrix.orthogonalize(*V, normalize=True)

 [    ____]  [     ____ ] 
 [2*\/ 13 ]  [-3*\/ 13  ] 
 [--------]  [----------] 
 [   13   ]  [    13    ] 
[[        ], [          ]]
 [    ____]  [     ____ ] 
 [3*\/ 13 ]  [ 2*\/ 13  ] 
 [--------]  [ -------- ] 
 [   13   ]  [    13    ] 

In [235]:
# Matrix.orthogonalize(L)

# QR using Gram-Schmidt from sympy
In the code below we construct the QR factorization of a matrix using the Gram-Schmidt function from sympy following the steps:


1.   orthogonolize the columns of the given matrix using Gram-Schmidt function. We use the sympy GramSchmidt function with the optional parameter True to get orthonormal set of vectors as an output. The vectors obtained as the result of orthogonalization will be the columns of the orthogonal matrix Q.
2.   Find the upper-triangular matrix R by the formula $R=Q^TV$.



In [236]:
# the original matrix given as a list of its columns
V = [Matrix([1,-2,2]), Matrix([5,0,-1]), Matrix([4,3,7])]
V

 [1 ]  [5 ]  [4] 
 [  ]  [  ]  [ ] 
[[-2], [0 ], [3]]
 [  ]  [  ]  [ ] 
 [2 ]  [-1]  [7] 

In [237]:
# apply GramSchmidt to V.
# The optional parameter True, which specifies that the output should be normalized
# the output is a list of orthonormal vectors
Q_vect = GramSchmidt(V, True)
Q_vect

         [ 14 ]  [2/15] 
 [1/3 ]  [ -- ]  [    ] 
 [    ]  [ 15 ]  [ 11 ] 
[[-2/3], [    ], [ -- ]]
 [    ]  [2/15]  [ 15 ] 
 [2/3 ]  [    ]  [    ] 
         [-1/3]  [2/3 ] 

In [238]:
# appends the separate vectors of Q_vect in a single matrix
Q_matrix = Matrix.hstack(*(Q_vect[i] for i in range(3)))
Q_matrix

[       14       ]
[1/3    --   2/15]
[       15       ]
[                ]
[             11 ]
[-2/3  2/15   -- ]
[             15 ]
[                ]
[2/3   -1/3  2/3 ]

In [239]:
V_matrix = Matrix.hstack(*(V[i] for i in [0,1,2]))
V_matrix

[1   5   4]
[         ]
[-2  0   3]
[         ]
[2   -1  7]

In [240]:
# compute R
R_matrix = Q_matrix.T * V_matrix
R_matrix

[3  1   4  ]
[          ]
[0  5  9/5 ]
[          ]
[0  0  37/5]

In [241]:
# compute QR factorization by the QRdecomposition method of sympy Matrixobject
# the result is the same as above
Q, R = V_matrix.QRdecomposition()
Q, R

 [       14       ]               
 [1/3    --   2/15]               
 [       15       ]  [3  1   4  ] 
 [                ]  [          ] 
([             11 ], [0  5  9/5 ])
 [-2/3  2/15   -- ]  [          ] 
 [             15 ]  [0  0  37/5] 
 [                ]               
 [2/3   -1/3  2/3 ]               