In [224]:
import pprint
import numpy as np
import scipy
import scipy.linalg   # SciPy Linear Algebra Library

In [225]:
x = np.array([[3], [4]])
x

array([[3],
       [4]])

In [226]:
# l_1 norm of vector x
np.linalg.norm(x, 1)

7.0

In [227]:
# l_2 norm of vector x
np.linalg.norm(x, 2)

5.0

In [228]:
# l_infty norm of vector x
np.linalg.norm(x, np.inf)

4.0

In [229]:
A = np.array([[2, -2], [-3, 5]])
A

array([[ 2, -2],
       [-3,  5]])

In [230]:
# inverse of A
Ainv = np.linalg.inv(A)
Ainv

array([[1.25, 0.5 ],
       [0.75, 0.5 ]])

In [231]:
# induced l_1 norm of matrix A
np.linalg.norm(A, 1)

7.0

In [232]:
# induced l_1 norm of the inverse of matrix A
np.linalg.norm(Ainv, 1)

2.0000000000000004

In [233]:
# condition number of A with respect to l_1 norm
condA1 = np.linalg.cond(A, 1)
condA1

14.000000000000004

In [234]:
# induced l_inf norm of matrix A
np.linalg.norm(A, np.inf)

8.0

In [235]:
# induced l_inf norm of the inverse of matrix A
np.linalg.norm(Ainv, np.inf)

1.7500000000000004

In [236]:
# condition number of A with respect to l_1 norm
condAinf = np.linalg.cond(A, np.inf)
condAinf

14.000000000000004

Note, that the condition numbers of $2 \times 2$ matrices with respect to $l_1$ and $l_\infty$ norms are always the same. This is not generally true for square matrices of higher order.

In [237]:
n=3
A = np.random.rand(n, n)
cond1 = np.linalg.cond(A, 1)
print('cond1 = ', cond1)
cond2 = np.linalg.cond(A, 2)
print('cond2 = ', cond2)
cond_infty = np.linalg.cond(A, np.inf)
print('cond_infty = ', cond_infty)

cond1 =  19.422587210995967
cond2 =  11.72633261612491
cond_infty =  18.011281233159895


In [238]:
B = np.array([[3, -1, 0], [2, 0, 1], [1, 2, 1]])
print(np.linalg.det(B))
print(np.linalg.norm(B, 1))
print(np.linalg.norm(B, np.inf))
print(np.linalg.norm(np.linalg.inv(B), 1))
print(np.linalg.norm(np.linalg.inv(B), np.inf))
cond1 = np.linalg.cond(B, 1)
print('cond1 = ', cond1)
cond2 = np.linalg.cond(B, 2)
print('cond2 = ', cond2)
cond_infty = np.linalg.cond(B, np.inf)
print('cond_infty = ', cond_infty)

-5.000000000000001
6.0
4.0
2.1999999999999997
2.5999999999999996
cond1 =  13.2
cond2 =  7.207240787668564
cond_infty =  10.399999999999999


#Cholesky 2 by 2 other numbers

In [239]:
A = np.array([[9, 3], [3, 17]])
L = scipy.linalg.cholesky(A, lower=True)
L

array([[3., 0.],
       [1., 4.]])

In [240]:
U = scipy.linalg.cholesky(A, lower=False)
U

array([[3., 1.],
       [0., 4.]])

In [241]:
U.T @ U

array([[ 9.,  3.],
       [ 3., 17.]])

In [242]:
L @ L.T

array([[ 9.,  3.],
       [ 3., 17.]])

In [243]:
U.T == L

array([[ True,  True],
       [ True,  True]])

In [244]:
E1 = np.array([[1/3, 0], [-1/3, 1]])
E1 @ A

array([[ 3.,  1.],
       [ 0., 16.]])

In [245]:
E1 @ A @ E1.T

array([[ 1.,  0.],
       [ 0., 16.]])

In [246]:
E2 = np.array([[1, 0], [0, 1/4]])
E2 @ E1 @ A @ E1.T

array([[1., 0.],
       [0., 4.]])

In [247]:
E2 @ E1 @ A @ E1.T @ E2.T

array([[1., 0.],
       [0., 1.]])

In [248]:
L = np.linalg.inv(E1) @ np.linalg.inv(E2)
L

array([[3., 0.],
       [1., 4.]])

In [249]:
L @ L.T

array([[ 9.,  3.],
       [ 3., 17.]])

#Matrix condition old draft

##1. Compute the norm of A

In [250]:
A = np.array([[1, 2], [-3, 4]])
np.linalg.norm(A, ord=1)

6.0

In [251]:
x = np.array([1, 2]).T
np.linalg.norm(x, ord=1)

3.0

In [252]:
y = A @ x
y

array([5, 5])

In [253]:
np.linalg.norm(y, ord=1)

10.0

In [254]:
np.linalg.norm(A, ord=1) * np.linalg.norm(x, ord=1) < np.linalg.norm(y, ord=1)

False

##2. Find a determinant of A = a11*a22 - a12*a21

In [255]:
np.linalg.det(A)

10.000000000000002

##3. Find an inverse A^{-1}


In [256]:
np.linalg.inv(A)

array([[ 0.4, -0.2],
       [ 0.3,  0.1]])

##4. Find a norm of the inverse

In [257]:
np.linalg.norm(np.linalg.inv(A), ord=1)

0.7000000000000001

##5. Find the relative condition number 

In [258]:
np.linalg.cond(A, p=1)

4.2

#Matrix condition clean

##Q2

In [259]:
x = np.array([1, 2])
np.linalg.norm(x, ord=1)

3.0

##Q4

In [260]:
A = np.array([[1, 2], [-3, 4]])
np.linalg.norm(A, ord=1)

6.0

##Q5

In [261]:
A @ x

array([5, 5])

##Q6

In [262]:
np.linalg.norm(A @ x, ord=1)

10.0

##Q8

In [263]:
np.linalg.det(A)

10.000000000000002

##Q9

In [264]:
np.linalg.inv(A)

array([[ 0.4, -0.2],
       [ 0.3,  0.1]])

##Q10

In [265]:
np.linalg.norm(np.linalg.inv(A), ord=1)

0.7000000000000001

##Q11

In [266]:
np.linalg.cond(A, p=1)

4.2

st 1

In [267]:
L = np.array([[4, 0],
              [2, 9]
])
U = np.array([[1, 0.5],
              [0, 1]
])
A = L @ U
A

array([[ 4.,  2.],
       [ 2., 10.]])

In [268]:
P, L1, U1 = scipy.linalg.lu(A)
P

array([[1., 0.],
       [0., 1.]])

In [269]:
 L1

array([[1. , 0. ],
       [0.5, 1. ]])

In [270]:
U1

array([[4., 2.],
       [0., 9.]])

In [271]:
L2 = scipy.linalg.cholesky(A, lower=True)
L2

array([[2., 0.],
       [1., 3.]])

In [272]:
L2 @ L2.T

array([[ 4.,  2.],
       [ 2., 10.]])

Python

In [273]:
import numpy as np
mat = np.array([[ 1, 2, 3],
               [6, 5, 4]])
mat_norm = np.linalg.norm(mat, axis = 1)
len(mat_norm)

2

In [274]:
import numpy as np
vector = np.arange(9)
matrix = vector.reshape((3, 3))
vec_norm = np.linalg.norm(vector)
mat_norm = np.linalg.norm(matrix)
vec_norm==mat_norm

True