In [ ]:
# https://www.askpython.com/python/examples/singular-value-decomposition

Using numpy

In [ ]:
import numpy as np
 
#Creating a matrix A
A = np.array([[3,4,3],[1,2,3],[4,2,1]])
# A = np.array([[3,4],[1,2],[4,2]])
 
#Performing SVD
U, D, VT = np.linalg.svd(A)
print("A: \n", A)
print("U: \n", U)
print("np.diag(D): \n", np.diag(D))
print("VT: \n", VT) 
#Checking if we can remake the original matrix using U,D,VT
A_remake = (U @ np.diag(D) @ VT)
# A_remake = (U @ np.diag(D) @ VT.T)
print("A_remake: \n", A_remake)



A: 
 [[3 4 3]
 [1 2 3]
 [4 2 1]]
U: 
 [[-0.73553325 -0.18392937 -0.65204358]
 [-0.42657919 -0.62196982  0.65664582]
 [-0.52632788  0.76113306  0.37901904]]
np.diag(D): 
 [[7.87764972 0.         0.        ]
 [0.         2.54031671 0.        ]
 [0.         0.         0.69958986]]
VT: 
 [[-0.60151068 -0.61540527 -0.5093734 ]
 [ 0.73643349 -0.18005275 -0.65210944]
 [ 0.30959751 -0.76737042  0.5615087 ]]
A_remake: 
 [[3. 4. 3.]
 [1. 2. 3.]
 [4. 2. 1.]]


scipy

In [ ]:
from numpy import array
from scipy.linalg import svd
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# SVD
U, s, VT = svd(A)
print(U)
print("-------------------")
print(s)
print("-------------------")
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
-------------------
[9.52551809 0.51430058]
-------------------
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [ ]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
# define a matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create n x n Sigma matrix
Sigma = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
