In [18]:
import numpy as np
A = np.array([[1,2],
              [2,3]             
              ])
AtA = A.T @ A
valAtA, vecAtA = np.linalg.eig(AtA)



Which of the following vectors s1, s2, s3 and s4 contain singular values of matrix A?

In [19]:
U, s1, VH = np.linalg.svd(A)

In [20]:
s2 = valAtA

In [21]:
s3 = np.sqrt(valAtA)

In [22]:
s4 = vecAtA

In [23]:
s1 == s3

array([False, False])

In [24]:
s1, s3

(array([4.23606798, 0.23606798]), array([0.23606798, 4.23606798]))

In [25]:
U, S, VH = np.linalg.svd(A)
print(valAtA)
ascRootValAtA = np.sort(np.sqrt(valAtA))
descRootValAtA1 = ascRootValAtA[::-1]
descRootValAtA1
descRootValAtA2 = np.sort(ascRootValAtA)[::-1]
descRootValAtA2 = -np.sort(-ascRootValAtA)
descRootValAtA2
descRootValAtA1 == descRootValAtA2
descRootValAtA1 == S
np.isclose(descRootValAtA1, S)
np.isclose(descRootValAtA2, S)
np.isclose(descRootValAtA1, descRootValAtA2)

[ 0.05572809 17.94427191]


array([ True,  True])

In [26]:
import numpy as np
A = np.array([[1,2, 3],
              [4, 5, 6]              
              ])
AtA = A.T @ A

valAtA, vecAtA = np.linalg.eig(AtA)
U, S, VH = np.linalg.svd(A)
np.sqrt(valAtA) 

array([9.50803200e+00, 7.72869636e-01, 2.68942198e-08])

In [27]:
ascRootValAtA = np.sort(np.sqrt(valAtA))
ascRootValAtA

array([2.68942198e-08, 7.72869636e-01, 9.50803200e+00])

In [28]:
ascRootValAtA[::-1]

array([9.50803200e+00, 7.72869636e-01, 2.68942198e-08])

In [29]:
np.sort(ascRootValAtA)[::-1]

array([9.50803200e+00, 7.72869636e-01, 2.68942198e-08])

In [30]:
-np.sort(-ascRootValAtA)

array([9.50803200e+00, 7.72869636e-01, 2.68942198e-08])