In [36]:
# https://www.askpython.com/python/examples/singular-value-decomposition

Using numpy

In [37]:
import numpy as np
 
#Creating a matrix A
A = np.array([[3,4,3],[1,2,3],[4,2,1]])
# A = np.array([[3,4],[1,2],[4,2]])
 
#Performing SVD
U, D, VT = np.linalg.svd(A)
print("A: \n", A)
print("U: \n", U)
print("np.diag(D): \n", np.diag(D))
print("VT: \n", VT) 
#Checking if we can remake the original matrix using U,D,VT
A_remake = (U @ np.diag(D) @ VT)
# A_remake = (U @ np.diag(D) @ VT.T)
print("A_remake: \n", A_remake)



A: 
 [[3 4 3]
 [1 2 3]
 [4 2 1]]
U: 
 [[-0.73553325 -0.18392937 -0.65204358]
 [-0.42657919 -0.62196982  0.65664582]
 [-0.52632788  0.76113306  0.37901904]]
np.diag(D): 
 [[7.87764972 0.         0.        ]
 [0.         2.54031671 0.        ]
 [0.         0.         0.69958986]]
VT: 
 [[-0.60151068 -0.61540527 -0.5093734 ]
 [ 0.73643349 -0.18005275 -0.65210944]
 [ 0.30959751 -0.76737042  0.5615087 ]]
A_remake: 
 [[3. 4. 3.]
 [1. 2. 3.]
 [4. 2. 1.]]


Using scikit-learn

In [38]:
#Importing required modules
import numpy as np
from sklearn.decomposition import TruncatedSVD
 
#Creating array 
A = np.array([[3,4,3],[1,2,3],[4,2,1]])
 
#Fitting the SVD class
trun_svd =  TruncatedSVD(n_components = 2)
A_transformed = trun_svd.fit_transform(A)
 
#Printing the transformed matrix
print("Transformed Matrix:")
print(A_transformed)

Transformed Matrix:
[[ 5.7942733  -0.46723885]
 [ 3.3604414  -1.58000033]
 [ 4.14622666  1.93351902]]


In [39]:

from numpy import array
from scipy.linalg import svd
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# SVD
U, s, VT = svd(A)
print(U)
print("-------------------")
print(s)
print("-------------------")
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
-------------------
[9.52551809 0.51430058]
-------------------
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [40]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from scipy.linalg import svd
# define a matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create n x n Sigma matrix
Sigma = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [41]:
from numpy import array
from numpy.linalg import pinv
A = array([
	[0.1, 0.2],
	[0.3, 0.4],
	[0.5, 0.6],
	[0.7, 0.8]])
B = pinv(A)
print(B)

[[-1.0000000e+01 -5.0000000e+00  8.4040814e-15  5.0000000e+00]
 [ 8.5000000e+00  4.5000000e+00  5.0000000e-01 -3.5000000e+00]]


In [42]:

from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define a matrix
A = array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
VT = VT[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(VT))
print(B)
# transform
T = U.dot(Sigma)
print(T)
T = A.dot(VT.T)
print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [43]:
from numpy import array
from sklearn.decomposition import TruncatedSVD
# define array
A = array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])

svdObject = TruncatedSVD(n_components=3)
svdObject.fit(A)
result = svdObject.transform(A)
print(result)

[[ 1.85215775e+01  6.47697214e+00 -1.33226763e-15]
 [ 4.98131001e+01  1.91182038e+00 -8.88178420e-16]
 [ 8.11046228e+01 -2.65333138e+00  2.22044605e-15]]


In [44]:
dir(svdObject)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 'algorithm',
 'components_',
 'explained_variance_',
 'explained_variance_ratio_',
 'fit',
 'fit_transform',
 'get_params',
 'inverse_transform',
 'n_components',
 'n_iter',
 'random_state',
 'set_params',
 'singular_values_',
 'tol',
 'transform']

In [45]:
svdObject.singular_values_

array([9.69657342e+01, 7.25578339e+00, 2.17558393e-15])

In [47]:
svdObject.get_params()

{'algorithm': 'randomized',
 'n_components': 3,
 'n_iter': 5,
 'random_state': None,
 'tol': 0.0}

In [48]:
svdObject.components_

array([[ 0.24139304,  0.25728686,  0.27318068,  0.2890745 ,  0.30496832,
         0.32086214,  0.33675595,  0.35264977,  0.36854359,  0.38443741],
       [-0.53589546, -0.42695236, -0.31800926, -0.20906617, -0.10012307,
         0.00882003,  0.11776313,  0.22670623,  0.33564933,  0.44459242],
       [ 0.5823854 , -0.23754427, -0.29605719,  0.17429623,  0.0207045 ,
        -0.37938407, -0.17093355, -0.16276173, -0.06215358,  0.53144826]])

In [46]:

# Pseudoinverse via SVD
from numpy import array
from numpy.linalg import svd
from numpy import zeros
from numpy import diag
# define matrix
A = array([
	[0.1, 0.2],
	[0.3, 0.4],
	[0.5, 0.6],
	[0.7, 0.8]])
print(A)
# calculate svd
U, s, VT = svd(A)
# reciprocals of s
d = 1.0 / s
# create m x n D matrix
D = zeros(A.shape)
# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = diag(d)
# calculate pseudoinverse
B = VT.T.dot(D.T).dot(U.T)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  8.39790527e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]
