In [ ]:
# https://www.askpython.com/python/examples/singular-value-decomposition

Using numpy

In [ ]:
import numpy as np
 
#Creating a matrix A
A = np.array([[3,4,3],[1,2,3],[4,2,1]])
# A = np.array([[3,4],[1,2],[4,2]])
 
#Performing SVD
U, D, VT = np.linalg.svd(A)
print("A: \n", A)
print("U: \n", U)
print("np.diag(D): \n", np.diag(D))
print("VT: \n", VT) 
#Checking if we can remake the original matrix using U,D,VT
A_remake = (U @ np.diag(D) @ VT)
# A_remake = (U @ np.diag(D) @ VT.T)
print("A_remake: \n", A_remake)



A: 
 [[3 4 3]
 [1 2 3]
 [4 2 1]]
U: 
 [[-0.73553325 -0.18392937 -0.65204358]
 [-0.42657919 -0.62196982  0.65664582]
 [-0.52632788  0.76113306  0.37901904]]
np.diag(D): 
 [[7.87764972 0.         0.        ]
 [0.         2.54031671 0.        ]
 [0.         0.         0.69958986]]
VT: 
 [[-0.60151068 -0.61540527 -0.5093734 ]
 [ 0.73643349 -0.18005275 -0.65210944]
 [ 0.30959751 -0.76737042  0.5615087 ]]
A_remake: 
 [[3. 4. 3.]
 [1. 2. 3.]
 [4. 2. 1.]]


Using scikit-learn

In [ ]:
#Importing required modules
import numpy as np
from sklearn.decomposition import TruncatedSVD
 
#Creating array 
A = np.array([[3,4,3],[1,2,3],[4,2,1]])
 
#Fitting the SVD class
trun_svd =  TruncatedSVD(n_components = 2)
A_transformed = trun_svd.fit_transform(A)
 
#Printing the transformed matrix
print("Transformed Matrix:")
print(A_transformed)

Transformed Matrix:
[[ 5.7942733  -0.46723885]
 [ 3.3604414  -1.58000033]
 [ 4.14622666  1.93351902]]
