Using NumPy, a developer can perform the following operations −

    Mathematical and logical operations on arrays.
    Fourier transforms and routines for shape manipulation.
    Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.


In [2]:
# Show version
import numpy as np
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [3]:
# Create a null vector of size 10 
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# memory size of any array
Z = np.zeros((100,100))
print("{} bytes".format(Z.size * Z.itemsize))

80000 bytes


In [5]:
# create vector contains 10 elements with value 2.5
Z = np.full(shape=10, fill_value=2.5)
print(Z)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [6]:
# Create a vector with values ranging 
Z = np.arange(10,50)
print(Z)
# step 2
Z1 = np.arange(10,50, 2)
print(Z1)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [7]:
# Reverse a vector (first element becomes last)
Z = np.arange(50)
Z = Z[::-1]
print(Z)
print(type(Z))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]
<class 'numpy.ndarray'>


In [8]:
# Create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# Find indices of non-zero elements
x = np.array([1,2,0,0,4,0])
nz = np.nonzero(x)
print(nz)
print("Len of non zero is {}".format(len(nz[0])))
type(nz)

(array([0, 1, 4]),)
Len of non zero is 3


tuple

In [10]:
# Create a 3x3 identity matrix
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Create a 4x4 identity matrix
Z = np.eye(4,k=1)
print(Z)
print("----------------------")
Z = np.eye(4,k=-1)
print(Z)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
----------------------
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [12]:
# Create a 10x10 array with random values and find the minimum and maximum values
# Uniform [0,1) 
Z = np.random.random(size=(5,5))
Zmin, Zmax = Z.min(), Z.max()
print(Z)
print("Zmin = {}, Zmax = {}".format(Zmin, Zmax))

[[0.75819148 0.33281046 0.63176964 0.28826001 0.24766122]
 [0.06454209 0.89702296 0.363804   0.02294613 0.40834077]
 [0.2303753  0.77416865 0.22676925 0.53480222 0.81501834]
 [0.86838668 0.54048241 0.05662753 0.69240231 0.36954916]
 [0.22068105 0.14588007 0.81162441 0.72867473 0.70674633]]
Zmin = 0.02294612940776064, Zmax = 0.8970229581005962


In [13]:
# Create a random vector of size 30 and find the mean value 
Z = np.random.random(30)
m = Z.mean()
print(Z)
print("mean = {}".format(m))

[0.61744616 0.6197288  0.40619126 0.37574628 0.98658023 0.26993315
 0.15652205 0.8822889  0.51824239 0.27515165 0.78607094 0.76940087
 0.98654521 0.01440466 0.26293656 0.20685379 0.55215088 0.19648428
 0.43392264 0.70252271 0.91741239 0.76345287 0.44320481 0.36679214
 0.84077003 0.94343187 0.13235865 0.58445564 0.85818613 0.505191  ]
mean = 0.5458126318229082


In [14]:
# Create a 2d array with 1 on the border and 0 inside
Z = np.ones((10,10))
Z[2:-2,2:-2] = 0
print(Z)
print("----------------------")
Z = np.zeros((10,10))
Z[1:-1, 1:-1] = 1
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
----------------------
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
# interesting examples of some operations
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.inf < np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
3 * 0.1


nan
False
False
False
nan
True
False


0.30000000000000004

In [16]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [17]:
# Normalize a 5x5 random matrix
Z = np.random.random((5,5))
print(Z)
print("-------------------------")
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)


[[0.82193756 0.92226367 0.16378052 0.98754243 0.26236352]
 [0.77855727 0.39799633 0.77192936 0.53502964 0.79882944]
 [0.60787583 0.10559867 0.09334288 0.84912256 0.67891406]
 [0.42692353 0.47890533 0.00781324 0.83872752 0.81856143]
 [0.25021949 0.16944908 0.67276147 0.94144081 0.99981194]]
-------------------------
[[ 0.79684731  1.12083799 -1.32858892  1.33164761 -1.01022741]
 [ 0.65675605 -0.57221812  0.63535204 -0.1296861   0.7222225 ]
 [ 0.10556159 -1.51647997 -1.5560585   0.88463786  0.3349707 ]
 [-0.47880134 -0.31093259 -1.83226584  0.85106837  0.78594451]
 [-1.04944502 -1.31028303  0.31510169  1.18276818  1.37127045]]


In [18]:
#  Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
a = np.ones((5,3))
b = np.ones((3,2))
Z = np.dot(a, b)
print(a)
print(b)
print("Product")
print(Z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Product
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [19]:
# Given a 1D array, negate all elements located between 3 and 8
Z = np.arange(11)
print("Original\n",Z)
Z[(3 < Z) & (Z <= 8)] *= -1
# Break it down
trueFalseCollection = (3 < Z) & (Z <= 8)
print("trueFalseCollection =", trueFalseCollection)
print("type(trueFalseCollection) =", type(trueFalseCollection))

print(Z)
print("Negate at selected indexes")
newTrueFalseArray = np.array([False, False, True, True, True, True, True, True, True, True, True])
mySubset = Z[(newTrueFalseArray)] 
print("mySubset =", mySubset)

Original
 [ 0  1  2  3  4  5  6  7  8  9 10]
trueFalseCollection = [False False False False False False False False False False False]
type(trueFalseCollection) = <class 'numpy.ndarray'>
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]
Negate at selected indexes
mySubset = [ 2  3 -4 -5 -6 -7 -8  9 10]


In [20]:
# Given a 1D array, negate all elements located between 3 and 8
Z = np.arange(11)
print("Original\n",Z)
# Z[(3 < Z) & (Z <= 8)] *= -1
Z[[1,2,3]]*= -1
print(Z)

Original
 [ 0  1  2  3  4  5  6  7  8  9 10]
[ 0 -1 -2 -3  4  5  6  7  8  9 10]


In [21]:
# compare two array
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
equal = np.allclose(A,B)
print("-----------")
print(equal)

[1 1 0 0 0]
[1 1 1 1 0]
-----------
False


In [22]:
# create constant (immutable) array
# print("abc".flags) # only numpy?
Z = np.zeros(10)
Z.flags.writeable = False
print("Z.flags:\n", Z.flags)
print(dir(Z.flags))
Z[0] = 1



Z.flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

['__class__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', '_warn_on_write', '_writeable_no_warn', 'aligned', 'behaved', 'c_contiguous', 'carray', 'contiguous', 'f_contiguous', 'farray', 'fnc', 'forc', 'fortran', 'num', 'owndata', 'updateifcopy', 'writeable', 'writebackifcopy']


ValueError: ignored

In [23]:
# get all the dates corresponding to the month of September 2020
Z = np.arange('2020-09', '2020-10', dtype='datetime64[W]')
print(Z)

['2020-08-27' '2020-09-03' '2020-09-10' '2020-09-17' '2020-09-24']


In [24]:
# Extract the integer part of a random array using 5 different methods
Z = np.random.uniform(0,10,10)
print(Z)
print("---------")
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[0.59801229 3.811392   6.36226628 8.93360645 2.45432913 3.75016849
 9.22871512 1.77556581 8.04371132 6.42717206]
---------
[0. 3. 6. 8. 2. 3. 9. 1. 8. 6.]
[0. 3. 6. 8. 2. 3. 9. 1. 8. 6.]
[0. 3. 6. 8. 2. 3. 9. 1. 8. 6.]
[0 3 6 8 2 3 9 1 8 6]
[0. 3. 6. 8. 2. 3. 9. 1. 8. 6.]


In [25]:
# Create a 5x5 matrix with row values ranging from 0 to 4 
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [26]:
# transform int array to float
Z = np.arange(10, dtype=np.int32)
print(Z)
Z = Z.astype(np.float32, copy=False)
print(Z)


[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Several routines are available in NumPy package for manipulation of elements in ndarray object. They can be classified into the following types

**Changing Shape**

In [27]:
# This function returns a copy of an array collapsed into one dimension. The function takes the following parameters.
a = np.arange(8).reshape(2,4) 
print(a)
print("----------------")
print(a.flatten())
print("----------------")
"""
 	

order
'C'− row major default. 
'F': column major 
'A': flatten in column-major order, if a is Fortran contiguous in memory, row-major order otherwise 
'K': flatten a in the order the elements occur in the memory
"""
print( a.flatten(order = 'F'))

[[0 1 2 3]
 [4 5 6 7]]
----------------
[0 1 2 3 4 5 6 7]
----------------
[0 4 1 5 2 6 3 7]


In [28]:
a = np.arange(8).reshape(2,4) 
print(a)
print("----------------")
print(a.ravel())
("----------------")
print(a.ravel(order = 'F'))

[[0 1 2 3]
 [4 5 6 7]]
----------------
[0 1 2 3 4 5 6 7]
[0 4 1 5 2 6 3 7]


**Transpose Operations**

In [29]:
# This function permutes the dimension of the given array. It returns a view wherever possible. The function takes the following parameters.
a = np.arange(12).reshape(3,4)
print(a)
print("----------------")
print(np.transpose(a))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


**Joining Arrays**

In [30]:
# Concatenation refers to joining. This function is used to join two or more arrays of the same shape 
# along a specified axis. The function takes the following parameters
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
print(a)
print("------------------")
print(b)
print("------------------")
print(np.concatenate((a,b)))
print("------------------")
print(np.concatenate((a,b),axis = 1))

[[1 2]
 [3 4]]
------------------
[[5 6]
 [7 8]]
------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
------------------
[[1 2 5 6]
 [3 4 7 8]]


In [31]:
# This function joins the sequence of arrays along a new axis. 
# Another level of brackets comparing to the above cell. 
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
print(a)
print("------------------")
print(b)
print("------------------")
print(np.stack((a,b),0))
print("------------------")
print(np.stack((a,b),1))

[[1 2]
 [3 4]]
------------------
[[5 6]
 [7 8]]
------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
------------------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


**Statistical Functions**

In [32]:
# Percentile (or a centile) is a measure used in statistics 
# indicating the value below which a given percentage of observations 
# in a group of observations fall. 
# The function numpy.percentile() takes the following arguments.
"""
numpy.percentile(a, q, axis)
a - Input array
q - The percentile to compute must be between 0-100
axis - The axis along which the percentile is to be calculat
"""
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 
# 10 20 30 40 50 60 70 80 90
print("np.percentile(a,50) =", np.percentile(a,50))
b = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print("np.percentile(b,55) =", np.percentile(b,55))


np.percentile(a,50) = 50.0
np.percentile(b,55) = 54.0


In [33]:
# Median is defined as the value separating the higher half of a data sample from the lower half. The numpy.median() function is used as shown in the following program.
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 
print(a)
print("----------------")
print(np.median(a))
print("----------------")
print(np.median(a, axis = 1))


[[30 65 70]
 [80 95 10]
 [50 90 60]]
----------------
65.0
----------------
[65. 80. 60.]


In [34]:
# Weighted average is an average resulting from the multiplication of each component by a factor reflecting its importance. The numpy.average() function computes the weighted average of elements in an array according to their respective weight given in another array. 
a = np.array([1,2,3,4]) 
print(np.average(a))
myWeights = [1, 2, 3, 2]
print(np.average(a, weights=myWeights))
mySum = sum(myWeights)
myNormedWeights = np.array(myWeights) / mySum
print(np.average(a, weights=myNormedWeights))


2.5
2.75
2.75


In [35]:
# Standard deviation is the square root of the average of squared deviations from mean.
print(np.std([1,2,3,4]))
print((np.std([1,2,3,4])) ** 2)



1.118033988749895
1.2500000000000002


In [36]:
# Variance is the average of squared deviations, i.e., mean(abs(x - x.mean())**2). In other words, the standard deviation is the square root of variance.
print(np.var([1,2,3,4]))

1.25
