In [83]:
import numpy as np

https://numpy.org/doc/stable/reference/generated/numpy.fill_diagonal.html

In [84]:
a = np.zeros((3, 5), int)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [85]:
np.fill_diagonal(a, 4, wrap=True)
a

array([[4, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 4, 0, 0]])

In [86]:
a = np.zeros((7, 3), int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [87]:
np.fill_diagonal(a, 1, wrap=True)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [88]:
np.fill_diagonal(a, 1)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [89]:
np.fill_diagonal(a, [1, 2, 3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [90]:
np.fill_diagonal(a, [6, 2, 3, 4, 5, 6])
a

array([[6, 0, 0],
       [0, 2, 0],
       [0, 0, 3],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

SVD sklearn

https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html

In [91]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import csr_matrix
import numpy as np

In [92]:
np.random.seed(0)
X_dense = np.random.rand(100, 100)
X_dense[:, 2 * np.arange(50)] = 0

In [93]:
X = csr_matrix(X_dense)
X

<100x100 sparse matrix of type '<class 'numpy.float64'>'
	with 5000 stored elements in Compressed Sparse Row format>

In [94]:
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)

In [95]:
# Fit model on training data X.
svd.fit(X)
print(X.shape)
# Perform dimensionality reduction on X.
print(len(svd.transform(X)))

# Fit model to X and perform dimensionality reduction on X.
# svd.fit_transform(X)

(100, 100)
100


In [96]:
# Percentage of variance explained by each of the selected components.
print(svd.explained_variance_ratio_)

[0.01570766 0.05122679 0.04998062 0.04795064 0.04539933]


In [97]:
print(svd.explained_variance_ratio_.sum())

0.21026503465070334


In [98]:
# The singular values corresponding to each of the selected components. 
# The singular values are equal to the 2-norms of the n_components variables in the lower-dimensional space.
print(svd.singular_values_)

[35.24105443  4.5981613   4.54200434  4.44866153  4.32887456]
