In [ ]:
import numpy as np
from sklearn.decomposition import PCA
from numpy.linalg import svd



In [ ]:
X = np.array([
              [1, 2, 3], 
              [5, 2, -4], 
])
x_row_means = X.mean(axis=1).reshape([2, 1])
x_row_means

array([[2.],
       [1.]])

In [ ]:
X_centered = X - x_row_means
X_centered

array([[-1.,  0.,  1.],
       [ 4.,  1., -5.]])

In [ ]:
U, s, VT = svd(X)
U

array([[-0.09544671,  0.99543454],
       [ 0.99543454,  0.09544671]])

In [ ]:
Z_by_svd = U.T @ X
Z_by_svd

array([[ 4.88172599,  1.79997566, -4.2680783 ],
       [ 1.4726681 ,  2.1817625 ,  2.60451678]])

In [ ]:
U_centered, s_centered, VT_centered = svd(X_centered)
U_centered

array([[-0.2098553 ,  0.97773245],
       [ 0.97773245,  0.2098553 ]])

In [ ]:
Z_centered_by_svd = U_centered.T @ X_centered
Z_centered_by_svd

array([[ 4.12078512,  0.97773245, -5.09851757],
       [-0.13831125,  0.2098553 , -0.07154405]])

In [ ]:
pca = PCA()
Z_by_pca_T = pca.fit_transform(X.T)
Z_by_pca = Z_by_pca_T.T
Z_by_pca

array([[-4.12078512, -0.97773245,  5.09851757],
       [-0.13831125,  0.2098553 , -0.07154405]])

Centred

In [ ]:
import numpy as np
from sklearn.decomposition import PCA
from numpy.linalg import svd

X = np.array([
              [-1, -4, -1, -2], 
              [1, 0, -1, 4], 
])
x_row_means = X.mean(axis=1).reshape([2, 1])
X_centered = X - x_row_means
U_centered, s_centered, VT_centered = svd(X_centered)
Z_centered_by_svd = U_centered.T @ X_centered
Z_centered_by_svd
print(Z_centered_by_svd)
pca = PCA()
Z_by_pca_T = pca.fit_transform(X.T)
Z_by_pca = Z_by_pca_T.T
print(Z_by_pca)

[[ 0. -1. -2.  3.]
 [ 1. -2.  1.  0.]]
[[ 4.3874759e-16 -1.0000000e+00 -2.0000000e+00  3.0000000e+00]
 [-1.0000000e+00  2.0000000e+00 -1.0000000e+00  0.0000000e+00]]


In [ ]:
pca = PCA()
Z_by_pca_T = pca.fit_transform(X.T)
Z_by_pca = Z_by_pca_T.T
Z_by_pca

array([[ 4.3874759e-16, -1.0000000e+00, -2.0000000e+00,  3.0000000e+00],
       [-1.0000000e+00,  2.0000000e+00, -1.0000000e+00,  0.0000000e+00]])

Noncentred


In [ ]:
import numpy as np
from sklearn.decomposition import PCA
from numpy.linalg import svd
X = np.array([
              [-1, -4, -1, -2], 
              [1, 0, -1, 4], 
])
U, s, VT = svd(X)
Z_by_svd = U.T @ X
print(Z_by_svd)
pca = PCA()
Z_by_pca_T = pca.fit_transform(X.T)
Z_by_pca = Z_by_pca_T.T
print(Z_by_pca)

[[ 1.40361765  3.15282175  0.17279323  4.03805971]
 [ 0.17279323 -2.46164884 -1.40361765  1.92199733]]
[[ 4.3874759e-16 -1.0000000e+00 -2.0000000e+00  3.0000000e+00]
 [-1.0000000e+00  2.0000000e+00 -1.0000000e+00  0.0000000e+00]]
