In [ ]:
import numpy as np

In [ ]:
# Construct an array from an index array and a set of arrays to choose from.
a = [[1, 0, 1], [0, 1, 2], [1, 0, 1]]
choices = [-10, 10, 5]
np.choose(a, choices)

array([[ 10, -10,  10],
       [-10,  10,   5],
       [ 10, -10,  10]])

In [ ]:
choices = [[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23], [30, 31, 32, 33]]
np.choose([2, 3, 1, 0], choices)

array([20, 31, 12,  3])

In [ ]:
# Return the indices of the elements that are non-zero.
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
np.nonzero(x)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [ ]:
x[np.nonzero(x)]

array([3, 4, 5, 6])

In [ ]:
a = np.array([[1, 0, 2], [3, 0, 0], [4, 0, 5]])
a

array([[1, 0, 2],
       [3, 0, 0],
       [4, 0, 5]])

In [ ]:
np.nonzero(a)
"""
Каждый массив в этом кортеже, содержит индексы ненулевых элементов для соответствующего измерения, для примера выше, 
как нетрудно догадаться, первый массив - это индексы строк, второй - столбцов.
"""

'\nКаждый массив в этом кортеже, содержит индексы ненулевых элементов для соответствующего измерения, для примера выше, \nкак нетрудно догадаться, первый массив - это индексы строк, второй - столбцов.\n'

np.dot и np.inner идентичны для 1-мерных массивов, так что, вероятно, именно поэтому вы не замечаете никаких различий. Для n-мерных массивов они соответствуют общим тензорным операциям.

np.inner иногда называют "vector product" между тензором высшего и низшего порядка, особенно тензором, умноженным на вектор, и часто приводит к "tensor contraction". Она включает в себя умножение матрицы на вектор.

np.dot соответствует "тензорному произведению" и включает случай, упомянутый в нижней части страницы Википедии. Он обычно используется для умножения двух одинаковых тензоров, чтобы получить новый тензор. Она включает в себя матрицу-матричное умножение. 

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])

In [ ]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [ ]:
np.dot(a.T, b)

array([[50, 54],
       [74, 80]])

In [ ]:
np.dot(a, b.T)

array([[35, 41],
       [81, 95]])

In [ ]:
np.inner(a,b)

array([[35, 41],
       [81, 95]])

In [ ]:
np.outer(a, b)

array([[11, 12, 13, 14],
       [22, 24, 26, 28],
       [33, 36, 39, 42],
       [44, 48, 52, 56]])

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.inner(v1, v2)

32

In [ ]:
np.outer(v1, v2)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [ ]:
np.dot(v1, v2)

32

In [ ]:
v1 @ v2

32

In [ ]:
np.multiply(v1, v2)

array([ 4, 10, 18])

In [ ]:
np.multiply(a, b)

array([[11, 24],
       [39, 56]])

In [ ]:
# numpy.outer() function compute the outer product of two vectors.
a = np.ones(4) 
b = np.linspace(-1, 2, 4) 
print(a) 
print(b)
np.outer(a, b) 

[1. 1. 1. 1.]
[-1.  0.  1.  2.]


array([[-1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.]])

In [ ]:
# Функция einsum() применяет правила суммирования Эйнштейна к указанным массивам. 
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.einsum('ii', a)

30

In [ ]:
np.einsum('ii->i', a)
# https://pyprog.pro/linear_algebra_functions/einsum.html

array([ 0,  5, 10, 15])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
b

array([-1.,  0.,  1.,  2.])

In [ ]:
np.einsum('ij,j', a, b)


array([ 8., 16., 24., 32.])

In [ ]:
np.einsum('ij,i', a, b)

array([32., 34., 36., 38.])

In [ ]:
np.dot(a, b)

array([ 8., 16., 24., 32.])

In [ ]:
np.dot(b, a)

In [ ]:
np.einsum('ji', a)

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [ ]:
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [2]:
0.3
1/3

0.3333333333333333

In [4]:
import sympy
y = sympy.Symbol("x")
y

x

In [5]:
sympy.N(0.3, 50)

0.29999999999999998889776975374843459576368331909180