In [1]:
import numpy as np
import pprint
import scipy
import scipy.linalg   # SciPy Linear Algebra Library. 
from sympy.matrices import Matrix
from sympy import init_printing
init_printing()

#Scipy

In [2]:
A = np.array([[12, -51, 4], 
              [6, 167, -68], 
              [-4, 24, -41]])  # From the Wikipedia Article on QR Decomposition
type(A)                 

numpy.ndarray

In [3]:
Q, R = scipy.linalg.qr(A)

print("A:")
pprint.pprint(A)

print("Q:")
pprint.pprint(Q)

print("R:")
pprint.pprint(R)

print("Q @ R:")
pprint.pprint(Q @ R)

A:
array([[ 12, -51,   4],
       [  6, 167, -68],
       [ -4,  24, -41]])
Q:
array([[-0.85714286,  0.39428571,  0.33142857],
       [-0.42857143, -0.90285714, -0.03428571],
       [ 0.28571429, -0.17142857,  0.94285714]])
R:
array([[ -14.,  -21.,   14.],
       [   0., -175.,   70.],
       [   0.,    0.,  -35.]])
Q @ R:
array([[ 12., -51.,   4.],
       [  6., 167., -68.],
       [ -4.,  24., -41.]])


##RQ

In [4]:
from scipy import linalg

r, q = linalg.rq(A)
np.allclose(A, r @ q)



True

In [5]:
r, q, A, r@q

(array([[  16.16949328,   39.90406135,  -30.11998297],
        [   0.        , -111.23411418,  142.04214812],
        [   0.        ,    0.        ,   47.67598976]]),
 array([[ 0.98336918, -0.09767694, -0.1531152 ],
        [-0.16107729, -0.85851594, -0.48683106],
        [-0.08389967,  0.50339804, -0.85997166]]),
 array([[ 12, -51,   4],
        [  6, 167, -68],
        [ -4,  24, -41]]),
 array([[ 12., -51.,   4.],
        [  6., 167., -68.],
        [ -4.,  24., -41.]]))

In [6]:
r.shape, q.shape


In [7]:
r2 = linalg.rq(A, mode='r')
np.allclose(r, r2)


True

In [8]:
r3, q3 = linalg.rq(A, mode='economic')
r3.shape, q3.shape


-------------------------------

#RQ from scipy QR

In [9]:
import numpy as np
from scipy.linalg import qr
 
def custom_rq(A):
    '''Implement rq decomposition using QR decomposition
 
    From Wikipedia,
     The RQ decomposition transforms a matrix A into the product of an upper triangular matrix R (also known as right-triangular) and an orthogonal matrix Q. The only difference from QR decomposition is the order of these matrices.
     QR decomposition is Gram-Schmidt orthogonalization of columns of A, started from the first column.
     RQ decomposition is Gram-Schmidt orthogonalization of rows of A, started from the last row.
    '''
    Q,R = qr(np.flipud(A).T)
    R = np.flipud(R.T)
    Q = Q.T

    return R[:,::-1],Q[::-1,:]



In [10]:
R, Q = custom_rq(A)
A, R, Q, R @ Q

(array([[ 12, -51,   4],
        [  6, 167, -68],
        [ -4,  24, -41]]),
 array([[ -16.16949328,   39.90406135,  -30.11998297],
        [   0.        , -111.23411418,  142.04214812],
        [   0.        ,    0.        ,   47.67598976]]),
 array([[-0.98336918,  0.09767694,  0.1531152 ],
        [-0.16107729, -0.85851594, -0.48683106],
        [-0.08389967,  0.50339804, -0.85997166]]),
 array([[ 12., -51.,   4.],
        [  6., 167., -68.],
        [ -4.,  24., -41.]]))

In [11]:
R, Q = linalg.rq(A)
R, Q, R @ Q

(array([[  16.16949328,   39.90406135,  -30.11998297],
        [   0.        , -111.23411418,  142.04214812],
        [   0.        ,    0.        ,   47.67598976]]),
 array([[ 0.98336918, -0.09767694, -0.1531152 ],
        [-0.16107729, -0.85851594, -0.48683106],
        [-0.08389967,  0.50339804, -0.85997166]]),
 array([[ 12., -51.,   4.],
        [  6., 167., -68.],
        [ -4.,  24., -41.]]))

In [12]:
Q, R = scipy.linalg.qr(A)
R, Q, Q @ R

(array([[ -14.,  -21.,   14.],
        [   0., -175.,   70.],
        [   0.,    0.,  -35.]]),
 array([[-0.85714286,  0.39428571,  0.33142857],
        [-0.42857143, -0.90285714, -0.03428571],
        [ 0.28571429, -0.17142857,  0.94285714]]),
 array([[ 12., -51.,   4.],
        [  6., 167., -68.],
        [ -4.,  24., -41.]]))

----------------------

#Numpy

In [13]:
import numpy.linalg

In [14]:
A = np.array([[0, 1], 
              [1, 1], 
              [1, 1], 
              [2, 1]])
A

array([[0, 1],
       [1, 1],
       [1, 1],
       [2, 1]])

In [15]:
q, r = np.linalg.qr(A)
q, r

(array([[ 0.        ,  0.8660254 ],
        [-0.40824829,  0.28867513],
        [-0.40824829,  0.28867513],
        [-0.81649658, -0.28867513]]), array([[-2.44948974, -1.63299316],
        [ 0.        ,  1.15470054]]))

In [16]:
q @ r

array([[0., 1.],
       [1., 1.],
       [1., 1.],
       [2., 1.]])

In [17]:
b = np.array([1, 0, 2, 1])
p = np.dot(q.T, b)
np.dot(np.linalg.inv(r), p)

array([6.66133815e-16, 1.00000000e+00])

---------------------

#Sympy

In [18]:
A = Matrix([[1,1,1],[1,1,3],[2,3,4]])
Q, R = A.QRdecomposition()
A, Q, R, (Q @ R)

⎛           ⎡√6  -√3   -√2 ⎤                             ⎞
⎜           ⎢──  ────  ────⎥  ⎡    4⋅√6      ⎤           ⎟
⎜           ⎢6    3     2  ⎥  ⎢√6  ────  2⋅√6⎥           ⎟
⎜⎡1  1  1⎤  ⎢              ⎥  ⎢     3        ⎥  ⎡1  1  1⎤⎟
⎜⎢       ⎥  ⎢√6  -√3    √2 ⎥  ⎢              ⎥  ⎢       ⎥⎟
⎜⎢1  1  3⎥, ⎢──  ────   ── ⎥, ⎢     √3       ⎥, ⎢1  1  3⎥⎟
⎜⎢       ⎥  ⎢6    3     2  ⎥  ⎢0    ──    0  ⎥  ⎢       ⎥⎟
⎜⎣2  3  4⎦  ⎢              ⎥  ⎢     3        ⎥  ⎣2  3  4⎦⎟
⎜           ⎢√6   √3       ⎥  ⎢              ⎥           ⎟
⎜           ⎢──   ──    0  ⎥  ⎣0    0     √2 ⎦           ⎟
⎝           ⎣3    3        ⎦                             ⎠

-----------------------------

#Custom householder vectorization & QR factorization

stopped here

In [19]:
import numpy as np
from typing import Union

def householder_vectorized(a):
    """Use this version of householder to reproduce the output of np.linalg.qr 
    exactly (specifically, to match the sign convention it uses)

    based on https://rosettacode.org/wiki/QR_decomposition#Python
    """
    print("a.shape =", a.shape)
    print("a[0] =", a[0])
    denominator = a[0] + np.copysign(np.linalg.norm(a), a[0])
    v = a / denominator
    print("a =", a)
    print("v =", v)
    print("denominator =", denominator)
    v[0] = 1
    tau = 2 / (v.T @ v)

    return v,tau

def qr_decomposition(A: np.ndarray) -> Union[np.ndarray, np.ndarray]:
    m,n = A.shape
    R = A.copy()
    Q = np.identity(m)

    for j in range(0, n):
        # Apply Householder transformation.
        v, tau = householder_vectorized(R[j:, j, np.newaxis])

        H = np.identity(m)
        H[j:, j:] -= tau * (v @ v.T)
        R = H @ R
        Q = H @ Q

    return Q[:n].T, np.triu(R[:n])

m = 5
n = 4

A = np.random.rand(m, n)
q, r = np.linalg.qr(A)
Q, R = qr_decomposition(A)

with np.printoptions(linewidth=9999, precision=10, suppress=True):
    print("**** Q from qr_decomposition")
    print(Q)
    print("**** Q from np.linalg.qr")
    print(q)
    print()

    print("**** R from qr_decomposition")
    print(R)

a.shape = (5, 1)
a[0] = [0.83088211]
a = [[0.83088211]
 [0.23268183]
 [0.70234812]
 [0.76607875]
 [0.81876134]]
v = [[0.34469951]
 [0.09653032]
 [0.29137593]
 [0.3178152 ]
 [0.33967109]]
denominator = [2.41045343]
a.shape = (4, 1)
a[0] = [0.50375864]
a = [[ 0.50375864]
 [-0.020216  ]
 [ 0.02412138]
 [-0.22073079]]
v = [[ 0.47765313]
 [-0.01916838]
 [ 0.02287137]
 [-0.20929219]]
denominator = [1.05465372]
a.shape = (3, 1)
a[0] = [-0.0771868]
a = [[-0.0771868 ]
 [-0.60248477]
 [ 0.3078966 ]]
v = [[ 0.10180593]
 [ 0.7946505 ]
 [-0.40610186]]
denominator = [-0.75817579]
a.shape = (2, 1)
a[0] = [0.11882004]
a = [[ 0.11882004]
 [-0.21209887]]
v = [[ 0.32829251]
 [-0.58601619]]
denominator = [0.36193346]
**** Q from qr_decomposition
[[-0.5260174667 -0.0680666963  0.2361909464 -0.7373031476]
 [-0.1473069502 -0.9210071492  0.238536928   0.166820323 ]
 [-0.4446447616  0.0168636482 -0.048660121   0.6074588062]
 [-0.4849915529 -0.0654184277 -0.8047209868 -0.0605669533]
 [-0.5183440139  0.377556357

In [20]:
A = np.array([
      [1, 1],
      [1, 0]
])
Q, R = qr_decomposition(A)
Q, R

a.shape = (2, 1)
a[0] = [1]
a = [[1]
 [1]]
v = [[0.41421356]
 [0.41421356]]
denominator = [2.41421356]
a.shape = (1, 1)
a[0] = [-0.70710678]
a = [[-0.70710678]]
v = [[0.5]]
denominator = [-1.41421356]


(array([[-0.70710678,  0.70710678],
        [-0.70710678, -0.70710678]]), array([[-1.41421356, -0.70710678],
        [ 0.        ,  0.70710678]]))

In [21]:
A2 = np.array([[12, -51], 
              [6, 167], 
              [-4, 24]])
Q2, R2 = qr_decomposition(A2)

a.shape = (3, 1)
a[0] = [12]
a = [[12]
 [ 6]
 [-4]]
v = [[ 0.46153846]
 [ 0.23076923]
 [-0.15384615]]
denominator = [26.]
a.shape = (2, 1)
a[0] = [173.92307692]
a = [[173.92307692]
 [ 19.38461538]]
v = [[0.49845679]
 [0.05555556]]
denominator = [348.92307692]


In [22]:
Q2

array([[-0.85714286,  0.39428571],
       [-0.42857143, -0.90285714],
       [ 0.28571429, -0.17142857]])

In [23]:
R2

array([[ -14.,  -21.],
       [   0., -175.]])

In [24]:
Q2 @ R2

array([[ 12., -51.],
       [  6., 167.],
       [ -4.,  24.]])

In [25]:
Q3, R3 = scipy.linalg.qr(A2)
A2

array([[ 12, -51],
       [  6, 167],
       [ -4,  24]])

In [27]:
q, r = np.linalg.qr(A2, mode="complete")
q, r

(array([[-0.85714286,  0.39428571,  0.33142857],
        [-0.42857143, -0.90285714, -0.03428571],
        [ 0.28571429, -0.17142857,  0.94285714]]), array([[ -14.,  -21.],
        [   0., -175.],
        [   0.,    0.]]))

In [29]:
q, r = scipy.linalg.qr(A, mode="economic")
q, r

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]), array([[-1.41421356, -0.70710678],
        [ 0.        , -0.70710678]]))