In [645]:
import numpy as np
from scipy import linalg

Numpy QR

https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html


In [646]:
A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
A

array([[0, 1],
       [1, 1],
       [1, 1],
       [2, 1]])

In numpy the option mode{‘reduced’, ‘complete’, ‘r’, ‘raw’}, optional

In scipy the same option mode{‘full’, ‘r’, ‘economic’, ‘raw’},

Both have the first values as default. 

In case of tall matrix A, m by n, m>=n, scipy makes the suare matrix Q of the bigger side size m. 

Numpy, by default, reduces the Q matrix. And does some correspondent changes to R. 

The default of sympy is kind of scipy's full or numpy's complete. As to option specification, I did not find any. 


In [647]:
q, r = np.linalg.qr(A)
q

array([[ 0.        ,  0.8660254 ],
       [-0.40824829,  0.28867513],
       [-0.40824829,  0.28867513],
       [-0.81649658, -0.28867513]])

In [648]:
np.linalg.qr(A)

(array([[ 0.        ,  0.8660254 ],
        [-0.40824829,  0.28867513],
        [-0.40824829,  0.28867513],
        [-0.81649658, -0.28867513]]), array([[-2.44948974, -1.63299316],
        [ 0.        ,  1.15470054]]))

In [649]:
r

array([[-2.44948974, -1.63299316],
       [ 0.        ,  1.15470054]])

In [650]:
q, r = np.linalg.qr(A, mode="raw")
q

array([[-2.44948974,  0.40824829,  0.40824829,  0.81649658],
       [-1.63299316,  1.15470054,  0.06092551,  0.93511339]])

In [651]:
r

array([1.        , 1.06487826])

ScipyQR

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.qr.html

In [652]:
A

array([[0, 1],
       [1, 1],
       [1, 1],
       [2, 1]])

In [653]:
q, r = linalg.qr(A)
q

array([[ 0.        ,  0.8660254 , -0.33061251,  0.37509381],
       [-0.40824829,  0.28867513, -0.19985025, -0.84265051],
       [-0.40824829,  0.28867513,  0.86107527,  0.09246288],
       [-0.81649658, -0.28867513, -0.33061251,  0.37509381]])

In [654]:
r

array([[-2.44948974, -1.63299316],
       [ 0.        ,  1.15470054],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

Sympy QR

In [655]:
from sympy.interactive.printing import init_printing
from sympy.matrices import Matrix
from sympy import N

In [656]:
new_A = Matrix(A)
new_A

Matrix([
[0, 1],
[1, 1],
[1, 1],
[2, 1]])

In [657]:
Q, R = new_A.QRdecomposition()
Q

Matrix([
[        0,  sqrt(3)/2],
[sqrt(6)/6,  sqrt(3)/6],
[sqrt(6)/6,  sqrt(3)/6],
[sqrt(6)/3, -sqrt(3)/6]])

In [658]:
R

Matrix([
[sqrt(6), 2*sqrt(6)/3],
[      0, 2*sqrt(3)/3]])

In [659]:
A = np.array([[1,1,1],[1,1,3],[2,3,4]])
A

array([[1, 1, 1],
       [1, 1, 3],
       [2, 3, 4]])

If the matrix is square, I hypothesize, reduced will be the same as full. 

**numpy 3x3**

In [660]:
q, r = np.linalg.qr(A)
q

array([[-4.08248290e-01, -5.77350269e-01, -7.07106781e-01],
       [-4.08248290e-01, -5.77350269e-01,  7.07106781e-01],
       [-8.16496581e-01,  5.77350269e-01,  2.22044605e-16]])

In [661]:
r

array([[-2.44948974e+00, -3.26598632e+00, -4.89897949e+00],
       [ 0.00000000e+00,  5.77350269e-01, -1.33226763e-15],
       [ 0.00000000e+00,  0.00000000e+00,  1.41421356e+00]])

**scipy 3x3**

gives the same result

In [662]:
q, r = linalg.qr(A)
q

array([[-4.08248290e-01, -5.77350269e-01, -7.07106781e-01],
       [-4.08248290e-01, -5.77350269e-01,  7.07106781e-01],
       [-8.16496581e-01,  5.77350269e-01,  2.22044605e-16]])

In [663]:
r

array([[-2.44948974e+00, -3.26598632e+00, -4.89897949e+00],
       [ 0.00000000e+00,  5.77350269e-01, -1.33226763e-15],
       [ 0.00000000e+00,  0.00000000e+00,  1.41421356e+00]])

**sympy 3x3**

In [664]:
new_A = Matrix(A)
new_A

Matrix([
[1, 1, 1],
[1, 1, 3],
[2, 3, 4]])

In [665]:
Q, R = new_A.QRdecomposition()
Q

Matrix([
[sqrt(6)/6, -sqrt(3)/3, -sqrt(2)/2],
[sqrt(6)/6, -sqrt(3)/3,  sqrt(2)/2],
[sqrt(6)/3,  sqrt(3)/3,          0]])

In [666]:
R

Matrix([
[sqrt(6), 4*sqrt(6)/3, 2*sqrt(6)],
[      0,   sqrt(3)/3,         0],
[      0,           0,   sqrt(2)]])

In [667]:
N(Q)

Matrix([
[0.408248290463863, -0.577350269189626, -0.707106781186548],
[0.408248290463863, -0.577350269189626,  0.707106781186548],
[0.816496580927726,  0.577350269189626,                  0]])

In [668]:
N(R)

Matrix([
[2.44948974278318,   3.2659863237109, 4.89897948556636],
[               0, 0.577350269189626,                0],
[               0,                 0,  1.4142135623731]])

It is not exactly the same as the one of scipy. Some signs are different. The uniquiness comes when you require R's diagonal to be positive. 

In [669]:
A = np.array([[1,5,4],[-2,0,3],[2,-1,7]])
A

array([[ 1,  5,  4],
       [-2,  0,  3],
       [ 2, -1,  7]])

numpy

In [670]:
q, r = np.linalg.qr(A)
q

array([[-0.33333333, -0.93333333,  0.13333333],
       [ 0.66666667, -0.13333333,  0.73333333],
       [-0.66666667,  0.33333333,  0.66666667]])

In [671]:
r

array([[-3. , -1. , -4. ],
       [ 0. , -5. , -1.8],
       [ 0. ,  0. ,  7.4]])

Scipy

In [672]:
q, r = linalg.qr(A)
q

array([[-0.33333333, -0.93333333,  0.13333333],
       [ 0.66666667, -0.13333333,  0.73333333],
       [-0.66666667,  0.33333333,  0.66666667]])

In [673]:
r

array([[-3. , -1. , -4. ],
       [ 0. , -5. , -1.8],
       [ 0. ,  0. ,  7.4]])

sympy 

In [674]:
new_A = Matrix(A)
new_A

Matrix([
[ 1,  5, 4],
[-2,  0, 3],
[ 2, -1, 7]])

In [675]:
Q, R = new_A.QRdecomposition()
Q

Matrix([
[ 1/3, 14/15,  2/15],
[-2/3,  2/15, 11/15],
[ 2/3,  -1/3,   2/3]])

In [676]:
R

Matrix([
[3, 1,    4],
[0, 5,  9/5],
[0, 0, 37/5]])

In [677]:
N(Q)

Matrix([
[ 0.333333333333333,  0.933333333333333, 0.133333333333333],
[-0.666666666666667,  0.133333333333333, 0.733333333333333],
[ 0.666666666666667, -0.333333333333333, 0.666666666666667]])

In [678]:
A=np.array([ [4,2,1],[2,0,1],[2,0,-1],[1,2,1]])
A

array([[ 4,  2,  1],
       [ 2,  0,  1],
       [ 2,  0, -1],
       [ 1,  2,  1]])

In [679]:
np.linalg.qr(A)

(array([[-8.00000000e-01,  2.00000000e-01,  4.99600361e-17],
        [-4.00000000e-01, -4.00000000e-01,  7.07106781e-01],
        [-4.00000000e-01, -4.00000000e-01, -7.07106781e-01],
        [-2.00000000e-01,  8.00000000e-01, -1.60982339e-16]]),
 array([[-5.        , -2.        , -1.        ],
        [ 0.        ,  2.        ,  1.        ],
        [ 0.        ,  0.        ,  1.41421356]]))

Shapes in the rectangular cases. Full and reduced

In [680]:
import numpy as np
A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
q, r = np.linalg.qr(A)
q, np.shape(q)

(array([[ 0.        ,  0.8660254 ],
        [-0.40824829,  0.28867513],
        [-0.40824829,  0.28867513],
        [-0.81649658, -0.28867513]]), (4, 2))

In [681]:
r, np.shape(r)

(array([[-2.44948974, -1.63299316],
        [ 0.        ,  1.15470054]]), (2, 2))

In [682]:
import numpy as np
import scipy

A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
q, r = scipy.linalg.qr(A)
q, np.shape(q)

(array([[ 0.        ,  0.8660254 , -0.33061251,  0.37509381],
        [-0.40824829,  0.28867513, -0.19985025, -0.84265051],
        [-0.40824829,  0.28867513,  0.86107527,  0.09246288],
        [-0.81649658, -0.28867513, -0.33061251,  0.37509381]]), (4, 4))

In [683]:
r, np.shape(r)

(array([[-2.44948974, -1.63299316],
        [ 0.        ,  1.15470054],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]]), (4, 2))

In [684]:
import numpy as np
A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
q, r = np.linalg.qr(A, mode="complete")
q, np.shape(q)

(array([[ 0.        ,  0.8660254 , -0.33061251,  0.37509381],
        [-0.40824829,  0.28867513, -0.19985025, -0.84265051],
        [-0.40824829,  0.28867513,  0.86107527,  0.09246288],
        [-0.81649658, -0.28867513, -0.33061251,  0.37509381]]), (4, 4))

In [685]:
r, np.shape(r)

(array([[-2.44948974, -1.63299316],
        [ 0.        ,  1.15470054],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]]), (4, 2))

In [686]:
import numpy as np
import scipy

A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
q, r = scipy.linalg.qr(A, mode="economic")
q, np.shape(q)

(array([[ 0.        ,  0.8660254 ],
        [-0.40824829,  0.28867513],
        [-0.40824829,  0.28867513],
        [-0.81649658, -0.28867513]]), (4, 2))

In [687]:
r, np.shape(r)

(array([[-2.44948974, -1.63299316],
        [ 0.        ,  1.15470054]]), (2, 2))

In [688]:
import numpy as np
import scipy

A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
q, r = np.linalg.qr(A, mode="reduced")
q, np.shape(q)

(array([[ 0.        ,  0.8660254 ],
        [-0.40824829,  0.28867513],
        [-0.40824829,  0.28867513],
        [-0.81649658, -0.28867513]]), (4, 2))

In [689]:
r, np.shape(r)

(array([[-2.44948974, -1.63299316],
        [ 0.        ,  1.15470054]]), (2, 2))

In [690]:
from sympy import Matrix
A = [[0, 1], [1, 1], [1, 1], [2, 1]]
symA = Matrix(A)
Q, R = symA.QRdecomposition()
Q

Matrix([
[        0,  sqrt(3)/2],
[sqrt(6)/6,  sqrt(3)/6],
[sqrt(6)/6,  sqrt(3)/6],
[sqrt(6)/3, -sqrt(3)/6]])

In [691]:
np.shape(Q)

(4, 2)

In [692]:
R

Matrix([
[sqrt(6), 2*sqrt(6)/3],
[      0, 2*sqrt(3)/3]])

In [693]:
np.shape(R)

(2, 2)