In this notebook we are solving the system of linear equations
$$ A\overrightarrow{x}=\overrightarrow{b}$$
exactly and approximately using least-squares for different cases of the matrix $A$.

In [ ]:
import numpy as np
from scipy import linalg

# Case 1. Compatible systems ($\overrightarrow{b}\in col(A)$)

## Case 1.1. Unique solution:


*   $A$ square non-degenerate
*   $A$ tall full rank

For such $A$ both the system $A\overrightarrow{x}=\overrightarrow{b}$ and the normal equation $A^TA\overrightarrow{x}=A^T\overrightarrow{b}$ admits a unique solution. These solutions are close. The small mismatch is due to computation errors. 




In [ ]:
# A square non-degenerate
# the system admits a uniqe solution for any RHS b
A = np.array([[1, 2], [3, 4]])
b = np.array([[2], [4]])

# b in col(A)
# the system admits a unique solutio [0, 1]
x_exact = linalg.solve(A, b)
print('exact solution: x = \n', x_exact)

# solving normal equation
ATA = A.T @ A
ATb = A.T @ b
x_normeq = linalg.solve(ATA, ATb)
print('solution to normal equation: x = \n', x_normeq)

# applyong numpy.linalg.lstsq
x_approx = linalg.lstsq(A, b)[0]
print('least squares solution: x = \n', x_approx)
print('Check Ax=b: ', np.allclose(A @ x_approx, b))
print('Check if satisfies normal equation: \n', np.allclose(ATA @ x_approx, ATb))

exact solution: x = 
 [[0.]
 [1.]]
solution to normal equation: x = 
 [[0.]
 [1.]]
least squares solution: x = 
 [[3.37339617e-16]
 [1.00000000e+00]]
Check Ax=b:  True
Check if satisfies normal equation: 
 True


Case 1.1 a

Also unique solution of the original equation. But it is tall full rank. 

In [ ]:
# A tall full rank
A = np.array([[1, 2], [3, 4], [5, 6]])

# b in col(A)
# the system admits a unique solution [0, 1]
b = np.array([[2], [4], [6]])

# won't be able to find the solution using scipy.linalg.solve. Works for square matrices only
# x_exact = linalg.solve(A, b)
# print('exact solution: x = ', x_exact)
# print('Check Ax=b: ', np.allclose(A @ x_exact, b))

print("We do not print the soluton of the original system, because scipy does not want to solve non-square systems \n")

# solving normal equation
ATA = A.T @ A
ATb = A.T @ b
x_normeq = linalg.solve(ATA, ATb)
print('solution to normal equation: x = ', x_normeq)

# the output of np.linalg.lstsq is close to the exact solution
x_approx = linalg.lstsq(A, b)[0]
print('least squares solution: x = ', x_approx)
print('Check Ax=b: ', np.allclose(A @ x_approx, b))
print('Check if satisfies normal equation: ', np.allclose(ATA @ x_approx, ATb))

We do not print the soluton of the original system, because scipy does not want to solve non-square systems 

solution to normal equation: x =  [[0.]
 [1.]]
least squares solution: x =  [[-1.03127486e-16]
 [ 1.00000000e+00]]
Check Ax=b:  True
Check if satisfies normal equation:  True


## Case 1.2. Non-unique solution:



*   $A$ square degenerate
*   $A$ wide
* $A$ tall not full rank

In this case both the system $A\overrightarrow{x}=\overrightarrow{b}$ and the normal equation $A^TA\overrightarrow{x}=A^T\overrightarrow{b}$ admit infinitely many solutions.

Least squares outputs the solution of the initial system with the smallest $l_2$ norm.

In [ ]:
# A square degenerate
A = np.array([[1, 2], [3, 6]])

# b in col(A)
# the system admits infinitely many solutions (undertermined system)
b = np.array([[2], [6]])

# won't be able to find an exact solution
# x_exact = linalg.solve(A, b)
# print('exact solution: x = ', x_exact)

# normal equation has infinitely many solutions

print("Again, we do not print the soluton of the original system, because scipy does not want to solve non-square systems \n")
print("For the same reason we cannot even solve the normal equation \n")
print("linalg.lstsq(A, b) will find the solution for the smallest norm \n")

# the result solves both Ax=b and normal equation AT*A*x=AT*b, where AT is the transpose for A
x_approx = linalg.lstsq(A, b)[0]
print('least squares solution: x = ', x_approx)
print('Check Ax=b: ', np.allclose(A @ x_approx, b))
print('Check if satisfies normal equation: ', np.allclose(A.T @ A @ x_approx, A.T @ b))

Again, we do not print the soluton of the original system, because scipy does not want to solve non-square systems 

For the same reason we cannot even solve the normal equation 

linalg.lstsq(A, b) will find the solution for the smallest norm 

least squares solution: x =  [[0.4]
 [0.8]]
Check Ax=b:  True
Check if satisfies normal equation:  True


In [ ]:
# A wide full rank
# the system is compatible for any
# admits infinitly many solutions
A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[3], [6]])

# won't be able to find the solution using scipy.linalg.solve. Works for square matrices only
# x_exact = linalg.solve(A, b)
# print('exact solution: x = ', x_exact)
# print('Check Ax=b: ', np.allclose(A @ x_exact, b))

# normal equation has infinitely many solutions

# runs to completion for any RHS b
# the result solves both Ax=b and normal equation AT*A*x=AT*b, where AT is the transpose for A
x_approx = linalg.lstsq(A, b)[0]
print('least squares solution: x = ', x_approx)
print('Check Ax=b: ', np.allclose(A @ x_approx, b))
print('Check if satisfies normal equation: ', np.allclose(A.T @ A @ x_approx, A.T @ b))

least squares solution: x =  [[-0.16666667]
 [ 0.33333333]
 [ 0.83333333]]
Check Ax=b:  True
Check if satisfies normal equation:  True


In [ ]:
# A tall not full rank
A = np.array([[1, 2], [3, 6], [5, 10]])

# b in col(A)
# the system is incompatible
b = np.array([[2], [6], [10]])

# won't be able to find the solution using scipy.linalg.solve. Works for square matrices only
# x_exact = linalg.solve(A, b)
# print('exact solution: x = ', x_exact)
# print('Check Ax=b: ', np.allclose(A @ x_exact, b))

# normal equation has infinitely many solutions

# runs to completion for any RHS b
# the result does not solve Ax=b but solves normal equation AT*A*x=AT*b, where AT is the transpose for A
# the reason is that AT*b is alvays in col(AT)
x_approx = linalg.lstsq(A, b)[0]
print('least squares solution: x = ', x_approx)
print('Check Ax=b: ', np.allclose(A @ x_approx, b))
print('Check if satisfies normal equation: ', np.allclose(A.T @ A @ x_approx, A.T @ b))

least squares solution: x =  [[0.4]
 [0.8]]
Check Ax=b:  True
Check if satisfies normal equation:  True


# Case 2. Incompatible systems ($\overrightarrow{b}\not\in col(A)$)

In this case the original system $A\overrightarrow{x}=\overrightarrow{b}$ does not admit a solution, nevertheless, the normal equation $A^TA\overrightarrow{x}=A^T\overrightarrow{b}$ does. The reason is the normal equation is compatible for any $A$.

The least squares output does not solve the system $A\overrightarrow{x}=\overrightarrow{b}$ but solves the normal equation $A^TA\overrightarrow{x}=A^T\overrightarrow{b}$.

In case the normal system admits infinitely many solutions, the least squares outputs the one with the smallest $l_2$ norm.

In [ ]:
# A square degenerate
A = np.array([[1, 2], [3, 6]])

# b not in col(A)
# the system is incompetible
b = np.array([[0.1], [1.3]])

# won't be able to find an exact solution
# x_exact = linalg.solve(A, b)
# print('exact solution: x = ', x_exact)

# normal equation has infinitely many solutions

# runs to completion for any RHS b
# the result does not solve Ax=b but solves normal equation AT*A*x=AT*b, where AT is the transpose for A
# the reason is that AT*b is alvays in col(AT)
x_approx = linalg.lstsq(A, b)[0]
print('least squares solution: x = ', x_approx)
print('Check Ax=b: ', np.allclose(A @ x_approx, b))
print('Check if satisfies normal equation: ', np.allclose(A.T @ A @ x_approx, A.T @ b))

least squares solution: x =  [[0.08]
 [0.16]]
Check Ax=b:  False
Check if satisfies normal equation:  True


In [ ]:
# A tall full rank
A = np.array([[1, 2], [3, 4], [5, 6]])

# b not in col(A)
# the system is incompatible
b = np.array([[1], [0], [0]])

# won't be able to find the solution using scipy.linalg.solve. Works for square matrices only
# x_exact = linalg.solve(A, b)
# print('exact solution: x = ', x_exact)
# print('Check Ax=b: ', np.allclose(A @ x_exact, b))

# solving normal equation
ATA = A.T @ A
ATb = A.T @ b
x_normeq = linalg.solve(ATA, ATb)
print('solution to normal equation: x = ', x_normeq)

# runs to completion for any RHS b
# the result does not solve Ax=b but solves normal equation AT*A*x=AT*b, where AT is the transpose for A
# the reason is that AT*b is alvays in col(AT)
x_approx = linalg.lstsq(A, b)[0]
print('least squares solution: x = ', x_approx)
print('Check Ax=b: ', np.allclose(A @ x_approx, b))
print('Check if satisfies normal equation: ', np.allclose(ATA @ x_approx, ATb))

solution to normal equation: x =  [[-1.33333333]
 [ 1.08333333]]
least squares solution: x =  [[-1.33333333]
 [ 1.08333333]]
Check Ax=b:  False
Check if satisfies normal equation:  True


In [ ]:
# A tall not full rank
A = np.array([[1, 2], [3, 6], [5, 10]])

# b not in col(A)
# the system is incompatible
b = np.array([[1], [0], [0]])

# won't be able to find the solution using scipy.linalg.solve. Works for square matrices only
# x_exact = linalg.solve(A, b)
# print('exact solution: x = ', x_exact)
# print('Check Ax=b: ', np.allclose(A @ x_exact, b))

# normal equation has infinitely many solutions

# runs to completion for any RHS b
# the result does not solve Ax=b but solves normal equation AT*A*x=AT*b, where AT is the transpose for A
# the reason is that AT*b is alvays in col(AT)
x_approx = linalg.lstsq(A, b)[0]
print('least squares solution: x = ', x_approx)
print('Check Ax=b: ', np.allclose(A @ x_approx, b))
print('Check if satisfies normal equation: ', np.allclose(A.T @ A @ x_approx, A.T @ b))

least squares solution: x =  [[0.00571429]
 [0.01142857]]
Check Ax=b:  False
Check if satisfies normal equation:  True
