In [2]:
import numpy as np
from numpy import linalg

In [3]:
# A = np.array([
#               [-6, 3],
#               [4, 5]
# ])

A = np.array([
              [1, -2,-1],
              [1, 4, 2],
              [0, -6, -4]
])
coeffs = np.poly(A)
coeffs

array([ 1., -1., -2.,  6.])

In [4]:
linalg.eig(A)

(array([ 1.42273305+1.10771922j,  1.42273305-1.10771922j,
        -1.84546609+0.j        ]),
 array([[ 0.34372703-0.33826505j,  0.34372703+0.33826505j,
          0.09281251+0.j        ],
        [-0.58195882-0.11887861j, -0.58195882+0.11887861j,
         -0.33650155+0.j        ],
        [ 0.64391016+0.j        ,  0.64391016-0.j        ,
          0.93709794+0.j        ]]))

In [5]:
# given coefficients, find roots
roots = np.roots(coeffs)
roots

array([-1.84546609+0.j        ,  1.42273305+1.10771922j,
        1.42273305-1.10771922j])

In [6]:
eigenvectorCandidate = np.array([1, 4, 1])
A @ eigenvectorCandidate

array([ -8,  19, -28])

In [7]:
#eigenvectorCandidate2 = np.array([-3, 1])
#A @ eigenvectorCandidate2

In [8]:
v1 = np.array([1, 0])
v2 = A @ v1
v2

ValueError: ignored

In [ ]:
v3 = A @ v2
v3

In [ ]:
numerator = v3.T @ A @ v3
numerator



In [ ]:
denominator = v3.T @ v3
denominator

In [ ]:
lambdaHat = numerator / denominator
lambdaHat

In [ ]:
import numpy as np
a = np.array([[3, 1], [2, 2]])
w, v = np.linalg.eig(a)
np.isclose(np.dot(a, v), w*v)

In [ ]:
import numpy as np
a = np.array([[3, 1], [2, 2]])
w, v = np.linalg.eig(a)
print(w)

In [ ]:
import scipy.linalg as la
A = np.array([
              [1, -2,-1],
              [1, 4, 2],
              [0, -6, -4]
])

In [ ]:
eigvals, eigvecs = la.eig(A)

In [ ]:
eigvals

In [ ]:
eigvecs

In [ ]:
A = np.array([
               [-6, 3],
               [4, 5]
])
v = np.array([-3, 1])
A @ v

In [ ]:
np.linalg.eig(A)

Example 6.3 (QR iteration). To illustrate typical behavior of QR iteration, we apply the algorithm to the matrix

In [10]:
A1 = np.array([
               [2, 3],
               [3, 2]
])
x1Hat = np.array([0.555, 0.832])
x2Hat = np.array([0.832, -0.555])
A1 @ x1Hat

array([3.606, 3.329])

In [11]:
A1 @ x2Hat

array([-1.000e-03,  1.386e+00])

In [12]:
np.linalg.eig(A1)

(array([ 5., -1.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))