In [ ]:
import numpy as np
from scipy import linalg

In [ ]:
A = np.array([[2, 6], 
              [-1, 2]])
b = np.array([[4], 
              [3]])
L = np.array([[2, 0], 
              [-1, 5]])
U = np.array([[1, 3], 
              [0, 1]])



In [ ]:
L @ U

array([[ 2,  6],
       [-1,  2]])

In [ ]:
y = linalg.solve(L, b)
y

array([[2.],
       [1.]])

In [ ]:
linalg.solve(U, y)

array([[-1.],
       [ 1.]])

In [ ]:
linalg.solve(A, b)

array([[-1.],
       [ 1.]])

2 points regression

In [ ]:
X = np.array([[1, 1], 
              [1, 0]])
y = np.array([[2], 
              [3]])

In [ ]:
a = linalg.solve(X, y)
a

array([[ 3.],
       [-1.]])

In [ ]:
x = 2
y_predicted = a[0] + a[1] * x
y_predicted

array([1.])

# Linear regression on three observations and Tikhonov regularization

In [ ]:
X = np.array([[1, 1], [1, 0], [1, -1]])
y = np.array([[2], [3], [-2]])
XT = X.T
XTX = XT @ X
XTX

array([[3, 0],
       [0, 2]])

In [ ]:
XTy = XT @ y
XTy

array([[3],
       [4]])

In [ ]:
np.linalg.det(XTX)

6.0

In [ ]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[0.33333333, 0.        ],
       [0.        , 0.5       ]])

In [ ]:
x_ls = XTX_inv @ XTy
x_ls

array([[1.],
       [2.]])

In [ ]:
np.linalg.norm(x_ls)

2.23606797749979

In [ ]:
alpha = 1
X_reg = XTX + alpha * np.identity(2)
X_reg

array([[4., 0.],
       [0., 3.]])

In [ ]:
x_reg = linalg.solve(X_reg, XTy)
x_reg

array([[0.75      ],
       [1.33333333]])

In [ ]:
np.linalg.norm(x_reg)

1.5297966458904848