In [35]:
import numpy as np
 
 
# vector v1 of dimension (2, 2)
v1 = np.array([[1, 2], [1, 2]])
 
# vector v2 of dimension (2, 2)
v2 = np.array([[1, 2], [1, 2]])
 
print("vector multiplication")
print(np.dot(v1, v2))
 
print("\nElementwise multiplication of two vector")
print(v1 * v2)

vector multiplication
[[3 6]
 [3 6]]

Elementwise multiplication of two vector
[[1 4]
 [1 4]]


In [36]:
# vector v1 of dimension (2, 2)
v3 = np.array([[1, 2], 
               [1, 2]])
 
# vector v2 of dimension (2, 3)
v4 = np.array([[1, 2, 3], 
               [1, 2, 3]])
 
print("vector multiplication")
print(np.dot(v3, v4))
 
print("\nElementwise multiplication of two vector")
# print(v3 * v4)

vector multiplication
[[3 6 9]
 [3 6 9]]

Elementwise multiplication of two vector


1d

In [37]:
v5 = np.array([1, 2])
v6 = np.array([1, 2, 3])
 
# print(v5 @ v6)
# O: error
# B: error

# print(np.dot(v5, v6))
# O: error
# B: error

# print(v3 * v4)
# O: error
# B: error

In [38]:
v7 = np.array([1, 2])
v8 = np.array([1, 2])
 
print(v7 @ v8)

print(np.dot(v7, v8))

# above will be the same
# below will be different

print(v7 * v8)

5
5
[1 4]


In [39]:
v1@v2

array([[3, 6],
       [3, 6]])

In [40]:
v1 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
 
v2 = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
 
print("vector multiplication")
print(np.dot(v1, v2)) 
print((np.dot(v1, v2)).shape)
 
print("\nElementwise multiplication of two vector")
print(v1 * v2)

vector multiplication
[[[ 6 12 18]]

 [[ 6 12 18]]

 [[ 6 12 18]]]
(3, 1, 3)

Elementwise multiplication of two vector
[[[1 4 9]
  [1 4 9]
  [1 4 9]]]


In [41]:
print(v1@v2), (v1@v2).shape

[[[ 6 12 18]
  [ 6 12 18]
  [ 6 12 18]]]


(None, (1, 3, 3))

In [42]:
v1 = np.array([[1, 2], [1, 2]])
 
v2 = v1.copy()
 
print("vector multiplication")
print(np.dot(v1, v2)) 
print((np.dot(v1, v2)).shape)
 
print("\nElementwise multiplication of two vector")
print(v1 * v2)

print(v1@v2), (v1@v2).shape

vector multiplication
[[3 6]
 [3 6]]
(2, 2)

Elementwise multiplication of two vector
[[1 4]
 [1 4]]
[[3 6]
 [3 6]]


(None, (2, 2))

In [43]:
a = np.array([[1,2],[2,3]])
b = np.array(([8,4],[4,7]))
print(np.dot(a,b))
print("\n", a@b)
print("\n", a*b)

[[16 18]
 [28 29]]

 [[16 18]
 [28 29]]

 [[ 8  8]
 [ 8 21]]


However, when we deal with multi-dimensional arrays (N-D arrays with N>2) the result is slightly different. You can see the difference below.

In [44]:
a = np.random.rand(2,3,3)
print("a = \n", a)
b = np.random.rand(2,3,3)
print("b = \n", b)
print(b)
c = (a@b)
d = np.dot(a,b)
print("c: \n", c, "\n c.shape: \n", c.shape)
print("d: \n", d, "\n d.shape: \n", d.shape)

a = 
 [[[0.62494154 0.96060025 0.65982281]
  [0.60608642 0.60492008 0.93480992]
  [0.24260033 0.20138826 0.08588442]]

 [[0.8688593  0.27038176 0.0204358 ]
  [0.54825068 0.72294845 0.0508403 ]
  [0.00656706 0.85185637 0.97024569]]]
b = 
 [[[0.93232581 0.47155308 0.5924309 ]
  [0.74480861 0.29642546 0.10112074]
  [0.95229344 0.98770569 0.27316828]]

 [[0.84469754 0.49565556 0.73923265]
  [0.23901804 0.28141895 0.24519987]
  [0.76890243 0.72671169 0.26045258]]]
[[[0.93232581 0.47155308 0.5924309 ]
  [0.74480861 0.29642546 0.10112074]
  [0.95229344 0.98770569 0.27316828]]

 [[0.84469754 0.49565556 0.73923265]
  [0.23901804 0.28141895 0.24519987]
  [0.76890243 0.72671169 0.26045258]]]
c: 
 [[[1.9264574  1.23115022 0.64761395]
  [1.90583305 1.38843271 0.67559471]
  [0.45796543 0.25892407 0.18754936]]

 [[0.81426257 0.52159643 0.71390929]
  [0.67499494 0.51214113 0.59579315]
  [0.95518048 0.94807241 0.46643264]]] 
 c.shape: 
 (2, 3, 3)
d: 
 [[[[1.9264574  1.23115022 0.64761395]
   [1.2648267

The matmul() function broadcasts the array like a stack of matrices as elements residing in the last two indexes, respectively. The numpy.dot() function, on the other hand, performs multiplication as the sum of products over the last axis of the first array and the second-to-last of the second.

Another difference between the matmul() and the numpy.dot function is that the matmul() function cannot perform multiplication of array with scalar values.

In [45]:
a = np.random.rand(2,3,3)
a

array([[[0.90143694, 0.7294008 , 0.87331149],
        [0.86918946, 0.04372756, 0.6474432 ],
        [0.79284715, 0.13980762, 0.5351633 ]],

       [[0.50235312, 0.9113319 , 0.94781544],
        [0.19370275, 0.34531212, 0.50837787],
        [0.28226647, 0.69383285, 0.20605753]]])

In [46]:
b = np.random.rand(5,3,3)
b

array([[[0.39590276, 0.58672196, 0.97363995],
        [0.96552769, 0.9394261 , 0.10995391],
        [0.30040684, 0.74239459, 0.9158439 ]],

       [[0.07242809, 0.77767121, 0.40267488],
        [0.89914491, 0.61265592, 0.62954028],
        [0.5376385 , 0.79906898, 0.71120313]],

       [[0.922943  , 0.25246404, 0.30444065],
        [0.3182231 , 0.11921005, 0.33063951],
        [0.01313538, 0.18796106, 0.36280726]],

       [[0.72667081, 0.85890795, 0.24723071],
        [0.35590356, 0.12814851, 0.87723931],
        [0.34218201, 0.64043621, 0.42907526]],

       [[0.76166013, 0.01924862, 0.98872047],
        [0.81847961, 0.18572733, 0.91600579],
        [0.63063605, 0.56817892, 0.29153881]]])

In [47]:
from numpy import *
def print_3d_array(a_Array):
    prerow = []
    for i in a_Array[:,:,::-1].transpose(0,2,1): ## Get value of each col. of each last col. of each internal matrix as rows, starting with top row.
        for index, j in enumerate(i): ## Get the index and value of each element in modified matrix.
            print(" " * (len(i) - 1 - index) + "/ ", end="") ## Print the leading format chars.
            for k in j: ## Get value of each element in row.
                prerow = str(k).ljust( (len(str(amax(a_Array)))) + 1)
                print(prerow, end="") ## Print each element of each row with ljust to max len. of matrices max element.
            print("/") ## Print trailing format chars.
        
        print() ## Add a row between internal matrixes.

In [48]:
print_3d_array(a)

  / 0.8733114902360051 0.6474431988932987 0.535163296534905  /
 / 0.7294007976446809 0.043727560939138210.13980762236910038/
/ 0.9014369394316675 0.869189462613466  0.7928471505428824 /

  / 0.9478154388388872 0.5083778748306003 0.20605752907459107/
 / 0.9113319040855983 0.3453121248549871 0.6938328508162096 /
/ 0.5023531181098428 0.1937027489020473 0.2822664720734467 /



In [49]:
print_3d_array(b)

  / 0.9736399501006987 0.109953914308101090.9158438983133645 /
 / 0.5867219583534047 0.9394261045775932 0.7423945906404527 /
/ 0.3959027560037274 0.965527687661931  0.3004068394153594 /

  / 0.402674884944053350.6295402755577668 0.7112031343856032 /
 / 0.7776712139590921 0.6126559233329132 0.7990689797841716 /
/ 0.072428091672882330.899144908104679  0.5376384955904545 /

  / 0.304440648021127470.3306395147246478 0.36280726031217536/
 / 0.252464036041505360.119210051182187860.18796106376515054/
/ 0.9229430024648336 0.3182230988746596 0.013135381619507003/

  / 0.2472307106870415 0.8772393133100227 0.4290752585958141 /
 / 0.8589079529431163 0.128148510724001690.6404362111497062 /
/ 0.7266708124482028 0.355903555053584950.3421820083374144 /

  / 0.9887204702027568 0.9160057947216826 0.29153880612101213/
 / 0.0192486206923628830.185727327870999770.5681789187266676 /
/ 0.7616601287102422 0.8184796121632366 0.6306360492033903 /

