In [3]:
import numpy as np
import scipy.linalg as la

In [4]:
A = np.array([[2,4],[3,5]])
A

array([[2, 4],
       [3, 5]])

In [5]:
b = np.array([2,4]).reshape((-1,1))
b

array([[2],
       [4]])

In [6]:
x = la.solve(A, b)
x

array([[ 3.],
       [-1.]])

<a href="http://people.duke.edu/~ccc14/sta-663-2018/notebooks/S08B_Sovling_Linear_Equations_Annotated.html">More examples</a>



In [7]:

P, L, U = la.lu(A)
P

array([[0., 1.],
       [1., 0.]])

In [8]:
L

array([[1.        , 0.        ],
       [0.66666667, 1.        ]])

In [9]:
U

array([[3.        , 5.        ],
       [0.        , 0.66666667]])