In [1]:
# LU decomposition example
import numpy as np
# import scipy
# from scipy.linalg import *
from scipy import linalg
import math

In [2]:
A = np.array([[0, 1, -1], [1, 1, 2], [3, -1, 1]]) # one pivotin at the 1-st step
# A = np.array([[0, 1, -1], [1, 1, 2]]) # rectangular is possible
# A = np.array([[0, 0, 0], [0, 0, 0]]) # non full rank is also possible

P, L, U = linalg.lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)
print("LU:\n", L @ U)
PLU = P @ L @ U
print("PLU:\n", PLU)
print("PLU==A:\n", PLU==A)

LU = L @ U
print("LU:\n", LU)
PA = P @ A
print("PA:\n", PA)
print("LU==PA:\n", LU==PA)

P:
 [[1. 0.]
 [0. 1.]]
L:
 [[ 1.   0. ]
 [-0.5  1. ]]
U:
 [[2. 6.]
 [0. 5.]]
LU:
 [[ 2.  6.]
 [-1.  2.]]
PLU:
 [[ 2.  6.]
 [-1.  2.]]
PLU==A:
 [[ True  True]
 [ True  True]]
LU:
 [[ 2.  6.]
 [-1.  2.]]
PA:
 [[ 2.  6.]
 [-1.  2.]]
LU==PA:
 [[ True  True]
 [ True  True]]


Both above formulas give true because in this case P was a swap permutation, and thus it is self-inverse. If it were, for example, cyclic like 1 -> 2 -> 3 -> 1, or (2, 3, 1) one of those will fail. Which one? Let us experiment further. 

In [ ]:
cyclicP = np.array(
   [[0, 1, 0],
    [0, 0, 1],
    [1, 0, 0]] 
)
originalL = np.array(
   [[1, 0, 0],
    [1, 1, 0],
    [1, 1, 1]] 
)
originalU = np.array(
   [[1, 1, 1],
    [0, 2, 1],
    [0, 0, 3]] 
)
originalPL = cyclicP @ originalL
print("originalPL:\n", originalPL)
A = originalPL @ originalU
print("A = original PLU:\n", A)

originalPL:
 [[1 1 0]
 [1 1 1]
 [1 0 0]]
A = original PLU:
 [[1 3 2]
 [1 3 5]
 [1 1 1]]


In [ ]:
P, L, U = linalg.lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)
PLU = P @ L @ U
print("PLU:\n", PLU)
print("PLU==A:\n", PLU==A)

LU = L @ U
print("LU:\n", LU)
PA = P @ A
print("PA:\n", PA)
print("LU==PA:\n", LU==PA)


P:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
L:
 [[ 1.  0.  0.]
 [ 1.  1.  0.]
 [ 1. -0.  1.]]
U:
 [[ 1.  3.  2.]
 [ 0. -2. -1.]
 [ 0.  0.  3.]]
PLU:
 [[1. 3. 2.]
 [1. 3. 5.]
 [1. 1. 1.]]
PLU==A:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
LU:
 [[1. 3. 2.]
 [1. 1. 1.]
 [1. 3. 5.]]
PA:
 [[1. 3. 2.]
 [1. 1. 1.]
 [1. 3. 5.]]
LU==PA:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Here goes an example of a matrix with P not self-inverse
A = np.array([[1, 1, 2], [0, 1, -1],[3, -1, 1]])

P, L, U = linalg.lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)
PLU = P @ L @ U
# this works
print("PLU:\n", PLU)
print("PLU==A:\n", PLU==A)

LU = L @ U
print("LU:\n", LU)
PA = P @ A
# this fails
print("PA:\n", PA)
print("LU==PA:\n", LU==PA)

# the inverse of P equals its transpose
# the next should be Trye
Pinv = np.transpose(P)
PinvA = Pinv @ A
print("PinvA =", PinvA)
print("LU==PinvA:\n", LU==PinvA)

P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
 [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.         0.75       1.        ]]
U:
 [[ 3.         -1.          1.        ]
 [ 0.          1.33333333  1.66666667]
 [ 0.          0.         -2.25      ]]
PLU:
 [[ 1.  1.  2.]
 [ 0.  1. -1.]
 [ 3. -1.  1.]]
PLU==A:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
LU:
 [[ 3. -1.  1.]
 [ 1.  1.  2.]
 [ 0.  1. -1.]]
PA:
 [[ 0.  1. -1.]
 [ 3. -1.  1.]
 [ 1.  1.  2.]]
LU==PA:
 [[False False False]
 [False False False]
 [False  True False]]
PinvA = [[ 3. -1.  1.]
 [ 1.  1.  2.]
 [ 0.  1. -1.]]
LU==PinvA:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
