In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
A = np.array([[2,4],[3,5]])
A

array([[2, 4],
       [3, 5]])

In [3]:
b = np.array([2,4])
#.reshape((-1,1))
b

array([2, 4])

In [4]:
x = la.solve(A, b)
x

array([ 3., -1.])

<a href="http://people.duke.edu/~ccc14/sta-663-2018/notebooks/S08B_Sovling_Linear_Equations_Annotated.html">More examples</a>



In [5]:

P, L, U = la.lu(A)
P

array([[0., 1.],
       [1., 0.]])

In [6]:
L

array([[1.        , 0.        ],
       [0.66666667, 1.        ]])

In [7]:
U

array([[3.        , 5.        ],
       [0.        , 0.66666667]])