In [201]:
from scipy import linalg as la
import numpy as np

In [202]:
A = np.array([[2, 3], [5, 4]])
b = np.array([4, 3])
P, L, U = la.lu(A)
L

array([[1. , 0. ],
       [0.4, 1. ]])

In [203]:
U

array([[5. , 4. ],
       [0. , 1.4]])

In [204]:
P

array([[0., 1.],
       [1., 0.]])

In [205]:
P.dot(L.dot(U))

array([[2., 3.],
       [5., 4.]])

In [206]:
la.solve(A, b)

array([-1.,  2.])

In [207]:
import sympy
sympy.init_printing()

In [208]:
A = sympy.Matrix([[2, 3], [5, 4]])
b = sympy.Matrix([4, 3])
L, U, _ = A.LUdecomposition()
L

⎡ 1   0⎤
⎢      ⎥
⎣5/2  1⎦

In [209]:
U

⎡2   3  ⎤
⎢       ⎥
⎣0  -7/2⎦

In [210]:
L * U

⎡2  3⎤
⎢    ⎥
⎣5  4⎦

In [211]:
x = A.solve(b); x # equivalent to A.LUsolve(b)

⎡-1⎤
⎢  ⎥
⎣2 ⎦

In [212]:
# Book example
A3 = sympy.Matrix([[1, 1, -2], [3, -1, 1], [0, 1, -1]])
A3

⎡1  1   -2⎤
⎢         ⎥
⎢3  -1  1 ⎥
⎢         ⎥
⎣0  1   -1⎦

In [213]:
L3, U3, P3 = A3.LUdecomposition()
L3

⎡1   0    0⎤
⎢          ⎥
⎢3   1    0⎥
⎢          ⎥
⎣0  -1/4  1⎦

In [214]:
U3

⎡1  1   -2 ⎤
⎢          ⎥
⎢0  -4   7 ⎥
⎢          ⎥
⎣0  0   3/4⎦

In [215]:
P3

In [216]:
L3.inv()

⎡ 1     0   0⎤
⎢            ⎥
⎢ -3    1   0⎥
⎢            ⎥
⎣-3/4  1/4  1⎦

In [217]:
U3.inv()

⎡1  1/4   1/3⎤
⎢            ⎥
⎢0  -1/4  7/3⎥
⎢            ⎥
⎣0   0    4/3⎦

In [218]:
A3.inv()

⎡0   1/3  1/3⎤
⎢            ⎥
⎢-1  1/3  7/3⎥
⎢            ⎥
⎣-1  1/3  4/3⎦

In [219]:
myU3 = sympy.Matrix([[1,  1,  -2], [0,  1,  -7/4], [0,  0,  1]])
myU3

⎡1  1   -2  ⎤
⎢           ⎥
⎢0  1  -1.75⎥
⎢           ⎥
⎣0  0    1  ⎦

In [220]:
myU3inv = myU3.inv()
myU3inv

⎡1  -1  0.25⎤
⎢           ⎥
⎢0  1   1.75⎥
⎢           ⎥
⎣0  0    1  ⎦

In [221]:
myL3 = sympy.Matrix([[1,0, 0], [3/4, -1/4, 0], [-1, 1/3, 4/3]])
myL3 

⎡ 1            0                 0        ⎤
⎢                                         ⎥
⎢0.75        -0.25               0        ⎥
⎢                                         ⎥
⎣ -1   0.333333333333333  1.33333333333333⎦

In [222]:
myL3inv = myL3.inv()
myL3inv

⎡ 1    0     0  ⎤
⎢               ⎥
⎢3.0  -4.0   0  ⎥
⎢               ⎥
⎣ 0   1.0   0.75⎦

In [223]:
A3invByLU = myU3inv * myL3
A3invByLU

⎡ 0    0.333333333333333  0.333333333333333⎤
⎢                                          ⎥
⎢-1.0  0.333333333333333  2.33333333333333 ⎥
⎢                                          ⎥
⎣ -1   0.333333333333333  1.33333333333333 ⎦

In [224]:
A3invDirectly = A3.inv()
A3invDirectly

⎡0   1/3  1/3⎤
⎢            ⎥
⎢-1  1/3  7/3⎥
⎢            ⎥
⎣-1  1/3  4/3⎦

In [225]:
b3np = np.array([[-3], [4], [-1]])
b3np

array([[-3],
       [ 4],
       [-1]])

In [226]:
A3np = np.array([[1, 1, -2], [3, -1, 1], [0, 1, -1]])
A3np

array([[ 1,  1, -2],
       [ 3, -1,  1],
       [ 0,  1, -1]])

In [227]:
la.solve(A3np, b3np)

array([[1.],
       [2.],
       [3.]])

In [229]:
x3 = A3invDirectly * b3np
x3

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

In [230]:
# Or using LU:
x3byLU = myU3inv * myL3 * b3np
x3byLU


⎡1.0⎤
⎢   ⎥
⎢2.0⎥
⎢   ⎥
⎣3.0⎦