In this notebook we test scipy.linalg.lu on different matrices including non-square and degenerate

scipy.linalg.lu returns 

$P$ permutation matrix,

$L$ lower-unitriangular matrix,

$U$ upper-triangular matrix

Applies partial pivoting to any input matrix

In [1]:
import numpy as np
from scipy import linalg

In [2]:
A = np.array([[0, 1, -1], [1, 1, 2], [3, -1, 1]]) # one pivotin at the 1-st step
# A = np.array([[0, 1, -1], [1, 1, 2]]) # rectangular is possible
# A = np.array([[0, 0, 0], [0, 0, 0]]) # non full rank is also possible

P, L, U = linalg.lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)
print("LU:\n", L @ U)
PLU = P @ L @ U
print("PLU:\n", PLU)
print("PLU==A:\n", PLU==A)

LU = L @ U
print("LU:\n", LU)
PA = P @ A
print("PA:\n", PA)
print("LU==PA:\n", LU==PA)

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.         0.75       1.        ]]
U:
 [[ 3.         -1.          1.        ]
 [ 0.          1.33333333  1.66666667]
 [ 0.          0.         -2.25      ]]
LU:
 [[ 3. -1.  1.]
 [ 1.  1.  2.]
 [ 0.  1. -1.]]
PLU:
 [[ 0.  1. -1.]
 [ 1.  1.  2.]
 [ 3. -1.  1.]]
PLU==A:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
LU:
 [[ 3. -1.  1.]
 [ 1.  1.  2.]
 [ 0.  1. -1.]]
PA:
 [[ 3. -1.  1.]
 [ 1.  1.  2.]
 [ 0.  1. -1.]]
LU==PA:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Both these formulas produce a true answer since P is a swap of two rows and thus it is symmetric and self inverse.

In the following example P is not self inverse. In this case $A=PLU$ produces true and $PA=LU$ fails. The inverse of P equals its transpose, thus, $P^TA=LU$ is also true.

In [3]:
# Here goes an example of a matrix with P not self-inverse
A = np.array([[1, 1, 2], [0, 1, -1],[3, -1, 1]])

P, L, U = linalg.lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)
PLU = P @ L @ U
# this works
print("PLU:\n", PLU)
print("PLU==A:\n", PLU==A)

LU = L @ U
print("LU:\n", LU)
PA = P @ A
# this fails
print("PA:\n", PA)
print("LU==PA:\n", LU==PA)

# the inverse of P equals its transpose
# the next should be Trye
Pinv = np.transpose(P)
PinvA = Pinv @ A
print("PinvA =", PinvA)
print("LU==PinvA:\n", LU==PinvA)

P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
 [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.         0.75       1.        ]]
U:
 [[ 3.         -1.          1.        ]
 [ 0.          1.33333333  1.66666667]
 [ 0.          0.         -2.25      ]]
PLU:
 [[ 1.  1.  2.]
 [ 0.  1. -1.]
 [ 3. -1.  1.]]
PLU==A:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
LU:
 [[ 3. -1.  1.]
 [ 1.  1.  2.]
 [ 0.  1. -1.]]
PA:
 [[ 0.  1. -1.]
 [ 3. -1.  1.]
 [ 1.  1.  2.]]
LU==PA:
 [[False False False]
 [False False False]
 [False  True False]]
PinvA = [[ 3. -1.  1.]
 [ 1.  1.  2.]
 [ 0.  1. -1.]]
LU==PinvA:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
import scipy.linalg # SciPy Linear Algebra Library
A = scipy.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
P, L, U = scipy.linalg.lu(A)
P.dot(L.dot(U)) == L.dot(U)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])