In [19]:
import scipy.linalg
A = scipy.array([[1, 2, 3],
             [4, 5, 6],
             [10, 11, 9]])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.1        1.         0.        ]
 [0.4        0.66666667 1.        ]]
[[10.  11.   9. ]
 [ 0.   0.9  2.1]
 [ 0.   0.   1. ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  after removing the cwd from sys.path.


In [20]:
import numpy as np
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [10, 11, 9]])

B = scipy.array([[1, 2, 3],
             [4, 5, 6],
             [10, 11, 9]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  


In [21]:
(A == B).all()


True

In [22]:
type(B)

numpy.ndarray

In [23]:
import numpy as np
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [10, 11, 9]])
P, L, U = scipy.linalg.lu(A)
mult = P.dot((L.dot(U)))
print(mult)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [10. 11.  9.]]


In [24]:
P @ L @ U

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [10., 11.,  9.]])

In [25]:
P * L * U

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
P * L @ U

array([[0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [4. , 4.4, 3.6]])

In [27]:
(P @ L) * U

array([[ 1. , 11. ,  0. ],
       [ 0. ,  0.6,  2.1],
       [ 0. ,  0. ,  0. ]])

In [28]:
U @ L @ P

array([[ 9.        , 14.7       , 17.        ],
       [ 2.1       ,  0.93      ,  2.3       ],
       [ 1.        ,  0.4       ,  0.66666667]])