In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
A = np.array([[2,4],[3,5]])
A

array([[2, 4],
       [3, 5]])

In [3]:
b = np.array([2,4])
#.reshape((-1,1))
b

array([2, 4])

In [4]:
x = la.solve(A, b)
x

array([ 3., -1.])

<a href="http://people.duke.edu/~ccc14/sta-663-2018/notebooks/S08B_Sovling_Linear_Equations_Annotated.html">More examples</a>



In [5]:

P, L, U = la.lu(A)
P

array([[0., 1.],
       [1., 0.]])

In [6]:
L

array([[1.        , 0.        ],
       [0.66666667, 1.        ]])

In [7]:
U

array([[3.        , 5.        ],
       [0.        , 0.66666667]])

------------------------------ 

In [8]:
from scipy.linalg import lu
import numpy as np
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
P, L, U = lu(A)
np.allclose(A - (P @ L @ U), np.zeros((4, 4)))

True

In [9]:
from scipy.linalg import lu
import numpy as np
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
P, L, U = lu(A)
A - (P @ L @ U)

array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 8.8817842e-16,  0.0000000e+00, -4.4408921e-16,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 8.8817842e-16,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00]])

In [10]:
import scipy.linalg # SciPy Linear Algebra Library
A = scipy.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
P, L, U = scipy.linalg.lu(A)
P.dot(L.dot(U)) == L.dot(U)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [11]:
(P @ L @ U) == (L @ U @ P)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])