LU with scipy

scipy.linalg.lu returns 

$P$ permutation matrix,

$L$ lower-unitriangular matrix,

$U$ upper-triangular matrix

Applies partial pivoting to any input matrix

In [ ]:
from scipy import linalg as la
import numpy as np

In [ ]:
A = np.array([[2, 3], [5, 4]])
b = np.array([4, 3])
P, L, U = la.lu(A)
L

array([[1. , 0. ],
       [0.4, 1. ]])

In [ ]:
U

array([[5. , 4. ],
       [0. , 1.4]])

In [ ]:
P

array([[0., 1.],
       [1., 0.]])

In [ ]:
P.dot(L.dot(U))

array([[2., 3.],
       [5., 4.]])

In [ ]:
la.solve(A, b)

array([-1.,  2.])

In [ ]:
import sympy
sympy.init_printing()

In [ ]:
# try a matrix which requires permutation
# when reducing A to upper-triangular zerows appear 2 times on the diagonal
# hence 2 permutations are required
# [0,1] swaps the 1-st and 2-nd rows at the first step of elimenation
# [1,2] swaps the 2-nd and 3-d rows at the second step

A = sympy.Matrix([[0, 0, 2], [1, 3, 2], [1, 2, 3]])
L, U, P = A.LUdecomposition()
P

In [ ]:
# works for degenerate matrix
A = sympy.Matrix([[0, 0,], [1, 3]])
L, U, P = A.LUdecomposition()
print('L:\n', L)
print('U:\n', U)
print('P:\n', P)

L:
 Matrix([[1, 0], [0, 1]])
U:
 Matrix([[1, 3], [0, 0]])
P:
 [[0, 1]]


In [ ]:
# both wide and tall matrices also work
A = sympy.Matrix([[1, 2], [4, 5], [7, 9]])
L, U, P = A.LUdecomposition()
print('L:\n', L)
print('U:\n', U)
print('P:\n', P)

L:
 Matrix([[1, 0, 0], [4, 1, 0], [7, 5/3, 1]])
U:
 Matrix([[1, 2], [0, -3], [0, 0]])
P:
 []


In [ ]:
# problems with small pivot
eps = 10**(-18)
A = sympy.Matrix([[eps, 1], [1, 1]])
L, U, P = A.LUdecomposition()
print('L=\n', L)
print('U=\n', U)
print('P=\n', P)
LU = L@U
print('A=\n', A)
print('LU=\n', LU)
# the product LU is not equal to the original matrix A

L=
 Matrix([[1, 0], [1.00000000000000e+18, 1]])
U=
 Matrix([[1.00000000000000e-18, 1], [0, -1.00000000000000e+18]])
P=
 []
A=
 Matrix([[1.00000000000000e-18, 1], [1, 1]])
LU=
 Matrix([[1.00000000000000e-18, 1], [1.00000000000000, 0]])


In [ ]:
A = sympy.Matrix([[2, 3], [5, 4]])
b = sympy.Matrix([4, 3])
L, U, P = A.LUdecomposition()
L

⎡ 1   0⎤
⎢      ⎥
⎣5/2  1⎦

In [ ]:
U

⎡2   3  ⎤
⎢       ⎥
⎣0  -7/2⎦

In [ ]:
P # the matrix admits LU factorization without permutations, hence, P is emty

In [ ]:
L * U

⎡2  3⎤
⎢    ⎥
⎣5  4⎦

In [ ]:
L @ U

⎡2  3⎤
⎢    ⎥
⎣5  4⎦

In [ ]:
x = A.solve(b); x # equivalent to A.LUsolve(b)

⎡-1⎤
⎢  ⎥
⎣2 ⎦

In [ ]:
# Book example
A3 = sympy.Matrix([[1, 1, -2], [3, -1, 1], [0, 1, -1]])
A3

⎡1  1   -2⎤
⎢         ⎥
⎢3  -1  1 ⎥
⎢         ⎥
⎣0  1   -1⎦

In [ ]:
L3, U3, P3 = A3.LUdecomposition()
L3

⎡1   0    0⎤
⎢          ⎥
⎢3   1    0⎥
⎢          ⎥
⎣0  -1/4  1⎦

In [ ]:
U3

⎡1  1   -2 ⎤
⎢          ⎥
⎢0  -4   7 ⎥
⎢          ⎥
⎣0  0   3/4⎦

In [ ]:
P3

In [ ]:
L3.inv()

⎡ 1     0   0⎤
⎢            ⎥
⎢ -3    1   0⎥
⎢            ⎥
⎣-3/4  1/4  1⎦

In [ ]:
U3.inv()

⎡1  1/4   1/3⎤
⎢            ⎥
⎢0  -1/4  7/3⎥
⎢            ⎥
⎣0   0    4/3⎦

In [ ]:
A3.inv()

⎡0   1/3  1/3⎤
⎢            ⎥
⎢-1  1/3  7/3⎥
⎢            ⎥
⎣-1  1/3  4/3⎦

In [ ]:
myU3 = sympy.Matrix([[1,  1,  -2], [0,  1,  -7/4], [0,  0,  1]])
myU3

⎡1  1   -2  ⎤
⎢           ⎥
⎢0  1  -1.75⎥
⎢           ⎥
⎣0  0    1  ⎦

In [ ]:
myU3inv = myU3.inv()
myU3inv

⎡1  -1  0.25⎤
⎢           ⎥
⎢0  1   1.75⎥
⎢           ⎥
⎣0  0    1  ⎦

In [ ]:
myL3 = sympy.Matrix([[1,0, 0], [3/4, -1/4, 0], [-1, 1/3, 4/3]])
myL3 

⎡ 1            0                 0        ⎤
⎢                                         ⎥
⎢0.75        -0.25               0        ⎥
⎢                                         ⎥
⎣ -1   0.333333333333333  1.33333333333333⎦

In [ ]:
myL3inv = myL3.inv()
myL3inv

⎡ 1    0     0  ⎤
⎢               ⎥
⎢3.0  -4.0   0  ⎥
⎢               ⎥
⎣ 0   1.0   0.75⎦

In [ ]:
A3invByLU = myU3inv * myL3
A3invByLU

⎡ 0    0.333333333333333  0.333333333333333⎤
⎢                                          ⎥
⎢-1.0  0.333333333333333  2.33333333333333 ⎥
⎢                                          ⎥
⎣ -1   0.333333333333333  1.33333333333333 ⎦

In [ ]:
A3invDirectly = A3.inv()
A3invDirectly

⎡0   1/3  1/3⎤
⎢            ⎥
⎢-1  1/3  7/3⎥
⎢            ⎥
⎣-1  1/3  4/3⎦

In [ ]:
b3np = np.array([[-3], [4], [-1]])
b3np

array([[-3],
       [ 4],
       [-1]])

In [ ]:
A3np = np.array([[1, 1, -2], [3, -1, 1], [0, 1, -1]])
A3np

array([[ 1,  1, -2],
       [ 3, -1,  1],
       [ 0,  1, -1]])

In [ ]:
la.solve(A3np, b3np)

array([[1.],
       [2.],
       [3.]])

In [ ]:
x3 = A3invDirectly * b3np
x3

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

In [ ]:
# Or using LU:
x3byLU = myU3inv * myL3 * b3np
x3byLU


⎡1.0⎤
⎢   ⎥
⎢2.0⎥
⎢   ⎥
⎣3.0⎦