In [ ]:
import pprint
import numpy as np
import scipy
import scipy.linalg   # SciPy Linear Algebra Library

In [ ]:
x = np.array([[3], [4]])
x

array([[3],
       [4]])

In [ ]:
# l_1 norm of vector x
np.linalg.norm(x, 1)

7.0

In [ ]:
# l_2 norm of vector x
np.linalg.norm(x, 2)

5.0

In [ ]:
# l_infty norm of vector x
np.linalg.norm(x, np.inf)

4.0

In [ ]:
A = np.array([[2, -2], [-3, 5]])
A

array([[ 2, -2],
       [-3,  5]])

In [ ]:
# inverse of A
Ainv = np.linalg.inv(A)
Ainv

array([[1.25, 0.5 ],
       [0.75, 0.5 ]])

In [ ]:
# induced l_1 norm of matrix A
np.linalg.norm(A, 1)

7.0

In [ ]:
# induced l_1 norm of the inverse of matrix A
np.linalg.norm(Ainv, 1)

2.0000000000000004

In [ ]:
# condition number of A with respect to l_1 norm
condA1 = np.linalg.cond(A, 1)
condA1

14.000000000000004

In [ ]:
# induced l_inf norm of matrix A
np.linalg.norm(A, np.inf)

8.0

In [ ]:
# induced l_inf norm of the inverse of matrix A
np.linalg.norm(Ainv, np.inf)

1.7500000000000004

In [ ]:
# condition number of A with respect to l_1 norm
condAinf = np.linalg.cond(A, np.inf)
condAinf

14.000000000000004

Note, that the condition numbers of $2 \times 2$ matrices with respect to $l_1$ and $l_\infty$ norms are always the same. This is not generally true for square matrices of higher order.

In [ ]:
n=3
A = np.random.rand(n, n)
cond1 = np.linalg.cond(A, 1)
print('cond1 = ', cond1)
cond2 = np.linalg.cond(A, 2)
print('cond2 = ', cond2)
cond_infty = np.linalg.cond(A, np.inf)
print('cond_infty = ', cond_infty)

cond1 =  67.77710708875978
cond2 =  40.44374340550412
cond_infty =  58.460429851173785


In [ ]:
B = np.array([[3, -1, 0], [2, 0, 1], [1, 2, 1]])
print(np.linalg.det(B))
print(np.linalg.norm(B, 1))
print(np.linalg.norm(B, np.inf))
print(np.linalg.norm(np.linalg.inv(B), 1))
print(np.linalg.norm(np.linalg.inv(B), np.inf))
cond1 = np.linalg.cond(B, 1)
print('cond1 = ', cond1)
cond2 = np.linalg.cond(B, 2)
print('cond2 = ', cond2)
cond_infty = np.linalg.cond(B, np.inf)
print('cond_infty = ', cond_infty)

-5.000000000000001
6.0
4.0
2.1999999999999997
2.5999999999999996
cond1 =  13.2
cond2 =  7.2072407876685665
cond_infty =  10.399999999999999
