In [ ]:
import pprint
import numpy as np
import scipy
import scipy.linalg   # SciPy Linear Algebra Library

In [ ]:
x = np.array([[3], [4]])
x

array([[3],
       [4]])

In [ ]:
# l_1 norm of vector x
np.linalg.norm(x, 1)

7.0

In [ ]:
# l_2 norm of vector x
np.linalg.norm(x, 2)

5.0

In [ ]:
# l_infty norm of vector x
np.linalg.norm(x, np.inf)

4.0

In [ ]:
A = np.array([[2, -2], [-3, 5]])
A

array([[ 2, -2],
       [-3,  5]])

In [ ]:
# inverse of A
Ainv = np.linalg.inv(A)
Ainv

array([[1.25, 0.5 ],
       [0.75, 0.5 ]])

In [ ]:
# induced l_1 norm of matrix A
np.linalg.norm(A, 1)

7.0

In [ ]:
# induced l_1 norm of the inverse of matrix A
np.linalg.norm(Ainv, 1)

2.0000000000000004

In [ ]:
# condition number of A with respect to l_1 norm
condA1 = np.linalg.cond(A, 1)
condA1

14.000000000000004

In [ ]:
# induced l_inf norm of matrix A
np.linalg.norm(A, np.inf)

8.0

In [ ]:
# induced l_inf norm of the inverse of matrix A
np.linalg.norm(Ainv, np.inf)

1.7500000000000004

In [ ]:
# condition number of A with respect to l_1 norm
condAinf = np.linalg.cond(A, np.inf)
condAinf

14.000000000000004

Note, that the condition numbers of $2 \times 2$ matrices with respect to $l_1$ and $l_\infty$ norms are always the same. This is not generally true for square matrices of higher order.

In [ ]:
n=3
A = np.random.rand(n, n)
cond1 = np.linalg.cond(A, 1)
print('cond1 = ', cond1)
cond2 = np.linalg.cond(A, 2)
print('cond2 = ', cond2)
cond_infty = np.linalg.cond(A, np.inf)
print('cond_infty = ', cond_infty)

cond1 =  67.77710708875978
cond2 =  40.44374340550412
cond_infty =  58.460429851173785


In [ ]:
B = np.array([[3, -1, 0], [2, 0, 1], [1, 2, 1]])
print(np.linalg.det(B))
print(np.linalg.norm(B, 1))
print(np.linalg.norm(B, np.inf))
print(np.linalg.norm(np.linalg.inv(B), 1))
print(np.linalg.norm(np.linalg.inv(B), np.inf))
cond1 = np.linalg.cond(B, 1)
print('cond1 = ', cond1)
cond2 = np.linalg.cond(B, 2)
print('cond2 = ', cond2)
cond_infty = np.linalg.cond(B, np.inf)
print('cond_infty = ', cond_infty)

-5.000000000000001
6.0
4.0
2.1999999999999997
2.5999999999999996
cond1 =  13.2
cond2 =  7.2072407876685665
cond_infty =  10.399999999999999


#Cholesky 2 by 2 other numbers

In [70]:
A = np.array([[9, 3], [3, 17]])
L = scipy.linalg.cholesky(A, lower=True)
L

array([[3., 0.],
       [1., 4.]])

In [ ]:
U = scipy.linalg.cholesky(A, lower=False)
U

array([[3., 1.],
       [0., 4.]])

In [ ]:
U.T @ U

array([[ 9.,  3.],
       [ 3., 17.]])

In [ ]:
L @ L.T

array([[ 9.,  3.],
       [ 3., 17.]])

In [ ]:
U.T == L

array([[ True,  True],
       [ True,  True]])

In [ ]:
E1 = np.array([[1/3, 0], [-1/3, 1]])
E1 @ A

array([[ 3.,  1.],
       [ 0., 16.]])

In [ ]:
E1 @ A @ E1.T

array([[ 1.,  0.],
       [ 0., 16.]])

In [ ]:
E2 = np.array([[1, 0], [0, 1/4]])
E2 @ E1 @ A @ E1.T

array([[1., 0.],
       [0., 4.]])

In [ ]:
E2 @ E1 @ A @ E1.T @ E2.T

array([[1., 0.],
       [0., 1.]])

In [ ]:
L = np.linalg.inv(E1) @ np.linalg.inv(E2)
L

array([[3., 0.],
       [1., 4.]])

In [ ]:
L @ L.T

array([[ 9.,  3.],
       [ 3., 17.]])

#Matrix condition old draft

##1. Compute the norm of A

In [ ]:
A = np.array([[1, 2], [-3, 4]])
np.linalg.norm(A, ord=1)

6.0

##2. Find a determinant of A = a11*a22 - a12*a21

In [ ]:
np.linalg.det(A)

10.000000000000002

##3. Find an inverse A^{-1}


In [ ]:
np.linalg.inv(A)

array([[ 0.4, -0.2],
       [ 0.3,  0.1]])

##4. Find a norm of the inverse

In [ ]:
np.linalg.norm(np.linalg.inv(A), ord=1)

0.7000000000000001

##5. Find the relative condition number 

In [ ]:
np.linalg.cond(A, p=1)

4.2

#Matrix condition clean

##Q2

In [ ]:
x = np.array([1, 2])
np.linalg.norm(x, ord=1)

3.0

##Q4

In [ ]:
A = np.array([[1, 2], [-3, 4]])
np.linalg.norm(A, ord=1)

6.0

##Q5

In [ ]:
A @ x

array([5, 5])

##Q6

In [ ]:
np.linalg.norm(A @ x, ord=1)

10.0

##Q8

In [ ]:
np.linalg.det(A)

10.000000000000002

##Q9

In [ ]:
np.linalg.inv(A)

array([[ 0.4, -0.2],
       [ 0.3,  0.1]])

##Q10

In [ ]:
np.linalg.norm(np.linalg.inv(A), ord=1)

0.7000000000000001

##Q11

In [ ]:
np.linalg.cond(A, p=1)

4.2