In [44]:
import numpy as np
import scipy.linalg as la

import numpy
import scipy
a = numpy.array([[3, 1], [2, 2]])
w, v = numpy.linalg.eig(a)
eigvals, eigvecs = scipy.linalg.eig(a)
print(eigvals)
print(w)



[4.+0.j 1.+0.j]
[4. 1.]


In [45]:
eigvals, eigvecs = la.eig(a)
print(eigvals)

[4.+0.j 1.+0.j]


In [46]:


print(np.linalg.norm(v[:,0]))
print(np.linalg.norm(v[:,1]))



0.9999999999999999
0.9999999999999999


In [47]:
np.dot(a,v[:,0])

array([2.82842712, 2.82842712])

In [48]:


print(np.allclose(np.dot(a,v[:,0]),np.dot(w[0],v[:,0])))



True


In [49]:
print(np.linalg.norm(v[:,0]))
print(np.linalg.norm(v[:,1]))


0.9999999999999999
0.9999999999999999


https://machinelearningmastery.com/introduction-to-eigendecomposition-eigenvalues-and-eigenvectors/

In [50]:
# confirm eigenvector
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# calculate eigendecomposition
values, vectors = eig(A)
values, vectors

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [51]:
# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


We can also divide one vector by another coordinate-wise, and find the constant vector of eigenvalue

In [52]:
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# calculate eigendecomposition
values, vectors = eig(A)
vec1 = vectors[:, 0]

In [53]:
mult = A @ vec1
mult

array([ -3.73863537,  -8.46653421, -13.19443305])

In [54]:
values[0]

16.116843969807043

In [55]:
mult / vec1

array([16.11684397, 16.11684397, 16.11684397])

In [56]:
# reconstruct matrix
from numpy import diag
from numpy import dot
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# calculate eigenvectors and eigenvalues
values, vectors = eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [58]:

import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
values, vectors = np.linalg.eig(A)
P = vectors
Pinv = np.linalg.inv(P)
D = np.diag(values)
new_A = P @ D @ Pinv
new_A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])