In [1]:
import numpy as np
from numpy.linalg import solve, det
from sklearn.linear_model import LinearRegression

In [2]:
# practice
A2 = np.array([[1, 1], [1, 2]])
# mt
# A2 = np.array([[1, 1], [1, 0]])
A2

array([[1, 1],
       [1, 2]])

In [3]:
# practice
b2 = np.array([[3], [5]])
# mt
# b2 = np.array([[2], [3]])

b2

array([[3],
       [5]])

In [4]:
solve(A2, b2)

array([[1.],
       [2.]])

In [5]:
# practice
A3 = np.array([[1, 1], [1, 2], [1, 3]])
# mt
# A3 = np.array([[1, 1], [1, 0], [1, -1]])
A3

array([[1, 1],
       [1, 2],
       [1, 3]])

In [6]:
# practice
b3 = np.array([[3], [5], [1]])
# mt
# b3 = np.array([[2], [3], [4]])
b3

array([[3],
       [5],
       [1]])

In [7]:
reg = LinearRegression(fit_intercept=False)
reg.fit(X=A3, y=b3)
reg.coef_

array([[ 5., -1.]])

In [8]:
AtA = A3.T @ A3
AtA

array([[ 3,  6],
       [ 6, 14]])

In [9]:
det(AtA)

6.0

In [10]:
AtAinv = np.linalg.inv(AtA)
AtAinv

array([[ 2.33333333, -1.        ],
       [-1.        ,  0.5       ]])

In [11]:
AtB = A3.T @ b3
AtB

array([[ 9],
       [16]])

In [12]:
solve(AtA, AtB)

array([[ 5.],
       [-1.]])

In [13]:
AtAinv @ AtB

array([[ 5.],
       [-1.]])

Tikhonov sustem formed by hand

In [14]:
AtATikhonov = AtA + 1 * np.eye(AtA.shape[0])
# np.array([[4, 6], [6, 15]])
AtATikhonov

array([[ 4.,  6.],
       [ 6., 15.]])

In [15]:
solve(AtATikhonov, AtB)

array([[1.625     ],
       [0.41666667]])

In [16]:
5/12

0.4166666666666667

In [17]:
13/8

1.625