In [ ]:
import numpy as np
from sympy.matrices import Matrix, GramSchmidt
from sympy import init_printing
init_printing()

#Sympy
stopped here

In [ ]:
L = [Matrix([2,3,5]), Matrix([3,6,2]), Matrix([8,3,6])]
out1 = GramSchmidt(L)
out2 = GramSchmidt(L, True)
L

⎡⎡2⎤  ⎡3⎤  ⎡8⎤⎤
⎢⎢ ⎥  ⎢ ⎥  ⎢ ⎥⎥
⎢⎢3⎥, ⎢6⎥, ⎢3⎥⎥
⎢⎢ ⎥  ⎢ ⎥  ⎢ ⎥⎥
⎣⎣5⎦  ⎣2⎦  ⎣6⎦⎦

In [ ]:
out1

⎡     ⎡ 23 ⎤  ⎡ 1692 ⎤⎤
⎢     ⎢ ── ⎥  ⎢ ──── ⎥⎥
⎢     ⎢ 19 ⎥  ⎢ 353  ⎥⎥
⎢⎡2⎤  ⎢    ⎥  ⎢      ⎥⎥
⎢⎢ ⎥  ⎢ 63 ⎥  ⎢-1551 ⎥⎥
⎢⎢3⎥, ⎢ ── ⎥, ⎢──────⎥⎥
⎢⎢ ⎥  ⎢ 19 ⎥  ⎢ 706  ⎥⎥
⎢⎣5⎦  ⎢    ⎥  ⎢      ⎥⎥
⎢     ⎢-47 ⎥  ⎢-423  ⎥⎥
⎢     ⎢────⎥  ⎢───── ⎥⎥
⎣     ⎣ 19 ⎦  ⎣ 706  ⎦⎦

In [ ]:
out2

⎡⎡ √38 ⎤  ⎡ 23⋅√6707 ⎤  ⎡ 12⋅√706 ⎤⎤
⎢⎢ ─── ⎥  ⎢ ──────── ⎥  ⎢ ─────── ⎥⎥
⎢⎢  19 ⎥  ⎢   6707   ⎥  ⎢   353   ⎥⎥
⎢⎢     ⎥  ⎢          ⎥  ⎢         ⎥⎥
⎢⎢3⋅√38⎥  ⎢ 63⋅√6707 ⎥  ⎢-11⋅√706 ⎥⎥
⎢⎢─────⎥, ⎢ ──────── ⎥, ⎢─────────⎥⎥
⎢⎢  38 ⎥  ⎢   6707   ⎥  ⎢   706   ⎥⎥
⎢⎢     ⎥  ⎢          ⎥  ⎢         ⎥⎥
⎢⎢5⋅√38⎥  ⎢-47⋅√6707 ⎥  ⎢-3⋅√706  ⎥⎥
⎢⎢─────⎥  ⎢──────────⎥  ⎢──────── ⎥⎥
⎣⎣  38 ⎦  ⎣   6707   ⎦  ⎣  706    ⎦⎦

-------------------------------


#Custom

In [ ]:


def gramschmidt(A):
    """
    Applies the Gram-Schmidt method to A
    and returns Q and R, so Q*R = A.
    """
    R = np.zeros((A.shape[1], A.shape[1]))
    Q = np.zeros(A.shape)
    for k in range(0, A.shape[1]):
        R[k, k] = np.sqrt(np.dot(A[:, k], A[:, k]))
        Q[:, k] = A[:, k]/R[k, k]
        for j in range(k+1, A.shape[1]):
            R[k, j] = np.dot(Q[:, k], A[:, j])
            A[:, j] = A[:, j] - R[k, j]*Q[:, k]
    return Q, R

def main():
    """
    Prompts for n and generates a random matrix.
    """
    #cols = int(input('give number of columns : '))
    #rows = int(input('give number of rows : '))
    cols = 3
    rows = 3
    A = np.random.rand(rows, cols)
    print('A = ')
    print(A)
    Q, R = gramschmidt(A)
    print('Q = ')
    print(Q)
    print('R = ')
    print(R)
    print('Q^T*Q = ')
    print(np.dot(Q.transpose(), Q))
    print('Q*R =')
    print(np.dot(Q, R))
    
main()

A = 
[[0.11576313 0.1222489  0.96952446]
 [0.09612772 0.34954598 0.68865963]
 [0.15499636 0.53036031 0.8153474 ]]
Q = 
[[ 0.5358858  -0.84199293  0.06224403]
 [ 0.44499037  0.34432685  0.82669377]
 [ 0.7175026   0.41531545 -0.55919862]]
R = 
[[ 0.21602202  0.60159095  1.41101517]
 [ 0.          0.23769219 -0.24058236]
 [ 0.          0.          0.17371659]]
Q^T*Q = 
[[1.00000000e+00 1.51801859e-16 7.92909887e-16]
 [1.51801859e-16 1.00000000e+00 1.61899625e-16]
 [7.92909887e-16 1.61899625e-16 1.00000000e+00]]
Q*R =
[[0.11576313 0.1222489  0.96952446]
 [0.09612772 0.34954598 0.68865963]
 [0.15499636 0.53036031 0.8153474 ]]
