In [364]:
import numpy as np
import pprint
import scipy
import scipy.linalg   # SciPy Linear Algebra Library. 
from sympy.matrices import Matrix
from sympy import init_printing
init_printing()

#Scipy

In [365]:
A = np.array([[12, -51, 4], 
              [6, 167, -68], 
              [-4, 24, -41]])  # From the Wikipedia Article on QR Decomposition
type(A)                 

numpy.ndarray

In [366]:
Q, R = scipy.linalg.qr(A)

print("A:")
pprint.pprint(A)

print("Q:")
pprint.pprint(Q)

print("R:")
pprint.pprint(R)

print("Q @ R:")
pprint.pprint(Q @ R)

A:
array([[ 12, -51,   4],
       [  6, 167, -68],
       [ -4,  24, -41]])
Q:
array([[-0.85714286,  0.39428571,  0.33142857],
       [-0.42857143, -0.90285714, -0.03428571],
       [ 0.28571429, -0.17142857,  0.94285714]])
R:
array([[ -14.,  -21.,   14.],
       [   0., -175.,   70.],
       [   0.,    0.,  -35.]])
Q @ R:
array([[ 12., -51.,   4.],
       [  6., 167., -68.],
       [ -4.,  24., -41.]])


##RQ

In [367]:
from scipy import linalg

r, q = linalg.rq(A)
np.allclose(A, r @ q)



True

In [368]:
r, q, A, r@q

(array([[  16.16949328,   39.90406135,  -30.11998297],
        [   0.        , -111.23411418,  142.04214812],
        [   0.        ,    0.        ,   47.67598976]]),
 array([[ 0.98336918, -0.09767694, -0.1531152 ],
        [-0.16107729, -0.85851594, -0.48683106],
        [-0.08389967,  0.50339804, -0.85997166]]),
 array([[ 12, -51,   4],
        [  6, 167, -68],
        [ -4,  24, -41]]),
 array([[ 12., -51.,   4.],
        [  6., 167., -68.],
        [ -4.,  24., -41.]]))

In [369]:
r.shape, q.shape


In [370]:
r2 = linalg.rq(A, mode='r')
np.allclose(r, r2)


True

In [371]:
r3, q3 = linalg.rq(A, mode='economic')
r3.shape, q3.shape


-------------------------------

#RQ from scipy QR

In [372]:
import numpy as np
from scipy.linalg import qr
 
def custom_rq(A):
    '''Implement rq decomposition using QR decomposition
 
    From Wikipedia,
     The RQ decomposition transforms a matrix A into the product of an upper triangular matrix R (also known as right-triangular) and an orthogonal matrix Q. The only difference from QR decomposition is the order of these matrices.
     QR decomposition is Gram-Schmidt orthogonalization of columns of A, started from the first column.
     RQ decomposition is Gram-Schmidt orthogonalization of rows of A, started from the last row.
    '''
    Q,R = qr(np.flipud(A).T)
    R = np.flipud(R.T)
    Q = Q.T

    return R[:,::-1],Q[::-1,:]



In [373]:
R, Q = custom_rq(A)
R, Q, R @ Q

(array([[ -16.16949328,   39.90406135,  -30.11998297],
        [   0.        , -111.23411418,  142.04214812],
        [   0.        ,    0.        ,   47.67598976]]),
 array([[-0.98336918,  0.09767694,  0.1531152 ],
        [-0.16107729, -0.85851594, -0.48683106],
        [-0.08389967,  0.50339804, -0.85997166]]),
 array([[ 12., -51.,   4.],
        [  6., 167., -68.],
        [ -4.,  24., -41.]]))

In [374]:
R, Q = linalg.rq(A)
R, Q, R @ Q

(array([[  16.16949328,   39.90406135,  -30.11998297],
        [   0.        , -111.23411418,  142.04214812],
        [   0.        ,    0.        ,   47.67598976]]),
 array([[ 0.98336918, -0.09767694, -0.1531152 ],
        [-0.16107729, -0.85851594, -0.48683106],
        [-0.08389967,  0.50339804, -0.85997166]]),
 array([[ 12., -51.,   4.],
        [  6., 167., -68.],
        [ -4.,  24., -41.]]))

In [375]:
Q, R = scipy.linalg.qr(A)
R, Q, Q @ R

(array([[ -14.,  -21.,   14.],
        [   0., -175.,   70.],
        [   0.,    0.,  -35.]]),
 array([[-0.85714286,  0.39428571,  0.33142857],
        [-0.42857143, -0.90285714, -0.03428571],
        [ 0.28571429, -0.17142857,  0.94285714]]),
 array([[ 12., -51.,   4.],
        [  6., 167., -68.],
        [ -4.,  24., -41.]]))

----------------------

#Numpy

In [376]:
import numpy.linalg

In [377]:
A = np.array([[0, 1], 
              [1, 1], 
              [1, 1], 
              [2, 1]])
A

array([[0, 1],
       [1, 1],
       [1, 1],
       [2, 1]])

In [378]:
q, r = np.linalg.qr(A)
q, r

(array([[ 0.        ,  0.8660254 ],
        [-0.40824829,  0.28867513],
        [-0.40824829,  0.28867513],
        [-0.81649658, -0.28867513]]), array([[-2.44948974, -1.63299316],
        [ 0.        ,  1.15470054]]))

In [379]:
q @ r

array([[0., 1.],
       [1., 1.],
       [1., 1.],
       [2., 1.]])

In [380]:
b = np.array([1, 0, 2, 1])
p = np.dot(q.T, b)
np.dot(np.linalg.inv(r), p)

array([1.10105035e-16, 1.00000000e+00])

---------------------

#Sympy

In [381]:
A = Matrix([[1,1,1],[1,1,3],[2,3,4]])
Q, R = A.QRdecomposition()
A, Q, R, (Q @ R)

⎛           ⎡√6  -√3   -√2 ⎤                             ⎞
⎜           ⎢──  ────  ────⎥  ⎡    4⋅√6      ⎤           ⎟
⎜           ⎢6    3     2  ⎥  ⎢√6  ────  2⋅√6⎥           ⎟
⎜⎡1  1  1⎤  ⎢              ⎥  ⎢     3        ⎥  ⎡1  1  1⎤⎟
⎜⎢       ⎥  ⎢√6  -√3    √2 ⎥  ⎢              ⎥  ⎢       ⎥⎟
⎜⎢1  1  3⎥, ⎢──  ────   ── ⎥, ⎢     √3       ⎥, ⎢1  1  3⎥⎟
⎜⎢       ⎥  ⎢6    3     2  ⎥  ⎢0    ──    0  ⎥  ⎢       ⎥⎟
⎜⎣2  3  4⎦  ⎢              ⎥  ⎢     3        ⎥  ⎣2  3  4⎦⎟
⎜           ⎢√6   √3       ⎥  ⎢              ⎥           ⎟
⎜           ⎢──   ──    0  ⎥  ⎣0    0     √2 ⎦           ⎟
⎝           ⎣3    3        ⎦                             ⎠

-----------------------------

#Custom householder vectorization & QR factorization

In [382]:
import numpy as np
from typing import Union

def householder_vectorized(a):
    """Use this version of householder to reproduce the output of np.linalg.qr 
    exactly (specifically, to match the sign convention it uses)

    based on https://rosettacode.org/wiki/QR_decomposition#Python
    """
    v = a / (a[0] + np.copysign(np.linalg.norm(a), a[0]))
    v[0] = 1
    tau = 2 / (v.T @ v)

    return v,tau

def qr_decomposition(A: np.ndarray) -> Union[np.ndarray, np.ndarray]:
    m,n = A.shape
    R = A.copy()
    Q = np.identity(m)

    for j in range(0, n):
        # Apply Householder transformation.
        v, tau = householder_vectorized(R[j:, j, np.newaxis])

        H = np.identity(m)
        H[j:, j:] -= tau * (v @ v.T)
        R = H @ R
        Q = H @ Q

    return Q[:n].T, np.triu(R[:n])

m = 5
n = 4

A = np.random.rand(m, n)
q, r = np.linalg.qr(A)
Q, R = qr_decomposition(A)

with np.printoptions(linewidth=9999, precision=10, suppress=True):
    print("**** Q from qr_decomposition")
    print(Q)
    print("**** Q from np.linalg.qr")
    print(q)
    print()

    print("**** R from qr_decomposition")
    print(R)

**** Q from qr_decomposition
[[-0.112208176  -0.7359577282  0.6615955478  0.0892607103]
 [-0.1895358295 -0.5465954473 -0.6459870536  0.0976067848]
 [-0.4127995858  0.269374783   0.3063260791 -0.4962695864]
 [-0.4696386828 -0.1942774765 -0.223359535  -0.6009059469]
 [-0.7486798409  0.2220205568  0.0355936679  0.6124818215]]
**** Q from np.linalg.qr
[[-0.112208176  -0.7359577282  0.6615955478  0.0892607103]
 [-0.1895358295 -0.5465954473 -0.6459870536  0.0976067848]
 [-0.4127995858  0.269374783   0.3063260791 -0.4962695864]
 [-0.4696386828 -0.1942774765 -0.223359535  -0.6009059469]
 [-0.7486798409  0.2220205568  0.0355936679  0.6124818215]]

**** R from qr_decomposition
[[-1.0044620445 -1.298627076  -1.155899706  -0.7144479427]
 [ 0.           -0.8298805896 -0.5755889736 -0.6742183507]
 [ 0.            0.           -0.5234541671  0.6377977223]
 [ 0.            0.            0.           -0.5388696276]]
