In [16]:
# https://towardsdatascience.com/singular-value-decomposition-example-in-python-dab2507d85a0

# Pseudoinverse

In [17]:
import numpy as np
from numpy import array
from numpy.linalg import pinv, inv
from numpy.linalg import svd
from numpy import zeros
from numpy import diag

In [18]:
import numpy as np
from numpy.linalg import inv
A = np.array([
	[0, 2],
	[0, 0],
	[1, 0]])

ApinvByHand = inv(A.T @ A) @ A.T
ApinvByHand


array([[0. , 0. , 1. ],
       [0.5, 0. , 0. ]])

In [19]:
Apinv = pinv(A)
Apinv

array([[0. , 0. , 1. ],
       [0.5, 0. , 0. ]])

In [31]:
import numpy as np
from numpy.linalg import pinv, inv
from numpy.linalg import svd

A = np.array([
	[0, 2],
	[0, 0],
	[1, 0]])

U, s, VT = svd(A)
# d = 1.0 / s
D = np.zeros(A.shape)
D[:A.shape[1], :A.shape[1]] = np.diag(s)
ApinvBySvd = VT.T.dot(D.T).dot(U.T)

Apinv = pinv(A)

np.allclose(ApinvBySvd, Apinv)

False

In [21]:

A = array([
	[0.1, 0.2],
	[0.3, 0.4],
	[0.5, 0.6],
	[0.7, 0.8]])

#A = array([[1, 2], [2, 3], [5, 6]])
Apinv = pinv(A)
print(Apinv)

[[-1.00000000e+01 -5.00000000e+00  1.42385628e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


By hand first

In [22]:
ApinvByHand = inv(A.T @ A) @ A.T
ApinvByHand

array([[-1.0000000e+01, -5.0000000e+00,  5.6177285e-15,  5.0000000e+00],
       [ 8.5000000e+00,  4.5000000e+00,  5.0000000e-01, -3.5000000e+00]])

In [23]:
np.isclose(ApinvByHand, Apinv)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Pseudoinverse via SVD

In [24]:
# calculate svd
U, s, VT = svd(A)
print('U= ', U)
print('s= ', s)
print('VT= ', VT)
# reciprocals of s
d = 1.0 / s
# create m x n D matrix
D = zeros(A.shape)
# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = diag(d)
print('D= ', D)
# calculate pseudoinverse
ApinvBySvd = VT.T.dot(D.T).dot(U.T)
print(ApinvBySvd)

U=  [[-0.15248323 -0.82264747 -0.39450102 -0.37995913]
 [-0.34991837 -0.42137529  0.24279655  0.80065588]
 [-0.54735351 -0.0201031   0.69790998 -0.46143436]
 [-0.74478865  0.38116908 -0.5462055   0.04073761]]
s=  [1.42690955 0.06268282]
VT=  [[-0.64142303 -0.7671874 ]
 [ 0.7671874  -0.64142303]]
D=  [[ 0.70081527  0.        ]
 [ 0.         15.95333376]
 [ 0.          0.        ]
 [ 0.          0.        ]]
[[-1.00000000e+01 -5.00000000e+00  1.42578328e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [25]:
np.isclose(ApinvBySvd, Apinv)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Rank 1 approximation

In [26]:
S = zeros(A.shape)
S[0][0] = s[0]
S

array([[1.42690955, 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ]])

In [27]:
Aapprox = U @ S @ VT
Aapprox

array([[0.13956068, 0.16692447],
       [0.32026372, 0.3830581 ],
       [0.50096675, 0.59919173],
       [0.68166978, 0.81532536]])

In [28]:
# check that the columns of Aapprox are proportional, thus, linear dependent
Aapprox[:, 0] / Aapprox[:, 1]

array([0.83607086, 0.83607086, 0.83607086, 0.83607086])

In [29]:
np.linalg.matrix_rank(A)

2

In [30]:
np.linalg.matrix_rank(Aapprox)

1