In [1]:
import numpy as np

In [2]:
def power_iteration(A, x_k, num_iterations: int):
    x_k_norm = np.linalg.norm(x_k)
    x_k = x_k / x_k_norm

    for iteration in range(num_iterations):
        # calculate the matrix-by-vector product Ab
        
        x_k1 = np.dot(A, x_k)
        
        # calculate the norm
        x_k1_norm = np.linalg.norm(x_k1)

        # re normalize the vector
        x_k = x_k1 / x_k1_norm

        #print("iteration: ", iteration, ", x_k = ", x_k)
        #print("l2 norm of Ax_k: ", x_k1_norm)
        numerator = x_k.T @ A @ x_k
        denominator = x_k.T @ x_k
        lambda_k = numerator / denominator
        #print("lambda_k = ", lambda_k)
        #print()
    return lambda_k, x_k

In [3]:
def deflation(AP):
  n = AP.shape[1]
  Eigvals = []
  Eigvecs = [[]*1]*n
  # Here draw a result on each deflationStage
  for deflationStage in range(n):
    v = (np.random.rand(n) - 1/2)*10 # generate random vector
    # Draw this vector: eigvect
    # Think, how to show eigval
    eigval, eigvect = power_iteration(AP, v, 10) # run power iteration to reveal eigenvalue lambda_k and eigenvecor x_k
    eigvect = eigvect.reshape((n,1))
    Eigvals.append(eigval)
    Eigvecs = np.hstack((Eigvecs, eigvect))
    #print(f"eigval= {eigval}\n eigvect={eigvect}\n")
    AP = AP @ (np.eye(n) - eigvect @ eigvect.T) # update A
  return Eigvals, Eigvecs

In [4]:
# A = np.array([[10, 12], [12, 3]])
A = np.array([[1, 2, 3], 
              [2, 4, -5], 
              [3, -5, 1]])
eigenvalues, eigenvectors = deflation(A)
print(f"eigenvalues:\n{eigenvalues}\neigenvectors:\n {eigenvectors}\n")

eigenvalues:
[7.726347424106021, -4.913440975721425, 3.187093551615404]
eigenvectors:
 [[-0.03572909  0.51817267  0.85124486]
 [ 0.79632312 -0.50845029  0.34100966]
 [-0.6038153  -0.68773206  0.39886665]]



In [5]:
np.linalg.eigh(A)

(array([-4.91362227,  3.18714811,  7.72647417]),
 array([[-0.5202283 ,  0.85335319,  0.03392401],
        [ 0.5036228 ,  0.33861889, -0.7947964 ],
        [ 0.68972936,  0.39639068,  0.60592726]]))

In [6]:
def deflation(AP):
    n = AP.shape[1]
    Eigvals = []
    Eigvecs = [[]*1]*n
    for deflationStage in range(n):
        v = (np.random.rand(n) - 1/2)*10 
        eigval, eigvect = power_iteration(AP, v, 10) 
        eigvect = eigvect.reshape((n,1))
        Eigvals.append(eigval)
        Eigvecs = np.hstack((Eigvecs, eigvect))
        AP = AP @ (np.eye(n) - eigvect @ eigvect.T)
    return Eigvals, Eigvecs

In [7]:
# A = np.array([[10, -7], [12, 3]])
A = np.array([[1, 12, 17], 
              [2, 4, 5], 
              [13, -15, 1]])
eigenvalues, eigenvectors = deflation(A)
eigenvalues, eigenvectors

([4.683352522820896, 3.2560082863385733, -1.9393608091594536],
 array([[-0.95293771, -0.94502087, -0.95710234],
        [-0.30218798, -0.28083359, -0.28386554],
        [ 0.02433398, -0.16753523, -0.05809879]]))

Final practice.

Deflation by orthogonal projection

In [8]:
def power_iteration(M):
    x_k = (np.random.rand(M.shape[1]) - 1/2)*10
    x_k_norm = np.linalg.norm(x_k)
    x_k = x_k / x_k_norm
    for iteration in range(10):
        x_k1 = np.dot(M, x_k)
        x_k1_norm = np.linalg.norm(x_k1)
        x_k = x_k1 / x_k1_norm
        lambda_k = x_k.T @ M @ x_k
        # There is no denominator because our vectors are of unit length. 
    return lambda_k, x_k

In [9]:
# symmetric matrix
A = np.array([[3, 7], [7, 3]]) # true eigenvalues 10, -4
eigval1, eigvect1 = power_iteration(A)
eigval1, eigvect1

(9.999999767514193, array([0.70701565, 0.7071979 ]))

In [10]:
from math import sqrt
1 / sqrt(2)

0.7071067811865475

In [11]:
eigvect1 = eigvect1.reshape((2,1))

In [12]:
P1 = eigvect1 @ eigvect1.T
P1

array([[0.49987114, 0.49999998],
       [0.49999998, 0.50012886]])

In [13]:
P1_ort = np.eye(2) - P1
P1_ort

array([[ 0.50012886, -0.49999998],
       [-0.49999998,  0.49987114]])

In [14]:
A1 = A @ P1_ort
A1

array([[-1.99961329,  1.999098  ],
       [ 2.0009021 , -2.00038648]])

In [15]:
power_iteration(A1)

(-3.999999767514194, array([ 0.70687894, -0.70733455]))

In [16]:
# round of the elements of A1
A1 = np.array([[-2, 2], [2, -2]])
power_iteration(A1)

(-4.000000000000001, array([-0.70710678,  0.70710678]))

Deflation by Householder transformation

In [17]:
A = np.array([[-10, -9], [12, 11]]) # true eigenvalues 2, -1
power_iteration(A)

(2.0023448675157045, array([-0.59991067,  0.80006699]))

In [18]:
# Round it up to make the values exact just in case
x = np.array([[-0.6], [0.8]])
# Householder defining vector
v = x - np.array([[1], [0]])
v

array([[-1.6],
       [ 0.8]])

In [19]:
v @ v.T

array([[ 2.56, -1.28],
       [-1.28,  0.64]])

In [20]:
(v.T @ v)

array([[3.2]])

In [21]:
H = np.eye(2) - 2 * v @ v.T /(v.T @ v)
H

array([[-0.6,  0.8],
       [ 0.8,  0.6]])

In [22]:
A1 = H @ A @ H
A1
# should be upper triangular
# But due to computation errors, h21 = -1.59872116e-16 =almost 0

array([[ 2.00000000e+00,  2.10000000e+01],
       [-1.59872116e-16, -1.00000000e+00]])

In [23]:
# y is an eigenvector of A1, corresponding to eigenvalue -1
# The computation is done by hand
# The algorithm's presentation in Solomon's texbook
# does not deal with vectors at all. 
# So this is my add-on. 
# On the first step, the eigenvector of Ai is relatively easy to compute
# becaue it is of the same length as the original. 
# The later ones will be shorter. 
y = np.array([[7], [-1]])
x2 =  H @ y
x2

array([[-5.],
       [ 5.]])

In [24]:
A @ x2

array([[ 5.],
       [-5.]])