In [1]:
import numpy as np

In [2]:
def power_iteration(A, x_k, num_iterations: int):
    x_k_norm = np.linalg.norm(x_k)
    x_k = x_k / x_k_norm

    for iteration in range(num_iterations):
        # calculate the matrix-by-vector product Ab
        
        x_k1 = np.dot(A, x_k)
        
        # calculate the norm
        x_k1_norm = np.linalg.norm(x_k1)

        # re normalize the vector
        x_k = x_k1 / x_k1_norm

        #print("iteration: ", iteration, ", x_k = ", x_k)
        #print("l2 norm of Ax_k: ", x_k1_norm)
        numerator = x_k.T @ A @ x_k
        denominator = x_k.T @ x_k
        lambda_k = numerator / denominator
        #print("lambda_k = ", lambda_k)
        #print()
    return lambda_k, x_k

In [3]:
def deflation(AP):
  n = AP.shape[1]
  Eigvals = []
  Eigvecs = [[]*1]*n
  # Here draw a result on each deflationStage
  for deflationStage in range(n):
    v = (np.random.rand(n) - 1/2)*10 # generate random vector
    # Draw this vector: eigvect
    # Think, how to show eigval
    eigval, eigvect = power_iteration(AP, v, 10) # run power iteration to reveal eigenvalue lambda_k and eigenvecor x_k
    eigvect = eigvect.reshape((n,1))
    Eigvals.append(eigval)
    Eigvecs = np.hstack((Eigvecs, eigvect))
    #print(f"eigval= {eigval}\n eigvect={eigvect}\n")
    AP = AP @ (np.eye(n) - eigvect @ eigvect.T) # update A
  return Eigvals, Eigvecs

In [4]:
# A = np.array([[10, 12], [12, 3]])
A = np.array([[1, 2, 3], 
              [2, 4, -5], 
              [3, -5, 1]])
eigenvalues, eigenvectors = deflation(A)
print(f"eigenvalues:\n{eigenvalues}\neigenvectors:\n {eigenvectors}\n")

eigenvalues:
[7.7242081034666406, -4.911345950586856, 3.1871378471202156]
eigenvectors:
 [[-0.02737569 -0.51837253  0.85237588]
 [ 0.78781741  0.48719163  0.34043965]
 [-0.61530017  0.70280455  0.39693351]]



In [5]:
np.linalg.eigh(A)

(array([-4.91362227,  3.18714811,  7.72647417]),
 array([[-0.5202283 ,  0.85335319,  0.03392401],
        [ 0.5036228 ,  0.33861889, -0.7947964 ],
        [ 0.68972936,  0.39639068,  0.60592726]]))

# old draft of code

In [6]:
# A = np.array([[10, 12], [12, 3]])
A = np.array([[1, 2, 3], 
              [2, 4, -5], 
              [3, -5, 1]])
AP = A
n = A.shape[1]

Eigvals = []
# Eigvecs = [[], []]
#Eigvecs = [[], [], []]
Eigvecs = [[]*1]*n

for deflationStage in range(n):
  v = (np.random.rand(n) - 1/2)*10 
  eigval, eigvect = power_iteration(AP, v, 10)
  Eigvals.append(eigval)
  eigvect = eigvect.reshape((n,1))
  Eigvecs = np.hstack((Eigvecs, eigvect))
  print(f"eigval= {eigval}\n eigvect={eigvect}\n")
  AP = A @ (np.eye(n) - Eigvecs @ Eigvecs.T)

eigval= 7.7257281728454394
 eigvect=[[-0.03788052]
 [ 0.79865741]
 [-0.60059255]]

eigval= -4.912876241881893
 eigvect=[[ 0.52066325]
 [-0.51316181]
 [-0.68233037]]

eigval= 3.187148068331452
 eigvect=[[-0.85341735]
 [-0.33847822]
 [-0.39637271]]

