In [16]:
import numpy as np
from numpy.linalg import solve, det
from sklearn.linear_model import LinearRegression

In [17]:
# practice
A2 = np.array([[1, 1], [1, 2]])
# mt
# A2 = np.array([[1, 1], [1, 0]])
A2

array([[1, 1],
       [1, 2]])

In [18]:
# practice
b2 = np.array([[3], [5]])
# mt
# b2 = np.array([[2], [3]])

b2

array([[3],
       [5]])

In [19]:
solve(A2, b2)

array([[1.],
       [2.]])

In [20]:
# practice
A3 = np.array([[1, 1], [1, 2], [1, 3]])
# mt
# A3 = np.array([[1, 1], [1, 0], [1, -1]])
A3

array([[1, 1],
       [1, 2],
       [1, 3]])

In [21]:
# practice
b3 = np.array([[3], [5], [1]])
# mt
# b3 = np.array([[2], [3], [4]])
b3

array([[3],
       [5],
       [1]])

In [22]:
reg = LinearRegression(fit_intercept=False)
reg.fit(X=A3, y=b3)
reg.coef_

array([[ 5., -1.]])

In [23]:
AtA = A3.T @ A3
AtA

array([[ 3,  6],
       [ 6, 14]])

In [24]:
det(AtA)

6.0

In [25]:
AtAinv = np.linalg.inv(AtA)
AtAinv

array([[ 2.33333333, -1.        ],
       [-1.        ,  0.5       ]])

In [26]:
AtB = A3.T @ b3
AtB

array([[ 9],
       [16]])

In [27]:
solve(AtA, AtB)

array([[ 5.],
       [-1.]])

In [28]:
AtAinv @ AtB

array([[ 5.],
       [-1.]])

Tikhonov

In [29]:
AtATikhonov = np.array([[4, 6], [6, 15]])
AtATikhonov

array([[ 4,  6],
       [ 6, 15]])

In [30]:
solve(AtATikhonov, AtB)

array([[1.625     ],
       [0.41666667]])

In [31]:
5/12

0.4166666666666667

In [32]:
13/8

1.625