In [19]:
import pprint
import numpy as np
import scipy
import scipy.linalg   # SciPy Linear Algebra Library

#Cholesky 2 by 2 other numbers

In [20]:
A = np.array([[9, 3], [3, 17]])
L = scipy.linalg.cholesky(A, lower=True)
L

array([[3., 0.],
       [1., 4.]])

In [21]:
L @ L.T

array([[ 9.,  3.],
       [ 3., 17.]])

In [22]:
E1 = np.array([[1/3, 0], [-1/3, 1]])
E1 @ A

array([[ 3.,  1.],
       [ 0., 16.]])

In [23]:
E1 @ A @ E1.T

array([[ 1.,  0.],
       [ 0., 16.]])

In [24]:
E2 = np.array([[1, 0], [0, 1/4]])
E2 @ E1 @ A @ E1.T

array([[1., 0.],
       [0., 4.]])

In [25]:
E2 @ E1 @ A @ E1.T @ E2.T

array([[1., 0.],
       [0., 1.]])

In [26]:
L = np.linalg.inv(E1) @ np.linalg.inv(E2)
L

array([[3., 0.],
       [1., 4.]])

In [27]:
L @ L.T

array([[ 9.,  3.],
       [ 3., 17.]])

#Matrix condition old draft

##1. Compute the norm of A

In [28]:
A = np.array([[1, 2], [-3, 4]])
np.linalg.norm(A, ord=1)

6.0

##2. Find a determinant of A = a11*a22 - a12*a21

In [29]:
np.linalg.det(A)

10.000000000000002

##3. Find an inverse A^{-1}


In [30]:
np.linalg.inv(A)

array([[ 0.4, -0.2],
       [ 0.3,  0.1]])

##4. Find a norm of the inverse

In [31]:
np.linalg.norm(np.linalg.inv(A), ord=1)

0.7000000000000001

##5. Find the relative condition number 

In [32]:
np.linalg.cond(A, p=1)

4.2

#Matrix condition clean

##Q2

In [33]:
x = np.array([1, 2])
np.linalg.norm(x, ord=1)

3.0

##Q4

In [34]:
A = np.array([[1, 2], [-3, 4]])
np.linalg.norm(A, ord=1)

6.0

##Q5

In [40]:
A @ x

array([5, 5])

##Q6

In [35]:
np.linalg.norm(A @ x, ord=1)

10.0

##Q8

In [36]:
np.linalg.det(A)

10.000000000000002

##Q9

In [37]:
np.linalg.inv(A)

array([[ 0.4, -0.2],
       [ 0.3,  0.1]])

##Q10

In [38]:
np.linalg.norm(np.linalg.inv(A), ord=1)

0.7000000000000001

##Q11

In [39]:
np.linalg.cond(A, p=1)

4.2