In [29]:
from sklearn.linear_model import Ridge
import numpy as np
n_samples, n_features = 3, 2
rng = np.random.RandomState(0)
y = rng.randn(n_samples)
y

array([1.76405235, 0.40015721, 0.97873798])

In [30]:
X = rng.randn(n_samples, n_features)
X

array([[ 2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842],
       [-0.15135721, -0.10321885]])

In [31]:
reg = Ridge(alpha=1.0)
reg.fit(X, y)
reg

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [32]:
reg.coef_

array([ 0.34827615, -0.02011512])

In [33]:
reg.intercept_

0.9367251972689119

Now basic regression with the same data. With no regularization

In [34]:
from sklearn.linear_model import LinearRegression
linReg = LinearRegression()
linReg.fit(X, y)
linReg.coef_

array([ 0.47436778, -0.17733725])

In [35]:
linReg.intercept_

1.0322324192886838

In [36]:
linReg.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': False}

In [37]:
linReg.rank_

2

In [38]:
linReg.score(X, y)

1.0