In [6]:
import numpy as np
a = np.array([[3, 1], [2, 2]])
w, v = np.linalg.eig(a)
print(w)
print(v)

[4. 1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


How does dot differ from *?

In [7]:
np.dot(a, v) == w*v

array([[ True, False],
       [ True,  True]])

In [9]:
w*v

array([[ 2.82842712, -0.4472136 ],
       [ 2.82842712,  0.89442719]])

In [10]:
np.dot(a, v)

array([[ 2.82842712, -0.4472136 ],
       [ 2.82842712,  0.89442719]])

In [11]:
np.array_equal(np.dot(a, v), (w*v))

False

In [12]:
# !!!!
np.allclose(np.dot(a, v), w*v)

True

In [13]:
np.isclose(np.dot(a, v), w*v)

array([[ True,  True],
       [ True,  True]])