In [21]:
import pprint
import scipy
import scipy.linalg   # SciPy Linear Algebra Library

A = scipy.array([[12, -51, 4], 
                 [6, 167, -68], 
                 [-4, 24, -41]])  # From the Wikipedia Article on QR Decomposition
Q, R = scipy.linalg.qr(A)

print("A:")
pprint.pprint(A)

print("Q:")
pprint.pprint(Q)

print("R:")
pprint.pprint(R)

A:
array([[ 12, -51,   4],
       [  6, 167, -68],
       [ -4,  24, -41]])
Q:
array([[-0.85714286,  0.39428571,  0.33142857],
       [-0.42857143, -0.90285714, -0.03428571],
       [ 0.28571429, -0.17142857,  0.94285714]])
R:
array([[ -14.,  -21.,   14.],
       [   0., -175.,   70.],
       [   0.,    0.,  -35.]])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  import sys


In [22]:
import numpy as np
from typing import Union

def householder_vectorized(a):
    """Use this version of householder to reproduce the output of np.linalg.qr 
    exactly (specifically, to match the sign convention it uses)

    based on https://rosettacode.org/wiki/QR_decomposition#Python
    """
    v = a / (a[0] + np.copysign(np.linalg.norm(a), a[0]))
    v[0] = 1
    tau = 2 / (v.T @ v)

    return v,tau

def qr_decomposition(A: np.ndarray) -> Union[np.ndarray, np.ndarray]:
    m,n = A.shape
    R = A.copy()
    Q = np.identity(m)

    for j in range(0, n):
        # Apply Householder transformation.
        v, tau = householder_vectorized(R[j:, j, np.newaxis])

        H = np.identity(m)
        H[j:, j:] -= tau * (v @ v.T)
        R = H @ R
        Q = H @ Q

    return Q[:n].T, np.triu(R[:n])

m = 5
n = 4

A = np.random.rand(m, n)
q, r = np.linalg.qr(A)
Q, R = qr_decomposition(A)

with np.printoptions(linewidth=9999, precision=20, suppress=True):
    print("**** Q from qr_decomposition")
    print(Q)
    print("**** Q from np.linalg.qr")
    print(q)
    print()

    print("**** R from qr_decomposition")
    print(R)

**** Q from qr_decomposition
[[-0.5120769175299396     0.200332132557029     -0.4140535425334816     0.7222332137311531   ]
 [-0.5843354199421819    -0.006561468750364628  -0.0019067439362148973 -0.34471755960572964  ]
 [-0.006561202971743249  -0.3914353893696662    -0.8155975911261651    -0.3814483205507203   ]
 [-0.4521344421040087     0.5060636126209693     0.10518302092952729   -0.4538665151272906   ]
 [-0.43801911420951717   -0.7419581792277934     0.3902475236313119     0.08972933900505403  ]]
**** Q from np.linalg.qr
[[-0.5120769175299393    0.20033213255702942  -0.41405354253348153   0.7222332137311532  ]
 [-0.5843354199421817   -0.006561468750364688 -0.001906743936214983 -0.34471755960572975 ]
 [-0.006561202971743248 -0.3914353893696662   -0.8155975911261651   -0.38144832055072025 ]
 [-0.45213444210400855   0.506063612620969     0.10518302092952757  -0.45386651512729104 ]
 [-0.43801911420951706  -0.7419581792277935    0.3902475236313118    0.08972933900505428 ]]

**** R from q