In [ ]:
import numpy as np

A = np.array([[3,4,3],[1,2,3],[4,2,1]])
U, S, VH = np.linalg.svd(A)


In [ ]:
#Performing SVD
U, S, VH = np.linalg.svd(A)
U

array([[-0.73553325, -0.18392937, -0.65204358],
       [-0.42657919, -0.62196982,  0.65664582],
       [-0.52632788,  0.76113306,  0.37901904]])

In [ ]:
S

array([7.87764972, 2.54031671, 0.69958986])

In [ ]:
VH

array([[-0.60151068, -0.61540527, -0.5093734 ],
       [ 0.73643349, -0.18005275, -0.65210944],
       [ 0.30959751, -0.76737042,  0.5615087 ]])

In [ ]:
#Checking if we can remake the original matrix using U,D,VT
A_remake = (U @ np.diag(S) @ VH)
print(A_remake)

[[3. 4. 3.]
 [1. 2. 3.]
 [4. 2. 1.]]


In [ ]:
A_remake = (U @ S @ VH)
print(A_remake)

[0.13779496 6.43541178 5.25037978]


In [ ]:
A_remake = (np.diag(S) @ U @ VH)
print(A_remake)

[[ 8.28006336e-01  7.76836292e+00  1.01208110e+00]
 [ 4.69562559e-03 -3.28676669e-01  2.51895982e+00]
 [ 6.95713475e-01 -7.27483579e-02 -1.07891748e-02]]


The above equality gives rise to a question. 

Pack it up densely. Remove intermediate names.

Several questions. All 3 equal. 

# SVD computation
Exaple fron slides

In [ ]:
A =np.array([[1, 2], [2, 3], [5,6]])
A

array([[1, 2],
       [2, 3],
       [5, 6]])

Step 1.

$A^TA$.

In [ ]:
AtA = A.T @ A
AtA

array([[30, 38],
       [38, 49]])

Step 2.

Eigenvalues and eigenvecttors of $A^TA$.

In [ ]:
eigval, eigvect = np.linalg.eigh(AtA)
eigval, eigvect

(array([ 0.33049656, 78.66950344]), array([[-0.78820544,  0.61541221],
        [ 0.61541221,  0.78820544]]))

Step 4.

Right singular vectors and matrix $V^T$

In [ ]:
v1 = eigvect[:,0].reshape(2,1)
v2 = eigvect[:,1].reshape(2,1)
v1, v2

(array([[-0.78820544],
        [ 0.61541221]]), array([[0.61541221],
        [0.78820544]]))

In [ ]:
Vt = np.hstack((v2, v1)).T
Vt

array([[ 0.61541221,  0.78820544],
       [-0.78820544,  0.61541221]])

Step 5.

Singular values of $A$.

In [ ]:
singular_values=np.sqrt(eigval)
singular_values

array([0.5748883 , 8.86958305])

Step 6.

Diaginal mattrix $S$.

In [ ]:
S = np.zeros((3,2))
S[0,0] = singular_values[1]
S[1,1] = singular_values[0]
S

array([[8.86958305, 0.        ],
       [0.        , 0.5748883 ],
       [0.        , 0.        ]])

Step 7.

Left singular vectors, corresponding to non-zero singular vvalues.

In [ ]:
#u1 = A @ np.array([[-0.615], [-0.788]]) / 8.87
u1 = A @ v1 / singular_values[0]
u1

array([[ 0.76992171],
       [ 0.46935336],
       [-0.4323517 ]])

In [ ]:
#u2 = np.array([[1, 2], [2, 3], [5,6]]) @ np.array([[-0.788], [0.615]]) / 0.575
u2 = A @ v2 / singular_values[1]
u2

array([[0.24711681],
       [0.4053675 ],
       [0.88011958]])

In [ ]:
u1.T @ u2

array([[2.22044605e-16]])

Step 8.

The rest of left singular vectors.

In [ ]:
Proj = np.eye(3) - u1 @ u1.T - u2 @ u2.T
Proj

array([[ 0.34615385, -0.46153846,  0.11538462],
       [-0.46153846,  0.61538462, -0.15384615],
       [ 0.11538462, -0.15384615,  0.03846154]])

In [ ]:
y = np.array([[1], [2], [3]])
y_projected = Proj @ y
u3 = y_projected / np.linalg.norm(y_projected)
u3

array([[-0.58834841],
       [ 0.78446454],
       [-0.19611614]])

In [ ]:
u1.T @ u3

array([[-7.72992781e-15]])

Step 9.

Matrix $U$.

In [ ]:
U = np.hstack((u2, u1, u3))
U

array([[ 0.24711681,  0.76992171, -0.58834841],
       [ 0.4053675 ,  0.46935336,  0.78446454],
       [ 0.88011958, -0.4323517 , -0.19611614]])

Verification

In [ ]:
U @ S @ Vt

array([[1., 2.],
       [2., 3.],
       [5., 6.]])

In [ ]:
np.isclose(A, U @ S @ Vt)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

# End SVD computation