In [352]:
import numpy as np

In [353]:
A = np.array([
              [1, 2], 
              [3, 4]
])
B = np.array([
              [5, 6], 
              [7, 8]
])


In [354]:
ABdirectly = A @ B
ABdirectly

array([[19, 22],
       [43, 50]])

Self-made outer

In [355]:
outer1 = A[:, 0].reshape(2, 1) @ B[0, :].reshape(1, 2)
outer1

array([[ 5,  6],
       [15, 18]])

In [356]:
outer2 = A[:, 1].reshape(2, 1) @ B[1, :].reshape(1, 2)
outer2

array([[14, 16],
       [28, 32]])

In [357]:
ABbyOuterSum = outer1 + outer2
ABbyOuterSum

array([[19, 22],
       [43, 50]])

In [358]:
ABdirectly == ABbyOuterSum

array([[ True,  True],
       [ True,  True]])

By library outer

In [359]:
outer1 = np.outer(A[:, 0], B[0, :])
outer1

array([[ 5,  6],
       [15, 18]])

In [360]:
outer2 = np.outer(A[:, 1], B[1, :])
outer2

array([[14, 16],
       [28, 32]])

In [361]:
ABbyOuterSum = outer1 + outer2
ABbyOuterSum

array([[19, 22],
       [43, 50]])

In [362]:
ABdirectly == ABbyOuterSum

array([[ True,  True],
       [ True,  True]])

3 matrices - any * diag * any

A * D * B

In [363]:
A = np.array([
              [1, 2], 
              [3, 4]
])
B = np.array([
              [5, 6], 
              [7, 8]
])
D = np.diag([10, 20])
D

array([[10,  0],
       [ 0, 20]])

In [364]:
ADBdirect = A @ D @ B
ADBdirect

array([[330, 380],
       [710, 820]])

In [365]:
outer1 = np.outer(A[:, 0], B[0, :])
outer1

array([[ 5,  6],
       [15, 18]])

In [366]:
outer2 = np.outer(A[:, 1], B[1, :])
outer2

array([[14, 16],
       [28, 32]])

In [367]:
ADBbyOuterWeightedSum = D[0, 0] * outer1  + D[1, 1] * outer2
ADBbyOuterWeightedSum

array([[330, 380],
       [710, 820]])

In [368]:
ADBbyOuterWeightedSum == ADBdirect

array([[ True,  True],
       [ True,  True]])

Apply it to SVD

In [369]:
C = np.array([
              [10, 20], 
              [30, 40]
])
U, s, Vt = np.linalg.svd(C)
U

array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]])

In [370]:
s

array([54.64985704,  3.65966191])

In [371]:
Vt

array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]])

In [372]:
Crecovered = U @ np.diag(s) @ Vt
# Arecovered

In [373]:
# Crecovered = Crecovered.astype(int)

In [374]:
Crecovered, C

(array([[10., 20.],
        [30., 40.]]), array([[10, 20],
        [30, 40]]))

In [375]:
np.isclose(Crecovered, C)

array([[ True,  True],
       [ True,  True]])

Recovery using weighted sum of outer product

In [376]:
outer1 = np.outer(U[:, 0], Vt[0, :])
outer1

array([[0.23304246, 0.3306884 ],
       [0.52680453, 0.74753822]])

In [377]:
outer2 = np.outer(U[:, 1], Vt[1, :])
outer2

array([[-0.74753822,  0.52680453],
       [ 0.3306884 , -0.23304246]])

In [378]:
CbyOuterWeightedSum = s[0] * outer1  + s[1] * outer2
CbyOuterWeightedSum

array([[10., 20.],
       [30., 40.]])

In [379]:
np.isclose(CbyOuterWeightedSum, C)

array([[ True,  True],
       [ True,  True]])

full_matrices=False

In [380]:
# A = np.array([
#               [1, 2, 4], 
#               [3, 4, 7],
#               [8, 0, 5]])

# A = np.array([
#               [1, 2], 
#               [3, 4],
#               [8, 0]])

A = np.array([
              [1, 2, 4], 
              [3, 4, 7]])
A

array([[1, 2, 4],
       [3, 4, 7]])

In [381]:
u, s, vh = np.linalg.svd(A)
u.shape, s.shape, vh.shape

((2, 2), (2,), (3, 3))

In [382]:
u, s, vh

(array([[-0.46796371, -0.88374768],
        [-0.88374768,  0.46796371]]),
 array([9.72889264, 0.59046418]),
 array([[-0.32061272, -0.45955057, -0.8282637 ],
        [ 0.88090599,  0.17674138, -0.43905253],
        [ 0.34815531, -0.87038828,  0.34815531]]))

In [383]:
u, s, vh = np.linalg.svd(A, full_matrices=False)
u.shape, s.shape, vh.shape

((2, 2), (2,), (2, 3))

In [384]:
u, s, vh

(array([[-0.46796371, -0.88374768],
        [-0.88374768,  0.46796371]]),
 array([9.72889264, 0.59046418]),
 array([[-0.32061272, -0.45955057, -0.8282637 ],
        [ 0.88090599,  0.17674138, -0.43905253]]))

matrix product function

In [385]:
A = np.array([
              [1, 2], 
              [3, 4]
])
B = np.array([
              [5, 6], 
              [7, 8]
])
A.ndim

2

In [386]:
A[:, 0]

array([1, 3])

In [387]:
A[:, 0].reshape(2, 1)

array([[1],
       [3]])

In [388]:
A[:, 0].reshape(-1, 1)

array([[1],
       [3]])

In [389]:
B[0, :]

array([5, 6])

In [390]:
B[0, :].reshape(1, 2)

array([[5, 6]])

In [391]:
A[:, 0].reshape(-1, 1) @ B[0, :].reshape(1, 2)

array([[ 5,  6],
       [15, 18]])

In [392]:
outer1 = A[:, 0].reshape(2, 1) @ B[0, :].reshape(1, 2)
outer1



array([[ 5,  6],
       [15, 18]])

In [393]:
outer2 = A[:, 1].reshape(2, 1) @ B[1, :].reshape(1, 2)
outer2



array([[14, 16],
       [28, 32]])

In [394]:
ABbyOuterSum = outer1 + outer2
ABbyOuterSum

array([[19, 22],
       [43, 50]])

In [395]:
def product_by_sum_of_outer(A, B):
    if A.shape[1] == B.shape[0]:
        rows1, cols1 = A.shape
        rows2, cols2 = B.shape
        outer_product = np.zeros((rows1, cols2))
        for i in range(0, cols1):
            # print(A[:, i].reshape(-1, 1) @ B[i, :].reshape(1, cols))
            outer_product += A[:, i].reshape(-1, 1) @ B[i, :].reshape(1, cols2)
            print("--------------")
        print(outer_product)
        return outer_product
    else:
        print("incompatible shapes")
        print(A.shape)
        print(B.shape)
        return False

In [396]:
A = np.array([
              [1, 2], 
              [3, 4]
])
B = np.array([
              [5, 6], 
              [7, 8]
])

abBySumOfOuter = product_by_sum_of_outer(A,B)

--------------
--------------
[[19. 22.]
 [43. 50.]]


In [397]:
abDirectly = A @ B
abDirectly

array([[19, 22],
       [43, 50]])

In [398]:
np.isclose(abBySumOfOuter, abDirectly)

array([[ True,  True],
       [ True,  True]])

In [399]:
A = np.array([[1, 2, 5], 
              [3, 4, 2],
              [7, 8, 1]
])
B = np.array([
              [5, 6, 12], 
              [7, 8, 0],
              [3, 4, 2]
])

# outer(A,B)

In [400]:
A32 = np.array([
              [1, 2], 
              [3, 4],
              [8, 0]])

A23 = np.array([
              [1, 2, 4], 
              [3, 4, 7]])

In [401]:
a3223directly = A32 @ A23
a3223directly

array([[ 7, 10, 18],
       [15, 22, 40],
       [ 8, 16, 32]])

In [402]:
a3223BySumOfOuter = product_by_sum_of_outer(A32, A23)

--------------
--------------
[[ 7. 10. 18.]
 [15. 22. 40.]
 [ 8. 16. 32.]]
